### ISSUE TITLE
Retrieve Swagger JSON spec from endpoint instead of static definition

### ISSUE THREAD

**Issue by julioolvr** [scottie1984/swagger-ui-express#1]
I'm looking for a way to add Swagger documentation for my Express API generated by comments inlined in the code. [swagger-jsdoc](https://github.com/Surnet/swagger-jsdoc) seems like a cool project to do that, and it serves the documentation generated on an endpoint in the app. I think it'd work very nicely with this project, if I were able to configure `swagger-ui-express` to use a specific URL instead of a static JSON object as its source. What do you think about it? I can try and send a PR this weekend if you like the idea.

**Comment by scottie1984** [comment]
I believe this is already possible. Just pass the swagger spec into the setup function:

```javascript

// Initialize swagger-jsdoc -> returns validated swagger spec in json format
const swaggerSpec = swaggerJSDoc(options);

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
```
No need to serve the swagger document via an endpoint

Let me know if that works.

**Comment by julioolvr** [comment]
Yes, my bad, I was under the assumption that `swagger-jsdoc` only produced the spec through an endpoint but it actually generates the spec object. Thanks, sorry for the inconvenience!

**Comment by scottie1984** [comment]
No problem - I will update the documentation.
