### ISSUE TITLE
Is there a way to keep original favicon?

### ISSUE THREAD

**Issue by fiibbb** [scottie1984/swagger-ui-express#10]
Thanks for this great library!

Currently when I load the swagger route in my app, the favicon changes to the green-ish Swagger favicon. Is there an option to keep my app's original favicon?

**Comment by scottie1984** [comment]
Added another option to specify your favicon e.g.:
```
swaggerUi.setup(swaggerDocument, false, options, '', 'path/to/favicon')
```
The path should be the path it is served to the user.

Let me know.

**Comment by leeuwis** [comment]
When I add the favicon the options do not work anymore @scottie1984

**Comment by asotoglez** [comment]
Works for me

**Comment by asotoglez** [comment]
> Added another option to specify your favicon e.g.:
> 
> ```
> swaggerUi.setup(swaggerDocument, false, options, '', 'path/to/favicon')
> ```
> 
> The path should be the path it is served to the user.
> 
> Let me know.
Works great for me
