### ISSUE TITLE
Hash navigation without function since 4.0.0

### ISSUE THREAD

**Issue by leachiM2k** [scottie1984/swagger-ui-express#100]
Hello,
first I want to thank you for this package. It makes our daily work easier and faster.

I think there is a bug in the current release.
In 3.x I could open links like http://localhost/swagger-ui/#/default/get_foo and the UI just jumped to the right method and unfolded it.
Since upgrade to 4.0.0 nothing special happens when I open this URL.

We‘ve used this nifty feature to share links and I would love to see it back again.

**Comment by leachiM2k** [comment]
Ok, I just saw that this was fixed with swagger-ui@3.18.3
When I delete package-lock.json (or yarn.lock for yarn) I'll get the freshest swagger-ui-dist@3.19.4 and there is no issue with deeplinking.

Maybe it's worth to update the package.json in your repo? If it's not that important for you, please close this issue.

**Comment by scottie1984** [comment]
thanks - I will bump this during the next release.
