### ISSUE TITLE
is swagger-ui-express supports typescript ?

### ISSUE THREAD

**Issue by AhmadRaza786** [scottie1984/swagger-ui-express#102]
I have build my API in Typescript and now want to integrate the swagger-ui-express with it. Is it possible to integrate the swagger -ui-express with typescript. If yes, does it need any configurations with tsconfig.json or any other important instructions to do it ?

**Comment by scottie1984** [comment]
I believe if you follow the instructions in this comment:

[https://github.com/scottie1984/swagger-ui-express/issues/27#issuecomment-415341947](https://github.com/scottie1984/swagger-ui-express/issues/27#issuecomment-415341947)

You should have typescript support for this module.

**Comment by AhmadRaza786** [comment]
Thanks @scottie1984

**Comment by sachingoel** [comment]
@AhmadRaza786 
After adding swagger-ui-express types. It still throws  `Error: MESSAGE: Promise.map is not a function`

**Comment by mmiszy** [comment]
Yeah, it's broken. I don't understand why swagger-ui-express overrides `global.Promise` :|
