### ISSUE TITLE
typeScript support error in version ^4.0.0

### ISSUE THREAD

**Issue by sachingoel** [scottie1984/swagger-ui-express#103]
Package version above 4.0.0 throws an error in typescript.
Error- `MESSAGE: Promise.map is not a function`

This is basically in index.js while loading `var swaggerUi = require('swagger-ui-dist')` at Line 5

**Comment by scottie1984** [comment]
@shockey does swagger-ui-dist support typescript?

**Comment by sachingoel** [comment]
Hey @scottie1984 Any updates on this

**Comment by scottie1984** [comment]
@sachingoel I haven't been able to replicate your problem. Do you have any steps? 

I created an index.ts with the following:

```
import { 
  setup,
  serve,
  serveWithOptions,
  generateHTML,
  serveFiles 
} from 'swagger-ui-express'

setup()
serve()
serveWithOptions({})
generateHTML()
serveFiles()
```

and the following package.json

```
{
    "dependencies": {
        "swagger-ui-express": "latest",
        "@types/swagger-ui-express": "latest"
    }
}
```

and ran tsc index,ts and didn't retrieve any error.
