### ISSUE TITLE
How is it possible to make different sections in a same swagger.json?

### ISSUE THREAD

**Issue by inane** [scottie1984/swagger-ui-express#104]
Hello,

I would like to do different sections in a same swagger.json file. Scenario is a middleware application this file should be accesible from different clients and independent, all centralized here.

Is it possible this approach?

Thank you.

**Comment by scottie1984** [comment]
Hopefully this issue will help [https://github.com/scottie1984/swagger-ui-express/issues/69](https://github.com/scottie1984/swagger-ui-express/issues/69)
