### ISSUE TITLE
data post not sent

### ISSUE THREAD

**Issue by guenn** [scottie1984/swagger-ui-express#11]
Hello,

I'm trying ti use the swagger-ui-express for my application. 
All work fine, but when i try to use "post" data in the swagger-ui, they aren't send to my application.

Extract of my swagger.json 
"parameters": [
                    {
                        "name": "match",
                        "in": "query",
                        "description": "pattern de recherche dans l annuaire",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "p",
                        "in": "query",
                        "description": "Numéro de la page.",
                        "required": false,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "in": "body",
                        "name": "authentification",
                        "required": true,
                        "description": "login/mdp LDAP",
                        "schema": {
                            "$ref": "#/definitions/authentification"
                        }
                    }
                ]

The "Curl" generated code works, but in the web swagger ui part, i have a 400 error code.
If i check the network, we can see that the "post" data aren't send to my server.

Do you know why ?

If i test without authentication (delete all post data needed), all work fine too.

**Comment by scottie1984** [comment]
I think the issue you are having is related to swagger-ui. Swagger-ui-express is simply a wrapper around swagger-ui.

My suggestion is that you look into swagger-ui for this problem, a quick google and I can see the following which may be related:

https://github.com/noirbizarre/flask-restplus/issues/15

Also perhaps look into the basePath in the swagger.json, as I have had issues before when this wasn't set correctly.

Sorry couldn't be of any more help.

**Comment by guenn** [comment]
Ok. Thanks for the reply.

You're right, it a swagger-ui issue: 
[https://github.com/swagger-api/swagger-ui/issues/513](url) 

Sorry for the inconvenience.
