### ISSUE TITLE
Request body doesn't show

### ISSUE THREAD

**Issue by MarkAdell** [scottie1984/swagger-ui-express#113]
Here is my swagger jsdoc :-
```
/**
 * @swagger
 * /products/categories:
 *   post:
 *     tags:
 *       - Products
 *     summary: Adds new category
 *     requestBody:
 *       description: A JSON object containing category information
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - title
 *             properties:
 *               title:
 *                 type: string
*/
```
Here is swagger ui express output for this endpoint :-

![image](https://user-images.githubusercontent.com/18086162/52216680-79ce8700-289f-11e9-88ce-b1c039d7aefd.png)

Why doesn't the body appear?

**Comment by scottie1984** [comment]
Can you make sure the swagger document output from swagger-jsdoc is OAS3.

**Comment by MarkAdell** [comment]
Here is swagger-jsdoc output

```
post:{  
   tags:[  
      "Products"
   ],
   summary:"Adds new category",
   requestBody:{  
      description:"A JSON object containing the category information",
      required:true,
      content:{  
         application/json:{  
            schema:{  
               type:"object",
               required:[  
                  "title"
               ],
               properties:{  
                  title:{  
                     type:"string"
                  }
               }
            }
         }
      }
   }
}
```

**Comment by scottie1984** [comment]
You will need to check the full swagger-jsdoc output. Specifically you will need to see ``` openapi: "3.0.0"```

**Comment by MarkAdell** [comment]
Ah it was set to `2.0.0`. I set it to `3.0.0` and it worked fine. Thanks!

**Comment by Dharanikanna** [comment]
@MarkAdell, I have the same issue. But in my case `openapi: '3.0.0'`

**Screenshot for reference**

![image](https://user-images.githubusercontent.com/55808143/150107112-42a1d7ef-32bb-48f1-bcdb-0513c0d83250.png)


**Swagger-jsdoc output**

`
{
  openapi: '3.0.0',
  info: { title: 'Node API', version: '1.0.0' },
  paths: {
    '/user/register': { post: [Object] },
    '/healthcare/heroku': { get: [Object] },
    '/healthcare/getall': { get: [Object] },
    '/healthcare/id': { get: [Object] }
  },
  components: { schema: { users: [Object] } },
  tags: []
}
`

**Code for reference**

```nodejs
//user login routes
router.post('/login',user.login)


/**
 * @swagger
 *  components:
 *      schema:
 *          users:
 *              type: object
 *              properties:
 *                  email:
 *                      type: string
 *                  password:
 *                      type: string 
 */


/**
 * @swagger
 * /user/login:
 *   post:
 *     summary: Login
 *     description: Login User
 *     requestBody:
 *       required:true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#components/schema/users'
 *     responses:
 *       201:
 *         description: User Logged in successfuly
 *         schema:
 *           type: "string"
 *       "400":
 *         description: "Invalid username/password supplied"
 */

**Comment by ab958** [comment]
same issue

**Comment by medisoft** [comment]
I have the same issue. The swagger looks correct on the swagger editor and with redocly tool, but not with this lib

This is the swagger on json

`{
  "openapi": "3.0.0",
  "info": {
    "title": "Some API",
    "description": "TBD description in [CommonMark](http://commonmark.org/help/) or HTML.",
    "version": "0.0.1"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Local Development"
    }
  ],
  "paths": {
    "/auth": {
      "post": {
        "summary": "Login user",
        "description": "Login user",
        "responses": {
          "200": {
            "description": "Login successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponseSchema"
                }
              }
            }
          },
          "202": {
            "description": "Additional action required",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "example": false
                    },
                    "message": {
                      "type": "string"
                    },
                    "error": {
                      "type": "string"
                    },
                    "payload": {
                      "type": "object",
                      "properties": {
                        "Session": {
                          "type": "string"
                        },
                        "requiredAttributes": {
                          "type": "string"
                        },
                        "userAttributes": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Login failed",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "example": false
                    },
                    "message": {
                      "type": "string",
                      "example": "authentication error"
                    },
                    "error": {
                      "type": "string",
                      "example": "Incorrect username or password."
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "description": "The username and password object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string",
                    "example": "mywonderfulusername"
                  },
                  "password": {
                    "type": "string",
                    "example": "ab123.zAA"
                  }
                },
                "required": [
                  "username",
                  "password"
                ]
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "LoginResponseSchema": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "payload": {
            "type": "object",
            "properties": {
              "AccessToken": {
                "type": "string"
              },
              "IdToken": {
                "type": "string"
              },
              "RefreshToken": {
                "type": "string"
              },
              "ExpiresIn": {
                "type": "integer"
              },
              "TokenType": {
                "type": "string"
              }
            }
          }
        }
      },
      "SuccessResponseSchema": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "default": true
          },
          "message": {
            "type": "string"
          },
          "payload": {
            "oneOf": [
              {
                "type": "string"
              },
              {
                "type": "object"
              },
              {
                "type": "array"
              }
            ]
          }
        }
      },
      "ErrorResponseSchema": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "default": false
          },
          "error": {
            "type": "string"
          }
        }
      }
    }
  },
  "tags": []
}
`
