### ISSUE TITLE
Oauth2 Authorization Code flow, can't log in after log out

### ISSUE THREAD

**Issue by NikitaKrivenko** [scottie1984/swagger-ui-express#115]
**Steps to reproduce:**

1. Authorize with Oauth2 Authorization Code flow
2. Press Log Out
3. Try to authorize again

**Expected result:**
You can successfully log out and authorize again

**Actual result:**
Authorization after log out is failed

It seems that log out functionality does not flushes authorization **code** received after successful auth. When you log out and logging in again token request sent again with the same code, not with the new one.

**Comment by scottie1984** [comment]
This is likely an issue with swagger-ui (which is a dependency of this module). I can see a similar issue here but don't see a solution [https://github.com/swagger-api/swagger-ui/issues/3368](https://github.com/swagger-api/swagger-ui/issues/3368)

I suggest creating an issue with swagger-ui.

**Comment by NikitaKrivenko** [comment]
@scottie1984 thanks!
Here is the link on created issue https://github.com/swagger-api/swagger-ui/issues/5172 in case if someone experience the same.
