### ISSUE TITLE
Explorer not working

### ISSUE THREAD

**Issue by mue-barakat** [scottie1984/swagger-ui-express#116]
When i set explorer:true in options and use the explorer bar to search i always get

```
Errors
Hide
 
Parser error on line 13
end of the stream or a document separator is expected
```
```
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./swagger.json');
var options = {
	explorer: true,
};
app.use('/apidocs', swaggerUi.serve, swaggerUi.setup(swaggerDocument,options));
```
it doesn't matter if it's yaml or json, also i tried the test json it has the same error too

**Comment by mue-barakat** [comment]
OS: Windows 10
NodeJS Version: 10+

**Comment by BasilaryGroup** [comment]
The explorer allows you to open a different OpenAPI JSON file, it is not a search. 

For example, enter
```
https://petstore.swagger.io/v2/swagger.json
```
and press **Explore** to load the Swagger Petstore Demo.

**Comment by talatkuyuk** [comment]
I have the same issue. I could not figure out how I can utilize with the Explore button.

My swagger express ui actually parses an api definition yaml file, and works well.

But, if I try to explore something it throws stream error or try to open a different OPENAPI JSON file it throws an error related with CORS. The explore search bar should be related with my api definition in my opinion. I could not understand how the explore works.
