### ISSUE TITLE
Using JWT bearer token, "h.forEach is not a function"

### ISSUE THREAD

**Issue by SaucyJack** [scottie1984/swagger-ui-express#118]
I've got an OAS set up with two defined paths: 

`/auth/login` - unsecured
`/users/{id}` - secured, requires JWT

My security definition (some sections omitted to keep this from getting long):

```json
"openapi": "3.0.0",
"info": {
},
"host": "localhost:4000",
"basePath": "/",
"components": {
  "securitySchemes": {
    "bearerAuth": {
      "type": "http",
      "scheme": "bearer",
      "bearerFormat": "JWT"
    }
  },
  "schemas": {
   }
},
"security": {
  "bearerAuth": []
},
```

Then, in my `paths` (again, some stuff omitted for brevity):

```json
"/auth/login": {
  "post": {
    "security": [],

  }
},
"/users/{id}": {
  "get": {
    
  }
}
```

When I load up SwaggerUI, I am able to "Try it out" with the`/auth/login` endpoint and grab the JWT from the result. Then, I can paste it into the `bearerAuth` value provided by the "Authorize" button in the top right above the path listings. But, if I then attempt to hit the `/users/{id}` endpoint using the "Try it out" code, it hangs with a "Loading" indicator under the "Execute" button. If I open debugging tools, I see that it never sent the HTTP GET to the server, and this error is in the console:

```
TypeError: h.forEach is not a function
    at o (index.js:1)
    at t.default (index.js:1)
    at Object.o [as buildRequest] (index.js:1)
    at actions.js:415
    at utils.js:121
    at bindActionCreators.js:3
    at wrap-actions.js:33
    at Object.r (system.js:174)
    at Object.executeRequest (system.js:461)
    at actions.js:455
```

If I add `security: []` to the `/users/{id}` path (making it unsecured) and then remove security from the route (I am coding the API so can do this easily), "Try it out" works perfectly. Further, I know the JWT in the bearer works as I can do the exact same request in Postman and it works correctly.

Is this a bug in swagger-ui-express, or am I doing something wrong in my spec? Please let me know if I should provide the entire OAS file (it isn't huge, but it's big enough to make a post pretty long), screenshots, or anything else that might help. I am stuck.

**Comment by shockey** [comment]
This looks like a Swagger UI issue to me.

Have you checked your definition in Swagger Editor to make sure there are no validation errors? Sometimes the UI doesn't take kindly to errors or omissions.

**Comment by SaucyJack** [comment]
I have not, did not even know this was a possibility. I'll do so now and come back and close when I figure it out. Thank you for your prompt attention!

**Comment by SaucyJack** [comment]
Yes! Thank you so much! It was actually an error in the `requestBody` definition from the `/auth/login` path that was screwing everything up downstream.

**Comment by shockey** [comment]
Glad to hear you got it fixed! Happy I could help.
