### ISSUE TITLE
securityDefinitions not supported

### ISSUE THREAD

**Issue by TuureKaunisto** [scottie1984/swagger-ui-express#12]
I noticed securityDefinitions are not supported or at least the authorize button does not appear like it does in [Petstore](http://petstore.swagger.io/) with a valid security definition:
```
securityDefinitions: {
   api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header"
   }
}
```

This is most likely due to an old version of Sawgger UI. How about loading the dependencies from a CDN ( https://cdnjs.com/libraries/swagger-ui ) or NPM?

**Comment by scottie1984** [comment]
Is it related to this issue:

https://github.com/swagger-api/swagger-ui/issues/1108

My next task is to update the version of Swagger UI, however I can't use the a CDN or NPM as I modify one of the files - certainly without having to make significant changes.

**Comment by TuureKaunisto** [comment]
The issue you linked is not related since the security definitions do work when I explore the JSON with the latest version of Swagger UI.

Good to know that you're planning to update the Swagger UI version! :) I didn't know you had to make changes to the Swagger UI files.
