### ISSUE TITLE
Unable to change favicon

### ISSUE THREAD

**Issue by PuneetKohli** [scottie1984/swagger-ui-express#122]
Hi,

I've been debugging trying to change the favicon in my project that uses swagger-ui-express with swagger-js-doc.

```
// this is my index.js -- path is server/routes/index.js
const specs = swaggerJsdoc(swaggerJsOptions);

const uiOpts = {
    customSiteTitle: "Title",
    customFavIcon: "/favicon.ico"
};

router.use('/', swaggerUi.serve, swaggerUi.setup(specs, uiOpts));
```

My directory structure is as follows
server/
-- controller/
-- model/
-- routes/
---- index.js
---- favicon.ico
-- app.js
-- package.json

I run `npm start` from the root `server/` folder.

I have also tried adding the favicon.ico inside the `server/` folder but that did not work as well.

I also tried adding the favicon.ico file inside a `static/` folder and enabling `app.use(express.static('/static'));` in my `app.js` but it did not change the favicon.

**Comment by scottie1984** [comment]
Issue responded to https://github.com/scottie1984/swagger-ui-express/issues/123#issuecomment-492026055 , You need to serve the favicon out independently from this module and customFavIcon needs to be the public path to the favicon (the path that is needed from the browser)

**Comment by PuneetKohli** [comment]
"The public path to the favicon"

Based on my structure provided above, can you please help me understand which path that should be?

**Comment by PuneetKohli** [comment]
I was unable to get this to work by placing the favicon in the `server` as well as the `routes` folder. 

```
// this is my index.js -- path is server/routes/index.js
const specs = swaggerJsdoc(swaggerJsOptions);

const uiOpts = {
    customSiteTitle: "Leia Multiview",
    customFavIcon: "./favicon.ico"
};

router.use('/favicon.ico', express.static('./favicon.ico'));
router.use('/', swaggerUi.serve, swaggerUi.setup(specs, uiOpts));
```

**Comment by scottie1984** [comment]
It would be something like this:

```js
const uiOpts = {
  customSiteTitle: "Leia Multiview",
  customfavIcon: "/assets/favicon.ico"
};

app.use('/assets', express.static('assets'));
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, uiOpts));
```
Where the favicon is in a folder called assets. This is not in the documentation as it very much depends on your express app set up - but ultimately you need to serve the favicon (using express of otherwise) and the customfavIcon to this module is the public url that the clients browser would use to access the favicon.
