### ISSUE TITLE
Update README and examples

### ISSUE THREAD

**Issue by PuneetKohli** [scottie1984/swagger-ui-express#123]
I've been trying to use this library to generate a good Swagger UI but the documentation and examples are incomplete.

Could you please add examples for adding a custom favicon, custom js, css etc?

If possible please also update the documentation with some sample code for the same as well.

**Comment by shockey** [comment]
You should be able to get a custom favicon by simply serving your own, e.g.:

```js
const express = require('express');
const app = express();
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./swagger.json');

app.use('/api-docs/favicon.ico', express.static('./assets/favicon.ico') // note: the path is relative to `process.cwd()`, not necessarily the script's location, if I remember correctly
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
```

[Custom CSS](https://github.com/scottie1984/swagger-ui-express#custom-css-styles) and [custom JS](https://github.com/scottie1984/swagger-ui-express#custom-js) is documented 😄

**Comment by PuneetKohli** [comment]
Could you please update the Custom CSS and Custom JS documentation to provide an example ? Simply creating a custom.js file and adding a simple `console.log('Hello World');` to it does not do anything which leads me to believe there are more steps required than documented currently.

This is a really useful library and want to use it to its maximum potential, and hope others can too - with improved documentation :)

**Comment by scottie1984** [comment]
i have updated the documentation to refer to the fact that the custom js file must be hosted and served outside of this module. The path passed into this module is the public url of the js file from the clients browser. Hope that clears things up.
