### ISSUE TITLE
Question and willingness to contribute docs

### ISSUE THREAD

**Issue by kahunacohen** [scottie1984/swagger-ui-express#125]
Hello, I'm not so clear from the docs if this package is just for generating docs from a swagger.json file...what else do I need for automatic validation of the actual controller? I assume the `operationId` key has something to do with this...mapping an endpoint/method with a controller, but it's not clear to me if this package handles that, or I need something else. Is that something else this? https://github.com/apigee-127/swagger-tools/

I know there's codegen, which hooks your spec file up by generating code from the spec file, but is it possible to hook the two up without using code-gen with an existing app?

I'm happy to contribute to the README to make this clearer to newbies like me. Thanks!

**Comment by scottie1984** [comment]
Hey, this package is just for generating and serving the docs based on the swagger.json file.

For generating the actual swagger.json file (and validation etc) you will need to use other modules. I can point you in the direction of https://www.npmjs.com/package/swagger-jsdoc as a start.

**Comment by kahunacohen** [comment]
Thanks I was able to successfully use the swagger-jsdoc package. Thanks. I will issue a PR to clarify in these docs.

**Comment by kahunacohen** [comment]
Do I fork and issue PR or create a new branch and issue a PR?

**Comment by scottie1984** [comment]
I think you have to fork and then PR
