### ISSUE TITLE
PUT, DELETE, POST method not working

### ISSUE THREAD

**Issue by gabhishekprdxn** [scottie1984/swagger-ui-express#126]
Hi Team,
Using this module I have built my APIs documentation. But when I'm requesting POST, PUT, PATCH, DELETE method from UI, then these all request do not hit my APIs and GET method is working properly. here is my sample code:

//Swagger configuration.
const swaggerJSDoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

let config = {};
config.swaggerDefinition = {
  'info': {
    'title': 'xxxxx',
    'version': '1.0.0',
    'description': 'Demonstrating RESTful APIs with Swagger.'
  },
  'host': process.env.HOST || 'localhost:8000',
  'basePath': '/api',
  'securityDefinitions': {
    'bearerAuth': {
      'type': 'apiKey',
      'name': 'Authorization',
      'scheme': 'bearer',
      'in': 'header'
    }
  }
}
config.swaggerOptions = {
  'customSiteTitle': 'xxxxxxxx',
  'customCss': '.swagger-ui .topbar { display: none }',
  'customfavIcon': 'xxxxxxx'
} 

const swaggerDefinition = config.swaggerDefinition;
const swaggerOptions = config.swaggerOptions;
const options = {
  swaggerDefinition,
  'apis': ['./src/routes/routes.js'],
}
const swaggerSpec = swaggerJSDoc(options);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec, swaggerOptions));

```/** 
 * @swagger
 * /image-folders/{folderId}:
 *  patch:
 *    tags:
 *      - Image Folders
 *    name: Rename Folder 
 *    summary: Rename the folder
 *    produces:
 *      - application/json
 *    consumes:
 *      - application/json
 *    parameters:
 *      - name: folderId
 *        in: path  
 *        type: string
 *        required: 
 *          - folderId
 *      - name: Body Data
 *        in: body
 *        type: object
 *        properties:
 *         title:
 *          type: string 
 *         parent:
 *          type: string
 *        required:
 *         - title
 *         - parent
 *    responses:
 *     '200':
 *        description: Folders hierarchy would be respond. 
 *     '400':
 *        description: Duplicate data provided in same batch.
 *     '500':
 *        description: Internal server error.               
 */
router.patch('/image-folders/:folderId', dependencies.imageFolder.updateFolder);

Could you explain where I'm wrong or is this module issue?
Thanks in Advance!

**Comment by scottie1984** [comment]
Hey - I don't think it will have anything related to this module, it is more likely your specific setup or an issue with swagger-ui or swagger-jsdoc. I would check that your api works correctly via postman or otherwise and ensure that the curl command in the UI matches the same route in postman.  Failing that place your sample app on github might help pin point.

**Comment by shockey** [comment]
Could be CORS.... are you seeing any errors in your browser console when using Swagger UI?

**Comment by gabhishekprdxn** [comment]
Thanks!! @scottie1984  and @shockey for your support.

I had not define schema in body data so that is why Execute button for PUT, DELETE, POST 
method was not working. Now issue is resolved.
