### ISSUE TITLE
Requesting index.html

### ISSUE THREAD

**Issue by sempasha** [scottie1984/swagger-ui-express#131]
Examples said to run express static middleware first to server swagger-ui-dist files, and express middleware which overrides swagger-ui-dist files next.

```
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
```

This cause unexpected behavoir. When you ask `GET /api-docs/index.html` server send you index.html from swagger-ui-dist, and you will see PetShop API documentation instead of your service API docs.

**Comment by scottie1984** [comment]
https://github.com/scottie1984/swagger-ui-express/issues/94#issuecomment-424836407

**Comment by sempasha** [comment]
Yes, it works. Sorry for duplicating issues.
But maybe it's better to modify middleware functions design.

# Actual design
Now we have `serve` middleware which:

  1. Send `swagger-ui-init.js` if requested `/swagger-ui-init.js`;
  2. Do `express.static` on swagger-ui-dist files.

And `setup` function which send modified `index.html`.

# Suggested design
Single `serve` middleware which performs all three actions:

  1. Send `swagger-ui-init.js` if requested `/swagger-ui-init.js`;
  2. Send modified `index.html` if requested `/index.html` or `/`;
  3. Server  swagger-ui-dist files with `express.static`.

Thank you.

**Comment by scottie1984** [comment]
Agreed - a new function with updated docs it probably the way to go so as to not break older clients (with a deprecated warning). Happy to take a PR if anyone is interested.
