### ISSUE TITLE
Use updated ui?

### ISSUE THREAD

**Issue by devkws** [scottie1984/swagger-ui-express#132]
Is there anyway to use the update swagger ui?

swagger-ui-express:
![image](https://user-images.githubusercontent.com/22294114/60106706-a8a4a700-9733-11e9-9a1e-df1643174707.png)

swagger with aspnetcore:
![image](https://user-images.githubusercontent.com/22294114/60106603-80b54380-9733-11e9-92aa-40afdd231f5e.png)

**Comment by scottie1984** [comment]
swagger-ui-express uses the latest swagger-ui via the swagger-ui-dist npm dependency. It looks like the aspnetcore is out of date. If you want to use a specific version of swagger-ui-dist you can enter this into your package.json

**Comment by devkws** [comment]
thank you very much, set the version to 3.0.6 for now and that did the trick!

**Comment by shockey** [comment]
@devkws I don't suggest using 3.0.6, there have been a few security updates to Swagger UI since then.

**Comment by devkws** [comment]
ok, maybe i will just push back the OCD and use the latest version haha
