### ISSUE TITLE
Required parameter does not work

### ISSUE THREAD

**Issue by sutbult** [scottie1984/swagger-ui-express#136]
When executing a request to an endpoint that has a required parameter without that parameter, the request is executed but it will never stop to load. This error message is displayed in the console:

`system.js:464 Error: Required parameter parameterName is not provided
    at index.js:1
    at Array.forEach (<anonymous>)
    at Object.o [as buildRequest] (index.js:1)
    at actions.js:415
    at utils.js:121
    at bindActionCreators.js:3
    at wrap-actions.js:33
    at Object.r (system.js:174)
    at Object.executeRequest (system.js:461)
    at actions.js:455`

The expected behavior would be to get some kind of red colored prompt clarifying that a required value is missing, not having to go to the console to look for error messages.

I am using version 4.0.7, which is the latest version as of writing.

**Comment by scottie1984** [comment]
Have you checked your Swagger file in the swagger editor https://editor.swagger.io/ ? Otherwise this would be an issue with swagger-ui and best placed raised directly with that project.
