### ISSUE TITLE
module specific documentation / multiple documentation files

### ISSUE THREAD

**Issue by skt1598** [scottie1984/swagger-ui-express#137]
There should be way to write documentation in multiple files module specific and then generate single documentation using all these files. Like module admin will contain documentation related to admin api's, user-auth module will contain documentation related to user auth api's and it should generate single documentation for all these files.

**Comment by scottie1984** [comment]
You should use [swagger-jsdoc](https://github.com/Surnet/swagger-jsdoc/blob/master/docs/GETTING-STARTED.md) to do this. This [article](http://www.acuriousanimal.com/2018/10/20/express-swagger-doc.html) explains how to do it.
