### ISSUE TITLE
documentation in route file

### ISSUE THREAD

**Issue by skt1598** [scottie1984/swagger-ui-express#138]
There should be a way to write documentation in route file like "apiDoc" so that we'll have documentation for every api with it. Then it'll become more readable and easy to modify. it'll also reduce the effort to find documentation for particular api. I was using "apiDoc" earlier for documentation but this time I thought about using "swagger-ui-express" as we can also test the api using swagger. But when I started using this I find it complex to use unlike "apiDoc" which is very simple to use.

**Comment by scottie1984** [comment]
This module is specifically for hosting your Swagger document. If you are not already using Swagger then it's not targeting that use case. You may want to look into [swagger-jsdoc](https://github.com/Surnet/swagger-jsdoc/blob/master/docs/GETTING-STARTED.md), which is a way to write swagger annotations within your code. From that you can generate a Swagger document that can be targeted to swagger-ui-express.
