### ISSUE TITLE
Router.use() requires callback functions but got a [object Array]

### ISSUE THREAD

**Issue by Ketan-saresa** [scottie1984/swagger-ui-express#139]
I don't know what am i doing wrong, it's a fresh express project, but when i start the server it shows me following error.. 
Error: Router.use() requires callback functions but got a [object Array]

I have tried in app.js and also in routes/index.js but nothing works out..

var express = require('express');
var swaggerUi = require('swagger-ui-express');
var swaggerDocument = require('./openApiDocumentation.json');

var routes = require('./routes/index');

var app = express();
app.use('/', routes);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

the error points at swaggerUI.serve

**Comment by scottie1984** [comment]
what version of Express are you using? Just looking at the docs of Express some of the features we are using require version 4.x.

**Comment by Ketan-saresa** [comment]
"express": "~4.0.0"
