### ISSUE TITLE
Possibility to make @Query optional?

### ISSUE THREAD

**Issue by SerdarN92** [scottie1984/swagger-ui-express#143]
Hi guys,

is there any possibility to make a Query-Param optional?

I already tried different things but did not reach what i want.

As example i have 3 Query-Params
`async test(
        @Query('a') a: string,
        @Query('b') b: string,
        @Query('c') c: string): Promise<any> {
    }`

How can i make the Query 'c' in the api-docs optional? It is always required.

**Comment by scottie1984** [comment]
In your swagger doc the following explains request query params https://swagger.io/docs/specification/describing-parameters/
