### ISSUE TITLE
Migrate to Swagger UI 3.23.0+

### ISSUE THREAD

**Issue by anton-yarchuk** [scottie1984/swagger-ui-express#147]
It would be nice to migrate to the newer version. 
For me, the reason is "multiple examples" for the request body.
https://github.com/swagger-api/swagger-ui/issues/2651

**Comment by scottie1984** [comment]
This modules uses swagger-ui-dist so the latest version  of swagger-ui should always be being picked up on install. If you are using some kind of lock file you may want to look into your dependancy tree.

**Comment by anton-yarchuk** [comment]
You are right, my bad.
Thank you very much!
