### ISSUE TITLE
Convert JSON and print in ui-express

### ISSUE THREAD

**Issue by jserra91** [scottie1984/swagger-ui-express#149]
I think that I found a possible error.

I'm using the swagger-jsdoc module to read all comments in my project, convert to JSON format and print into de swagger-ui-express.

``

    app.use(bodyParser.json()); // To support JSON-encoded bodies
    app.use(
        bodyParser.urlencoded({
            // To support URL-encoded bodies
            extended: true,
        })
    );

    const swaggerSpec = swaggerJSDoc(configurationSwagger);

    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
``

The problem it's that the Swagger (localhost:3000/api-docs) return a text plain. When I open with Mozilla Firefox and I inspect the HEADERS browsers, I found...
``
Content-Type | application/json; charset=utf-8
``

It's possible that not working fine? I'm using 4.1.2 version. Before I used the 4.1.1 version and I see the same error.

Return this JSON:
``
{"openapi":"3.0.0","info":{"title":"HolderService","version":"0.0","description":"Description of the implementation of HolderService"},"servers":[{"url":"http://localhost:3000","description":"Local server"},{"url":"http://localhost:3001","description":"Dev server"},{"url":"http://localhost:3002","description":"Prod server"}],"paths":{"/test":{"get":{"summary":"End-point to retrieve all test from a specific wallet.","description":"End-point to retrieve all test from a specific wallet.","tags":["Holder Service"],"parameters":[{"in":"header","required":true,"description":"This token will contains who is generating the schema","name":"Authorization","schema":{"title":"Authorization","type":"string"}}],"responses":{"200":{"$ref":"#/components/responses/responseCredential"},"400":{"$ref":"#/components/responses/responseError"},"401":{"$ref":"#/components/responses/responseError"},"409":{"$ref":"#/components/responses/responseError"},"500":{"$ref":"#/components/responses/responseError"}}}},"/test/{credentialId}":{"get":{"summary":"End-point
to retrieve a specific credential from a specific wallet.","description":"End-point to retrieve a specific credential from a specific wallet.","tags":["Holder Service"],"parameters":[{"in":"path","required":true,"name":"credentialId","schema":{"title":"credentialId","type":"string"}},{"in":"header","description":"This token will contains who is asking for the schema","required":true,"name":"Authorization","schema":{"title":"Authorization","type":"string"}}],"responses":{"200":{"$ref":"#/components/responses/responseCredential"},"400":{"$ref":"#/components/responses/responseError"},"401":{"$ref":"#/components/responses/responseError"},"409":{"$ref":"#/components/responses/responseError"},"500":{"$ref":"#/components/responses/responseError"}}}},"/test/store/{issuanceToken}":{"post":{"summary":"End-point to store a credential in his wallet by using a credential token provided by the issuer previously.","description":"End-point to store a credential in his wallet by using a credential token provided by the issuer previously.","tags":["Holder Service"],"parameters":[{"in":"header","description":"This token will contains who is generating the credential","required":true,"name":"Authorization","schema":{"title":"Authorization","type":"string"}},{"in":"path","required":true,"name":"issuanceToken","schema":{"title":"issuanceToken","type":"string"}}],"requestBody":{"$ref":"#/components/requestBodies/postCredential"},"responses":{"200":{"$ref":"#/components/responses/responseCredential"},"400":{"$ref":"#/components/responses/responseError"},"401":{"$ref":"#/components/responses/responseError"},"409":{"$ref":"#/components/responses/responseError"},"500":{"$ref":"#/components/responses/responseError"}}}}},"components":{"requestBodies":{"postCredential":{"description":"CredentialDao object","content":{"application/json":{"schema":{"$ref":"#/components/schemas/CredentialDao"}}}}},"responses":{"responseCredential":{"description":"Credential response","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Credential"}}}},"responseError":{"description":"Error response from the api","content":{"application/json":{"schema":{"$ref":"#/components/schemas/Error"}}}}},"schemas":{"Error":{"properties":{"status":{"type":"string","example":"bad request"},"message":{"type":"string","example":{"userId":"must be greater than 1"}}}},"Credential":{"properties":{"CredentialId":{"type":"string","example":"95b28890-e366-11e9-81b4-2a2ae2dbcce4"},"UserId":{"type":"string","example":"95b28890-e366-11e9-81b4-2a2ae2dbcce4"},"SchemaId":{"type":"string","example":"95b28890-e366-11e9-81b4-2a2ae2dbcce4"},"IssuanceToken":{"type":"string","example":"CCwrd04woNCCwrd04woNCCwrd04woN"},"AdaptorMasterSecretId":{"type":"string","example":"95b28890-e366-11e9-81b4-2a2ae2dbcce4"},"ProofingLevel":{"type":"string","example":"L2"},"CreatedOn":{"type":"string","example":"01/12/2019 12:01:15"},"CreatedBy":{"type":"string","example":"95b28890-e366-11e9-81b4-2a2ae2dbcce4"},"ModifiedOn":{"type":"string","example":"01/12/2019 12:01:15"},"ModifiedBy":{"type":"string","example":"95b28890-e366-11e9-81b4-2a2ae2dbcce4"}}},"CredentialDao":{"properties":{"UserId":{"type":"string","example":"95b28890-e366-11e9-81b4-2a2ae2dbcce4"},"SchemaId":{"type":"string","example":"95b28890-e366-11e9-81b4-2a2ae2dbcce4"},"IssuanceToken":{"type":"string","example":"CCwrd04woNCCwrd04woNCCwrd04woN"},"AdaptorMasterSecretId":{"type":"string","example":"95b28890-e366-11e9-81b4-2a2ae2dbcce4"},"ProofingLevel":{"type":"string","example":"L2"}}}}},"tags":[]}
``
(if you copy and paste to Swagger editor, it's working)

Kind regards,

**Comment by scottie1984** [comment]
Not sure what the issue is, swagger-ui-express will return the swagger-ui bound to your swagger document at /api-docs. I am not sure I am following what the issue is.
