### ISSUE TITLE
Swagger UI with validator

### ISSUE THREAD

**Issue by LadIQe** [scottie1984/swagger-ui-express#151]
Hello, is it possible to have swagger ui and validator? Im using your swagger-ui-express but I want to validate requests and responses. So Im using this:
https://www.npmjs.com/package/express-openapi-validator

But I have problem to make it work. Im in contact with validator developer and we are trying to find solution for this, but I would like to know, if your swagger is open to it.

My app.js code:
```
const express = require('express')
const swaggerUi = require('swagger-ui-express')
const cookieParser = require('cookie-parser')
const bodyParser = require('body-parser')
const OpenApiValidator = require('express-openapi-validator').OpenApiValidator
const documentation = require('./components/documentation')
const app = express()


app.use(bodyParser.json())
app.use(bodyParser.text())
app.use(bodyParser.urlencoded())
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser())

app.use('/', swaggerUi.serve, swaggerUi.setup(documentation))

new OpenApiValidator({
  apiSpec: documentation,
  validateResponses: true,
  securityHandlers: {
    bearerAuth: (req, scopes, schema) => {
      console.log(req, scopes, schema)
    }
  }
}).install(app)


app.use((err, req, res, next) => {
  // format error
  console.error(err, err.stack);
  if (!err.status && !err.errors) {
    res.status(500).json({
      errors: [
        {
          message: err.message,
        },
      ],
    })
  } else {
    res.status(err.status).json({
      message: err.message,
      errors: err.errors,
    })
  }
})

module.exports = app
```

Thank you

**Comment by scottie1984** [comment]
Hey - this module renders the swagger doc in the swagger ui. I'm not sure the particular issue you are having or what you are trying to achieve, I don't see any issue as to why the express-openapi-validator module wouldn't work.

However, always open to making changes if you are able to provide some insight into the problem.

**Comment by LadIQe** [comment]
Thank you for your reply. To make it more clear:

- our app is based on docker, react, node, express etc
- we have 2 BEs, one is for main API, where are posts, gets etc, this one is headed for production, second one is for OpenAPI documentation, where is your swagger ui, api documentation and also there should be validator, this one is only for development, so no production

Our BE for OpenAPI has main js file called app.js, you can see it in post above. Your swagger ui works great, also TRY IT OUT works perfect. So we only need validator. But with validator mentioned in post above, we cant make it work. UI works, also requests and responds works, but validation is not working.

Now we dont know if its problem with validator (we tried workarounds) or its problem with your UI, which is not created for validations, or if you know different validator, which works with your UI, it would be great to know it.

Thanks

**Comment by scottie1984** [comment]
If you call the API's directly (not via Swagger UI) does it validate correctly? I don't see any reason why this module would be interfering with the validation - as it simply serves the swagger ui . I think more likely there is an issue with the validator which is why I suggest testing without swagger-ui-express.

**Comment by LadIQe** [comment]
No it doesnt validate, because validator is outside of production BE, we want validator and UI only for development

**Comment by shockey** [comment]
@LadIQe, try moving your `new OpenApiValidator({ ... }).install(app)` block above where you're attaching swaggerUi to your `/` route.

**Comment by LadIQe** [comment]
@shockey i tried before and I got

```
starter-node-documentation       | { stack:
starter-node-documentation       |    'Error: not found\n    at Object.validationError (/usr/app/node_modules/express-openapi-validator/dist/middlewares/util.js:23:25)\n    at /usr/app/node_modules/express-openapi-validator/dist/middlewares/openapi.security.js:16:32\n    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/app/node_modules/express/lib/router/index.js:275:10)\n    at /usr/app/node_modules/express-openapi-validator/dist/middlewares/openapi.multipart.js:37:13\n    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)',
starter-node-documentation       |   message: 'not found',
starter-node-documentation       |   toJSON: [Function: toJSON],
starter-node-documentation       |   status: 404,
starter-node-documentation       |   errors: [ { path: '/', message: 'not found', errors: undefined } ],
starter-node-documentation       |   name: 'Error',
starter-node-documentation       |   toString: [Function: toString] } 
```

And this I believe is problem with validator or with paths
