### ISSUE TITLE
Problem with oauth2-redirect.html path.

### ISSUE THREAD

**Issue by lazyhamster** [scottie1984/swagger-ui-express#152]
Hi.
I have a minor issue with making swagger ui  in my express project to work with external oauth2 server. UI is served through /api-docs path like described in your docs. Everything is working great except UI gives oauth2 redirect url in format like this  http://localhost:3000/oauth2-redirect.html. Naturally Express returns 404 for it. File oauth2-redirect.html is present and available from /api-docs/oauth2-redirect.html like all files from swagger UI.
I've fixed this with simple redirect from /oauth2-redirect.html to /api-docs/oauth2-redirect.html. But it does not look like it is good approach. How can I configure oauth2-redirect.html path properly?

**Comment by scottie1984** [comment]
This looks like an open issue with swagger ui [https://github.com/swagger-api/swagger-editor/issues/1969](https://github.com/swagger-api/swagger-editor/issues/1969)

Until its fixed the my only other suggestion would be to serve swagger-ui under root / . e.g.

```js
app.use('/', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
```

**Comment by lazyhamster** [comment]
Yes, it does looks like the same issue. Thank you for the response. I though I missed something with configuration.

**Comment by jatinmehrotra** [comment]
> Hi.
> I have a minor issue with making swagger ui in my express project to work with external oauth2 server. UI is served through /api-docs path like described in your docs. Everything is working great except UI gives oauth2 redirect url in format like this http://localhost:3000/oauth2-redirect.html. Naturally Express returns 404 for it. File oauth2-redirect.html is present and available from /api-docs/oauth2-redirect.html like all files from swagger UI.
> I've fixed this with simple redirect from /oauth2-redirect.html to /api-docs/oauth2-redirect.html. But it does not look like it is good approach. How can I configure oauth2-redirect.html path properly?

can you tell how did you fixed this? like what was the redirect?
