### ISSUE TITLE
Reduce swagger-ui-bundle.js size?

### ISSUE THREAD

**Issue by biblioallen** [scottie1984/swagger-ui-express#154]
I'm hosting this on AWS and it takes almost 5s for swagger-ui-bundle.js to download. It's almost 1 MB in size. Any advice on how to speed this up or reduce the size of the file?

**Comment by scottie1984** [comment]
This file is provided via swagger-ui and is a dependency of this module. If your concern is the files sizes the recommendation from swagger is to use Swagger-Ui module itself - [https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/installation.md](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/installation.md). This however is outside the scope of this module.

**Comment by biblioallen** [comment]
is there anyway to make chrome cache this so that it doesn't download it everytime?

**Comment by scottie1984** [comment]
Should be able to pass options to the express.static function using serveWithOptions

```js
app.use('/api-docs', swaggerUi.serveWithOptions({ maxAge: 31557600 }))
```
