### ISSUE TITLE
implement OpenApi 3.0 ServerTemplating

### ISSUE THREAD

**Issue by jmjpro** [scottie1984/swagger-ui-express#156]
background: https://swagger.io/docs/specification/api-host-and-base-path

expected: when defining a server url with variable in the form {var1}, {var2}, the variables are replaced by their values in the variables section

actual: variables aren't replaced

**Comment by scottie1984** [comment]
Can you attach your swagger-ui-express setup and config? My suspicion is that you will need to pass the servers config as the urls property into the swaggerOptions like [this](https://www.npmjs.com/package/swagger-ui-express#load-swagger-from-url)

**Comment by jondoe1337** [comment]
Same Problem here:

Express code:
```
app.use('/', swaggerUi.serve, swaggerUi.setup(swaggerDocument, {
    swaggerOptions: {
        apiServerURL: 'https://localhost:8080'
    }
}))
```
Swagger.json:
```
  "servers": [
    {
      "url": "{apiServerURL}",
      "variables": {
        "apiServerURL": {
          "default": "https://production.example.com"
        }
      }
    }
  ]
```
Any hint on how this might work?

**Comment by scottie1984** [comment]
I am not sure but I was thinking something more like: 

```js
app.use('/', swaggerUi.serve, swaggerUi.setup(swaggerDocument, {
    swaggerOptions: {
    urls: [
      {
        url: 'http://petstore.swagger.io/v2/swagger.json',
        name: 'Spec1',
        variables: {}
      },
      {
        url: 'http://petstore.swagger.io/v2/swagger.json',
        name: 'Spec2',
        variables: {}
      }
    ]
  }
}))
```

So the swagger servers config is generated Server side rather than in the Json (though you could always modify the Json file with the relevant settings prior to inputing it into the module

**Comment by jondoe1337** [comment]
Ah now I get it, you mean to select between different swagger.json for different server configs?

**Comment by scottie1984** [comment]
Yea- and if you need the others in there then place them in with the templating being done on Express server

**Comment by jondoe1337** [comment]
Well that is the actual problem and what @jmjpro maybe has - we don't know how the templating works. In my example the variable is not replaced by that what I put in the swaggerOptions.

**Comment by scottie1984** [comment]
Are you just looking the swagger document to be relevant to the environment it is running on? In which case if you remove the servers sections of the swagger file, the swagger document will load and use the base path of the window as the url. Therefore allowing it to be relevant to the environment.

**Comment by jondoe1337** [comment]
The basePath workaround won't be useful for me at least as my url of the swagger-ui-express instance is different from the API I want to talk to.

What I'm trying is to use variables like [here](https://swagger.io/docs/specification/api-host-and-base-path) so that I can start a local swagger-ui-express instance which will talk to some other API url.

**Comment by scottie1984** [comment]
OK - I would look at https://www.npmjs.com/package/swagger-ui-express#load-swagger-from-url . The url in your case would be https://localhost:8080 (or the environment specific url - which you can load in from your config)
