### ISSUE TITLE
GET request with JSON querystring

### ISSUE THREAD

**Issue by Menci** [scottie1984/swagger-ui-express#158]
I am using DTOs and class-validator with a GET request endpoint in my controller. The input numeric ID is treated as a string so it doesn't pass the validation.

I was told in nestjs/nest#3541 to use this to let express parse my querystring as JSON:

```ts
app.use(bodyParser.urlencoded({ extended: true }))
```

But Swagger doesn't know this. It still provides me a urlencoded interface. So can I tell Swagger I'm using JSON querystring?

Here is how to define this in Swagger OpenAPI 3: https://stackoverflow.com/questions/34820064/defining-an-api-with-swagger-get-call-that-uses-json-in-parameters

**Comment by scottie1984** [comment]
this would be something to raise with swagger-ui themselves h[ttps://github.com/swagger-api/swagger-ui](https://github.com/swagger-api/swagger-ui). There is nothing particular in this module that would be stopping that from working other than making sure your swagger-ui-dist version is above Swagger UI 3.23.8 as mentioned in the Stackoverflow

**Comment by Menci** [comment]
But how can I tell Swagger that the `parameters` should be `application/json`?

**Comment by Menci** [comment]
I'll post my issue to nestjs/swagger. Thanks.
