### ISSUE TITLE
Failing to load assests from swagger-ui-dist

### ISSUE THREAD

**Issue by femioni** [scottie1984/swagger-ui-express#159]
I am new to this and most like am doing something wrong, but i can't get the ui to load due to failure to load assests from the `swagger-ui-dist` repo.

<img width="726" alt="Screenshot 2020-01-06 at 7 36 51 PM" src="https://user-images.githubusercontent.com/58427968/71839630-ecea0a00-30bb-11ea-9805-56b4e2f992ba.png">

I have looked into the index.js file it seem to expect those files to be in the same directory.

**Comment by scottie1984** [comment]
Can you post your express code for swagger-ui-express? Can you also verify swagger-ui-dist is in your node_modules folder?

**Comment by femioni** [comment]
```
const routes = require('express').Router()
const swaggerJsdoc = require('swagger-jsdoc')
const swaggerUi = require('swagger-ui-express')

const swaggerOptions = {
  swaggerDefinition: {
    openapi: '3.0.0',
    info: {
      title: 'Authentication, Authorization and User management Service for HalaTech',
      version: '1.0.0',
      description:
        'Auth0 integrated authentication and user mannagement service',
      license: {
        name: 'MIT',
        url: 'https://choosealicense.com/licenses/mit/'
      },
      contact: {
        name: 'Femi Oni',
        url: 'https://guidedlabs.io',
        email: 'femi.oni@guidedlabs.io'
      }
    },
    servers: [
      {
        url: 'http://localhost:3021/v1'
      }
    ]
  },
  apis: []
}
const specs = swaggerJsdoc(swaggerOptions)
routes.get('/v1', swaggerUi.setup(specs, { explorer: true }))

module.exports = routes
```

**Comment by scottie1984** [comment]
You are missing the swaggerUi.serve middleware in your example. The readme has further examples. This is why the assets are not available.

**Comment by femioni** [comment]
Sorry i updated the example. I had that on another file

**Comment by scottie1984** [comment]
The serve and setup need to be served from the same route. 

ie:
```js
app.use('/docs/v1', swaggerUi.serve)
app.use('/docs/v1', v1Docs)

routes.get('/', swaggerUi.setup(specs, { explorer: true }))
```

**Comment by freefony** [comment]
I am doing exactly that.  In app.js `v1Doc` is the `module.exports = routes` i exported above.
`const v1Doc = require('./docs/v1Docs')`

I have even tried combining it

`app.use('/docs/', swaggerUi.serve, swaggerUi.setup(specs, { explorer: true }))`
or in the router
`routes.get('/docs/', swaggerUi.serve, swaggerUi.setup(specs, { explorer: true }))`

both did not work

**Comment by scottie1984** [comment]
In your routes you are exporting it with /v1:

```js
routes.get('/v1', swaggerUi.setup(specs, { explorer: true }))
```

and the assets are coming from /docs. These need to be routed from the same place. My suggestion would be to start with a small sample application using one of the examples in the readme and then work from there.
