### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by artoodeeto** [scottie1984/swagger-ui-express#163]
Hello, This might be a dumb question but I don't need `swagger-jsdocs` to use this right?. I can just import my yaml file, Or do I have to create like:

```
/**
* @swagger
* ... document here
*/
```

I asked this because I already created documentation on swaggerhub.com and I think I'm repeating myself when I use jsdocs and my routes looks ugly with those long comments. thank you and appreciate the help.

**Comment by scottie1984** [comment]
No - you don't need to use swagger-jsdocs

This should help https://github.com/scottie1984/swagger-ui-express#load-swagger-from-yaml-file

**Comment by artoodeeto** [comment]
Thank for this. I was double-checking. ill close this now. thanks again.
