### ISSUE TITLE
How to use custom headers in "try it out"?

### ISSUE THREAD

**Issue by doron-au10tix** [scottie1984/swagger-ui-express#164]

**Comment by scottie1984** [comment]
This is the only thread I can find on the topic - https://stackoverflow.com/questions/41180615/how-to-send-custom-headers-with-requests-in-swagger-ui

Ultimately this will need to be resolved by [swagger-ui](https://github.com/swagger-api/swagger-ui)

**Comment by RajeshPolavarapu** [comment]
If your looking for pre request script processing  or setting headers based on headers you are already sending ( for example: sending from swagger are apikey and apiSecret and you are computing authorization header using apikey and apiSecret ) you can try the below for oas 3:
in options of swaggerUi.setup you can you requestInterceptor property of swaggerOptions
ex:
router.use( '/swaggerPath',swaggerUi.serve,swaggerUi.setup('/path/to/json/file',{ 
swaggerOptions:{ 
      requestInterceptor: (request)=>{
                     //logic goes here...get executed before your request is made
                    request.headers.Authorization = request.headers.apiKey+ request.headers.apiSecret;
       }
  }
}

**Comment by scottie1984** [comment]
If you want to add a PR for the readme then please do so. Otherwise I will close.

**Comment by lgubala** [comment]
> If your looking for pre request script processing or setting headers based on headers you are already sending ( for example: sending from swagger are apikey and apiSecret and you are computing authorization header using apikey and apiSecret ) you can try the below for oas 3: in options of swaggerUi.setup you can you requestInterceptor property of swaggerOptions ex: router.use( '/swaggerPath',swaggerUi.serve,swaggerUi.setup('/path/to/json/file',{ swaggerOptions:{ requestInterceptor: (request)=>{ //logic goes here...get executed before your request is made request.headers.Authorization = request.headers.apiKey+ request.headers.apiSecret; } } }

thanks Rajesh, it helped a lot...first i strugled with this, got errors in console ... the solution was to return the request after changing the headers
`requestInterceptor: (request)=>{
//logic goes here...get executed before your request is made
request.headers.Authorization = request.headers.apiKey+ request.headers.apiSecret;
return request;
}`

**Comment by danielschmitz** [comment]
i do this with `securityDefinitions` and `security` parameters in swagger.js:

```js
const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        title: 'Sales Server',
        description: 'Documentation API. https://github.com/danielschmitz/sales-server',
        version: '1.0',
    },
    host: 'localhost:3000',
    basePath: '/api',
    securityDefinitions: {
        bearerAuth: {
            type: 'apiKey',
            name: 'x-auth-token',
            scheme: 'bearer',
            in: 'header',
        },
    },
    security: [{ bearerAuth: [] }],
}

const outputFile = './src/swagger.json'
const endpointsFiles = [
    './src/api/category.js'
]
swaggerAutogen(outputFile, endpointsFiles, doc)
```

so a green Authorize buttons appers:

![image](https://user-images.githubusercontent.com/1509692/179788389-a27aac76-4b23-4955-bdd4-127df59f2c33.png)
