### ISSUE TITLE
Should use 'req.path' in 'swaggerInitFn'

### ISSUE THREAD

**Issue by awattez** [scottie1984/swagger-ui-express#165]
https://github.com/scottie1984/swagger-ui-express/blob/98f40f8d93254703b641e48e7d94b87e0ac479c7/index.js#L193

Could you please use 'req.path' in 'swaggerInitFn' in order to avoid bad next() call.

**Comment by scottie1984** [comment]
Are you able to provide more details on why it should change? I will close this for now - but please reopen with further details if you can.
