### ISSUE TITLE
Exposing two swagger Open api specs on same nodejs server via two different urls

### ISSUE THREAD

**Issue by DhruboB** [scottie1984/swagger-ui-express#166]
I like to expose two different swagger specs e.g. internal.json and external.json on node js server using swagger-ui-express npm package.

I have followed the instruction given https://www.npmjs.com/package/swagger-ui-express and any one of the swagger works with below code.

```
const express = require("express");
const swaggerUi = require('swagger-ui-express');
const internalSpec = require('../../swagger/internal.json');
const externalSpec = require('../../swagger/external.json');

module.exports = function (app) {
    const router = express.Router();

    router.use('/', swaggerUi.serve);
    router.get('/', swaggerUi.setup(internalSpec));

    app.use("/apispec", router);
};
```
But if I use router.get('/external', swaggerUi.setup(externalSpec)); again to access second Spec via ../apispec/external/ I can see the externalSpec in both /apispec & as well as /apispec/extenal urls. I suppose, swaggerUi.setup() of swagger-ui-express package creates a singleton instance of Swagger which overwrites earlier set up.

Any solution please ?

**Comment by scottie1984** [comment]
This might help https://github.com/scottie1984/swagger-ui-express/issues/65

**Comment by scottie1984** [comment]
Should be fixed at of 4.1.4

**Comment by oyvind-stenhaug** [comment]
This seems to have regressed in 4.1.5.

**Comment by scottie1984** [comment]
Yes - due to a more serious race condition. Can you try using the serveFiles? This function should deal with the issue.

```javascript
app.use('/api-docs', swaggerUi.serveFiles(swaggerDocument, options), swaggerUi.setup(swaggerDocument));
```

If you can confirm I will look to update the docs in the next version to specify this as being the preferred way to set up.

**Comment by oyvind-stenhaug** [comment]
Thanks. I'm guessing the `options` parameter should be the same as the one that is (optionally) passed to the `setup` function?

In my case I currently don't set any options, so I tried it without that parameter ( `app.use('/api-docs', swaggerUi.serveFiles(swaggerDocument), swaggerUi.setup(swaggerDocument));`), and that seems to work.

**Comment by scottie1984** [comment]
Yea thats right - I will look to update the instructions in the next release to recommend using this function.

**Comment by oyvind-stenhaug** [comment]
Sounds good.

**Comment by BIEMAX** [comment]
Hi,

I spent some time trying to find a solution to this problem and I solved this issue (in my case) with the following lines:

```javascript
const swaggerJSDoc = require('swagger-jsdoc');
const swaggerJsonVersion = require('./swagger.json');

const swaggerDocumentsSpecification = swaggerJSDoc({
    apis: [
       './routes/*.js'
    ],
    definition: swaggerJsonVersion 
});

const customOptions = {
    customSiteTitle: config.api.applicationName,
    customCss: '.swagger-ui .topbar { display: none }',
};

app.use('/', swaggerUi.serveFiles(swaggerDocumentsSpecification))
app.get('/', swaggerUi.setup(swaggerDocumentsSpecification, {}, customOptions))
```

With this, swagger could support multiple open api specs (without changing any other code), that in my case it's three different versions. I hope this can be usefull.

**Comment by scottie1984** [comment]
Documentation has been updated to reflect the serveFiles function https://github.com/scottie1984/swagger-ui-express#two-swagger-documents
