### ISSUE TITLE
not loading YAML File from outside src folder

### ISSUE THREAD

**Issue by alishah730** [scottie1984/swagger-ui-express#169]
my folder structure  like below
`src/
       -app.js
      -swagger.js
api.yaml
`
loading file in app.js like below

`
const swaggerDocument1 = YAML1.load("../api.yaml");
`
giving error 

```
Error: ENOENT: no such file or directory, open '../api.swagger.yaml'
    at Object.openSync (fs.js:443:3)
```

**Comment by scottie1984** [comment]
The error references file '../api.swagger.yaml'?

**Comment by alishah730** [comment]
no thats jsut copy paste mistake... my reference is correct

**Comment by alishah730** [comment]
![image](https://user-images.githubusercontent.com/15693925/77114718-c3c6ed80-6a0b-11ea-9be7-27c02f2d5aca.png)

**Comment by scottie1984** [comment]
yamljs seems to reference the yaml file from the location of the node command. So the 

```js
const swaggerDocument = YAML.load('../api.swagger.yaml')
```

should be

```js
const swaggerDocument = YAML.load('./api.swagger.yaml')
```

**Comment by alishah730** [comment]
Thanks, its working now... no sure why it was giving error even after so many try with both
`../` and  `./`

closing
