### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by fcpauldiaz** [scottie1984/swagger-ui-express#17]
When I setup this package on the root route, all my api endpoints fail to work.

````

app.use('/', swaggerUi.serve, swaggerUi.setup(swaggerDoc, false, options, '.swagger-ui .topbar { background-color: rgb(112, 111, 111); }'));
````

How can I fix this?

**Comment by scottie1984** [comment]
Make sure your endpoints are defined before the swagger-ui-express line, e.g.:

```code
app.get('/test', function(req, res) { res.json({ status: 'OK'}); });
app.get('/bar', function(req, res) { res.json({ status: 'OKISH'}); });

app.use('/', swaggerUi.serve, swaggerUi.setup(swaggerDocument, false, options, '.swagger-ui .topbar { background-color: red }'));
```

Hope that helps.

**Comment by fcpauldiaz** [comment]
That helped. Now my endpoints are working but now when I request a non existing route,  the swagger html is sent. 

For example if I request `localhost:3000/hdhdjsksk` the swagger html is sent. What can I do?

**Comment by fcpauldiaz** [comment]
I tested this on the test app of this github and everything after main route is matched `localhost:3000/api-docs/znxnxnsk`

**Comment by scottie1984** [comment]
You can place some middleware in to handle the matching as you require. Something like this would work:

```code
const pageNotFound = (req, res, next) => {
	if (req.url !== '/') {
		res.send(404, 'Page not found');
	} else {
		next();
	}
}

app.use('/api-docs', swaggerUi.serve, pageNotFound, swaggerUi.setup(swaggerDocument, false, options, '.swagger-ui .topbar { background-color: red }'));
```

**Comment by fcpauldiaz** [comment]
Based on your idea I made some regex matches. This solves the problem but it feels like a hack to fix it like this. I still think that the problem relies on this package.

```js
app.use((req, res, next) => {
  const match = req.url.match(/^\/v1\/.+/);
  const matchExtensions = req.url.match(/\.[a-z]{1,3}$/i);
  if (match !== null
      || req.url === '/'
      || matchExtensions !== null) {
    return next();
  }
  const err = new APIError('API not found', httpStatus.NOT_FOUND);
  return next(err);
});
```

**Comment by scottie1984** [comment]
Possibly a better solution:

```code
app.use('/api-docs', swaggerUi.serve)
app.get('/api-docs', swaggerUi.setup(swaggerDocument, false, options, '.swagger-ui .topbar { background-color: red }'));
```

**Comment by fcpauldiaz** [comment]
I found a better solution, but just for me now. Replaced this function in this [line[https://github.com/scottie1984/swagger-ui-express/blob/master/index.js#L27]

```js
return function(req, res, next) { 
      if (req.url === '/' ) {
        res.send(htmlWithFavIcon) 
      }
      else {
        next();
      }
    };
```
