### ISSUE TITLE
multiple swagger files with Explorer bar by doc not url 

### ISSUE THREAD

**Issue by menasheAtias** [scottie1984/swagger-ui-express#170]
hi
I couldn't find a way to use the contents of swagger file with Explorer bar for multiple files
there is a way to use file content to display multiple files  with Explorer bar , like with using URL?
Something like that?
     app.use('/swagger', swaggerUi.serve, swaggerUi.setup(null, {
      explorer: true,
      swaggerOptions: {
        urls: [
          {
            url: YAML.load('./docs/link1.yaml'),
            name: 'link1'
          },
          {
            url: YAML.load('./docs/link2.yaml'),
            name: 'link2'
          }
        ]
      }
    }));
Thank you

**Comment by akshaybathija** [comment]
Hi Team,

Is there any ETA for this feature to be added to the Library, in need for a similar use case and need this exact feature for it

**Comment by scottie1984** [comment]
The only way to achieve this would be to use Loading from the URL https://github.com/scottie1984/swagger-ui-express#load-swagger-from-url

where the URL are links to your hosted swagger files (you would have to host the swagger files from your Express server).

**Comment by akshaybathija** [comment]
> The only way to achieve this would be to use Loading from the URL https://github.com/scottie1984/swagger-ui-express#load-swagger-from-url
> 
> where the URL are links to your hosted swagger files (you would have to host the swagger files from your Express server).

Using the express server was able to implement it, Thanks mate.
