### ISSUE TITLE
Swagger not sending body in the post request.

### ISSUE THREAD

**Issue by ZPLSSSTD** [scottie1984/swagger-ui-express#171]
Hello author，Recently using swagger-ui-express plugin，I found that swagger didn't send body in the post request。Open F12, network, I found that the content-length in the request headers is equal to 0。Afterwards, I tried to reduce swagger-ui-express from the latest version to V2.0.8, and found that the above situation will occur once the swagger-ui-express is larger than V2.0.8.How do I fix this if I want to use the latest version。Waiting for your reply。Thanks

**Comment by scottie1984** [comment]
It might be best to search for this issue on https://github.com/swagger-api/swagger-ui. I have linked a very similar issue https://github.com/swagger-api/swagger-ui/issues/965

**Comment by ZPLSSSTD** [comment]
@scottie1984  
  thank you for your reply。Before I submitted this issue, I had searched for related answers in issues, but the answers in it did not solve my problem.So I tried to gradually downgrade from the latest version, until V2.0.8 can be used normally. In the process, I have not changed my code. The same code can no longer run in versions greater than V2.0.8
  Now I can only continue to use the V2.0.8 version. If there is a subsequent opportunity, I will try to use the latest version. Thanks again for your reply

**Comment by poslegm** [comment]
@ZPLSSSTD what is your openapi specification?

I had the same issue and fixed it by changing
```
parameters:
- in: "body"
  schema:
  ...
```

to

```
requestBody:
  content:
    application/json:
    ...
```

https://swagger.io/docs/specification/describing-request-body/

**Comment by ZPLSSSTD** [comment]
@poslegm 
First of all thank you for your reply.
The specification I used is 3.0.3.I have read the article at the address you provided. It seems to solve my problem.
I tried the method mentioned in the article and it solved my problem in the new version. But there is still a problem now, how to use Authorization as the request header. This key seems to be pre-defined, as long as I use other name request headers can be sent normally, but as long as Authorization is not used. I tried to set securitySchemes using the methods in other issues, but it didn't work.
The new version(4.1.4) is often stuck on some problems, and the old version(V 2.0.8) does not have these problems. Headache for this matter

**Comment by ZPLSSSTD** [comment]
header problem has been solved, thank everyone

**Comment by ZPLSSSTD** [comment]
@

**Comment by Lalo19** [comment]
You can try this

    "/your-path": {
        post: {
            summary: 'Example POST request',
            description: 'Test post',
            "consumes": [ "application/json" ],
            produces: ["application/json"],
            requestBody: {
                content: {
                    "application/json": {
                        schema: {
                            "properties": {
                                "user": {
                                    "type": "string"
                                },
                                "pass": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            responses: {
                '200': { "description": "OK" },
                '401': { "description": "Unauthorized" },
                '402': { "description": "Bad Request" },
                '500': { "description": "Internal Server Error" }
            }
        }
    }
