### ISSUE TITLE
The stylesheet ../swagger-ui.css was not loaded because its MIME type

### ISSUE THREAD

**Issue by TanyaDolgopolova** [scottie1984/swagger-ui-express#173]
I setup swaggerUI on nodejs application with typescript. For running a program I use webpack. But when I open the browser I get this error. What am I doing wrong? In my package.json:
`
"@types/swagger-jsdoc": "^3.0.2",
"@types/swagger-ui-express": "^4.1.2",
"swagger-jsdoc": "^4.0.0",
"swagger-ui-express": "^4.1.4",
`

![Screenshot from 2020-04-01 19-04-59](https://user-images.githubusercontent.com/35150766/78159791-b833e780-744b-11ea-90a6-403ee33dc857.png)

![Screenshot from 2020-04-01 18-05-14](https://user-images.githubusercontent.com/35150766/78153092-625b4180-7443-11ea-89de-ea40ad91b958.png)

**Comment by scottie1984** [comment]
Hey - I have been unable to replicate. What happens when you try to hit the URL for the CSS directly in the browser. That might give some hint as to what is going on. I suspect some other route in your application is responding.

**Comment by TanyaDolgopolova** [comment]
I have the same error when I try to hint at the URL for the CSS. I run the same code in the JS application and it works.
![Screenshot from 2020-04-02 11-14-53](https://user-images.githubusercontent.com/35150766/78225680-469f7c00-74d3-11ea-93d9-c396f486e10d.png)

![Screenshot from 2020-04-02 11-17-22](https://user-images.githubusercontent.com/35150766/78225889-91b98f00-74d3-11ea-93be-d5e1a64dd932.png)

**Comment by scottie1984** [comment]
OK - not sure what is happening. My only suggestion is to strip back the rest of your api code so that only the /docs route is active, if this works then start adding the remainder in until you find the cause. Also perhaps set up another small application with just swagger-ui-express running just to make sure your code set up is correct.

Also if you have the code hosted publicly, can you post the link here? Or attach?

**Comment by TanyaDolgopolova** [comment]
I created a repo with the minimal configuration from another repository. The same problem, what I do wrong? https://github.com/TanyaDolgopolova/nodejs-typescript-

**Comment by scottie1984** [comment]
Ok - the issue is webpack and can be resolved using the following https://github.com/scottie1984/swagger-ui-express/issues/90#issuecomment-578096992
