### ISSUE TITLE
swagger-ui-css-resource-not-found-in-production-mode

### ISSUE THREAD

**Issue by jagdishjadeja** [scottie1984/swagger-ui-express#174]
in productin mode css is not loading 

https://stackoverflow.com/questions/60082388/nestjs-swagger-ui-css-resource-not-found-in-production-mode

I am facing same issue as this link

**Comment by scottie1984** [comment]
Hi,

Does nestjs use webpack? Same issue with CSS not loading was resolved in webpack using the following solution https://github.com/scottie1984/swagger-ui-express/issues/90#issuecomment-578096992

Thanks
Stephen

**Comment by jagdishjadeja** [comment]
Thank you for response
I have already checked that issue
I am not using webpack only core nest and nodejs

**Comment by scottie1984** [comment]
Can you post a link to a simple repo that displays the issue? I am unfamiliar with NestJS and how it works for production mode. It might also be worthwhile raising with NestJS as they are more likely to understand why there is an issue. Ultimately this module assumes the CSS files etc will be included in any build process. A solution might be for you to have a build step which copies the files from the node_modules into the static assets.

**Comment by jagdishjadeja** [comment]
Hi
here is my code repo https://github.com/jagdishjadeja/nest-swagger-demo
here is url where app is hosted https://swagger-demo.now.sh/api/

**Comment by scottie1984** [comment]
Looks like you can configure webpack with Nest

https://github.com/nestjs/nest/tree/master/sample/08-webpack

You should be able to use this to copy in the css files as I previously mentioned. Either that or you add a script prior to build to copy in the css files  from node_modules into the dist folder

**Comment by jagdishjadeja** [comment]
is there any other option other than this?

**Comment by scottie1984** [comment]
Not that I am aware off - I am open to PRs or ideas for how to solve from any Webpack or NestJS experts :)

**Comment by jagdishjadeja** [comment]
Like editing index.html for swagger ? and adding another url/path of css file ?

**Comment by scottie1984** [comment]
Not that I can think of - this module relies on these files being
statically served by the application and it retrieves them from NPM. Adding
a url or path to the files is possible but by that stage it would probably
be easier to just download the swagger-ui files, host them and set them up
yourself.

 Adding a build step to this module is also possible. - however this is
probably best solved outside of this module, as it is mostly likely
build tool specific.

As mentioned before if someone provided a clean mechanism via a PR that
worked I would be happy to accept.
