### ISSUE TITLE
swagger-ui-express package could not be found

### ISSUE THREAD

**Issue by johnico** [scottie1984/swagger-ui-express#175]
I got this response while the app  is loading :

`The "swagger-ui-express" package is missing.`

Versions:
    "swagger-ui-express": "^4.1.4"

**code (Nestjs):**

```
`
async function bootstrap() {
  const app = await NestFactory.create(module);
    const options = new DocumentBuilder()
      .setTitle('title')
      .setDescription('desc')
      .setVersion('1.0')
      .build();
    const document = SwaggerModule.createDocument(app, options);
    SwaggerModule.setup('api', app, document);

}
bootstrap();
`
```

**Comment by scottie1984** [comment]
Is swagger-ui-express a devDependency or dependency?

Without the docker build process and starting the app does it work? Do other packages give the same error? My guess is that your build process with Docker is the issue - I don’t think there is an issue with this module.

**Comment by johnico** [comment]
hi @scottie1984 
everything is working good in my local
swagger-ui-express is in dependency

npm install --production make the issue , without that its working , but for production npm install --production save around 200MB

the issue happens only with swagger-ui-express package

**Comment by scottie1984** [comment]
npm install —production just installs the dependencies only. It will have nonimpact on this module install. 

Perhaps you need to review your package-lock.json file?

Can you check in the output docker container if swagger-ui-express is in the node_modules?

**Comment by johnico** [comment]
@scottie1984 
thanks, 

... if swagger-ui-express is in the node_modules?  **YES it is**
also tried to remove and reinstall package-lock

this is from pacakge-lock.json 

```
    "swagger-ui-dist": {
      "version": "3.25.0",
      "resolved": "https://registry.npmjs.org/swagger-ui-dist/-/swagger-ui-dist-3.25.0.tgz",
      "integrity": "sha512-vwvJPPbdooTvDwLGzjIXinOXizDJJ6U1hxnJL3y6U3aL1d2MSXDmKg2139XaLBhsVZdnQJV2bOkX4reB+RXamg=="
    },
    "swagger-ui-express": {
      "version": "4.1.4",
      "resolved": "http://nexus.uveye.xyz:8080/repository/npm/swagger-ui-express/-/swagger-ui-express-4.1.4.tgz",
      "integrity": "sha512-Ea96ecpC+Iq9GUqkeD/LFR32xSs8gYqmTW1gXCuKg81c26WV6ZC2FsBSPVExQP6WkyUuz5HEiR0sEv/HCC343g==",
      "requires": {
        "swagger-ui-dist": "^3.18.1"
      }
    },
```


what in the build cause the package damage or  to "disappear"

**Comment by scottie1984** [comment]
the only thing I can think of is to analyse your docker container to see if you can see any clues to where the node_modules have gone / are installed.

**Comment by yuriburk** [comment]
Any solution?
