### ISSUE TITLE
SwaggerUIBundle is not defined with webpack build

### ISSUE THREAD

**Issue by ahmednkhan24** [scottie1984/swagger-ui-express#176]
I am creating a Node.js Express API found [here](https://github.com/ahmednkhan24/Tracker-Api).

I am trying to incorporate swagger-ui-express into my application. I am able to successfully load the localhost:5000/api-docs page when running locally.
I am using webpack to create a "production" build. When I create the bundle and try to run it locally, I can not access the localhost:5000/api-docs page anymore.

This is the error that is seen in the console: 

```
Uncaught SyntaxError: Unexpected token ':'
swagger-ui-standalone-preset.js:1 Uncaught SyntaxError: Unexpected token ':'
swagger-ui-init.js:140 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (swagger-ui-init.js:140)
```

[This](https://github.com/ahmednkhan24/Tracker-Api/blob/master/src/routes/index.js) is where I am serving swagger-ui-express.
And [this](https://github.com/ahmednkhan24/Tracker-Api/blob/master/src/swagger/swaggerLocal.json) is where I am defining the swagger.json file.

**Comment by scottie1984** [comment]
For webpack try the following https://github.com/scottie1984/swagger-ui-express/issues/90#issuecomment-516944437

I will add to the readme if it works for you.

**Comment by ahmednkhan24** [comment]
I tried that, but it didn't work. [This](https://github.com/scottie1984/swagger-ui-express/issues/114#issuecomment-566022730) solution is what's working for me.

**Comment by NoodleOfDeath** [comment]
how is this considered completed? the work around is like a hack... can this library be rewritten to work for production environments?

**Comment by manel00** [comment]
It literally happens to me the same, and still its not working, there is no workaround? How can it be possible?
