### ISSUE TITLE
Display security requirements in swagger-ui

### ISSUE THREAD

**Issue by MengRS** [scottie1984/swagger-ui-express#179]
Hello,

Is there any way to display the security requirements in swagger ui?  I know that you can click on `authorize` and that will display the security requirements.  However, is there a way that we can show the security requirements without having to click the `authorize` button (ideally underneath the `Extensions` section)?

**Comment by scottie1984** [comment]
This issue are specific to swagger-ui (https://github.com/swagger-api/swagger-ui). Please raise them with swagger-ui directly.

This module is a wrapper for swagger-ui for express
