### ISSUE TITLE
Adding functions to handle API response in client?

### ISSUE THREAD

**Issue by HoukasaurusRex** [scottie1984/swagger-ui-express#180]
Currently, I'm searching for a way to add a function to save a token sent in the body of a response from my login API to localStorage, however I'm unable to find a simple way to do this. I would like a way to "intercept" a response after it is returned from the API and displayed in the UI, as that would be easy enough to perform some kind of action with the result (i.e. saving a token to localStorage or setting the `ui.preauthorizeApiKey('bearerAuth', token)`)

Is there currently a way to do this?

**Comment by crazyx13th** [comment]
ugly workaround
```javascript
swaggerOptions: {
	authToken: authToken,
	requestInterceptor: (request) =>
	{
		request.headers.Authorization = `Bearer ${window.ui.getConfigs().authToken}`
		return request
	}
},

```

**Comment by scottie1984** [comment]
The workaround is the only option I am aware of.

If you would like to pick it up further then the issue is specific to swagger-ui (https://github.com/swagger-api/swagger-ui). Please raise them with swagger-ui directly.

This module is a wrapper for swagger-ui for express
