### ISSUE TITLE
How to set preauthorize for bearer or apiKey authentication?

### ISSUE THREAD

**Issue by HailoMYM** [scottie1984/swagger-ui-express#181]
Is there some way to set a preauthorize config so users can test api without typing the token everytime they access to docs?

Could someone provide an example?

**Comment by Pra3t0r5** [comment]
+1
I have the same question. I'm using this:
```
components: {
    securitySchemes: {
      basic: {
        type: "http",
        scheme: "basic"
      },
      bearerAuth: {
        description: "JWT Authorization",
        type: "http",
        scheme: "bearer",
        in: "header",
        bearerFormat: "JWT"
      },
      ApiKeyAuth:{
        type: "apiKey",
        in: "header",
        name: "token"
      }
    }
  },
  security: {
    basicAuth: [],
    apiKey: []
  },
```
As OAs3 specifies to set global auths and the UI Authorize dialog still empty

**Comment by venkateshgbabu** [comment]
Doesn't look like this is supported or could be a bug.

**Comment by scottie1984** [comment]
The only related issue is:

https://github.com/scottie1984/swagger-ui-express/issues/180

Which may be of help. Otherwise raise with the swagger ui (https://github.com/swagger-api/swagger-ui) team.

Closing for now as this has been open for a while - please reopen if needed

**Comment by wolfieorama** [comment]
> 

try adding `openapi: '3.0.0',` in the swaggerDefinition
