### ISSUE TITLE
Changing Logo with CSS doesn't work

### ISSUE THREAD

**Issue by stoicAlchemist** [scottie1984/swagger-ui-express#184]
Adding the Css into the correct element doesn't change the logo.

To reproduce this, pass down options for:
  .topbar-wrapper img {
      content: url(customLogo.png);
    }
The Swagger logo will remain, if you use Developer Tools to delete the SRC property from the IMG tag, then you can see your logo.

Could this be related to the way the CSS is passed or is it at all possible with this library?

**Comment by tmtron** [comment]
replacing an image via css is not so easy - this worked for me: https://stackoverflow.com/a/19114098/1041641
