### ISSUE TITLE
render swagger page inside default handlbars layout page

### ISSUE THREAD

**Issue by jhylton** [scottie1984/swagger-ui-express#186]
Hello,

I have a standard menu bar and side menu bar for my current site. I would like to be able to use my current sites layout and have swagger rendered inside my "main" div so all other navigation options are still available to the end user when viewing the api-docs page. is this a possibility?

basically i would like this rendered within the mainV3 layout page:

```javascript
app.set('trust proxy', 1);
app.set('view engine', 'hbs');
app.set('views', path.join(__dirname, 'views'));
app.engine('hbs', hbs({
  extname: 'hbs',
  defaultLayout: 'mainV3',
  layoutDir: path.join(__dirname + '/views/layouts'),
  partialsDir: path.join(__dirname + '/views/partials')
}));
```

thanks!

**Comment by franciscohanna92** [comment]
I think that the best you can do at the moment is to use an iframe
