### ISSUE TITLE
basePath not working

### ISSUE THREAD

**Issue by varmeh** [scottie1984/swagger-ui-express#189]
Issue: basePath not working.

Used with `swagger-jsdoc`.

configuration used:

```
    const swaggerDefinition = {
		openapi: '3.0.3',
		info: {
			title: 'Stockal API',
			version: '1.0.0'
		},
		basePath: '/api'
	}

	const swaggerOptions = {
		swaggerDefinition,
		apis: ['**/*.routes.js']
	}
```

Instead of making calls to `http://localhost:3000/api/home`, calls are redirected to `http://localhost:3000/home`.

Swagger.json generated by jsdoc:
```
{
  "openapi": "3.0.3",
  "info": {
    "title": "API",
    "version": "1.0.0",
    "contact": {
      "name": "Support",
      "email": "test@test.com"
    }
  },
  "basePath": "/api",
  "paths": {
    "/home": {
      "get": {
        "description": "Home message",
        "produces": "application/json",
        "responses": {
          "200": {
            "description": "message",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    }
  },
  "components": {},
  "tags": []
}
```

Please help.

**Comment by mgagliardo91** [comment]
I am also having this issue, can you please comment a solution. For me, I have all my routes served at `/v1` but I would like to avoid having to write `/v1` for each jsdoc route.

**Comment by scottie1984** [comment]
Please review this #228 and let me know if it fixes.

**Comment by JoffrayBillon** [comment]
It's not !

**Comment by JoffrayBillon** [comment]
Update: [openapi 3 replaced the basePath attribute](https://swagger.io/docs/specification/api-host-and-base-path/) there is nothing to fix in swagger-ui here (or maybe yes) but the fix of this issue is elsewhere.

Considere 2 solution:
- 1: change `openapi: '3.0.3'` to `swagger: '2.0'`
- 2: change `basePath: '/api'` to `servers: [{ url: '/api' }]`

Take the one you prefer but let me tell you the actual swagger-jsdoc is all made with for swagger: "2.0" for some reason they changed the version name without taking care of adapting the doc for openapi: '3.0.3'.
That mean keep openapi: '3.0.3' mean to do some more changes that are actually not documented.

**Comment by iwankruger** [comment]
@JoffrayBillon thanks 
Changing ` basePath: '/api'` to `servers: [{ url: '/api' }]` worked for me

**Comment by abdulloooh** [comment]
handling it on servers array works well
```
 "servers": [
      {
          "url": "http://localhost:4000/api",
          "description": "Development server"
      },
      {
          "url": "https://app.com/api",
          "description": "Production server"
      }
  ],
```

**Comment by buuhvprojects** [comment]
> * 1: change `openapi: '3.0.3'` to `swagger: '2.0'`

worked for me

**Comment by guilbep** [comment]
I'm using feathersJs v5 (https://feathersjs.com/guides/) with feathers-swagger (https://github.com/feathersjs-ecosystem/feathers-swagger). and having specs: {servers: [{'url': '/api'}]} worked for me :)

Thanks!!


```ts
 app.configure(
  swagger({
    ui: swagger.swaggerUI({ getSwaggerInitializerScript }),
    specs: {
      servers: [{ url: '/api' }],
      info: { 
        title: 'http rest api',
        description: ' swagger documentation',
        version: '1.0.0'
      },
      components: {
        securitySchemes: {
          BearerAuth: {
            type: 'http',
            scheme: 'bearer'
          }
        }
      },
      security: [{ BearerAuth: [] }]
    }
  })
)
```
