### ISSUE TITLE
swagger.json link not available with spec object

### ISSUE THREAD

**Issue by jbaris** [scottie1984/swagger-ui-express#194]
AFAIK there are (at least) two ways to setup swagger-ui-express:
- providing the swagger.json file url

      var options = {
         swaggerOptions: {
            url: 'http://petstore.swagger.io/v2/swagger.json'
         }
      }
      app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(null, options));

- providing a spec object

      const swaggerSpec = swaggerJSDoc(options);
      app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));

The first alternative shows a swagger.json link to access/download the file.
![image](https://user-images.githubusercontent.com/819587/84143053-44eeb900-aa2c-11ea-8594-0ebe7f598e41.png)

The second one not.
Allow access to this file is important to import it in another tools compatible with OpenAPI3.
We had to implement a workaround to achieve this, but it would be nice to get this feature out-of-box.

Thanks!

**Comment by AlbertoLopSie** [comment]
Hi Juan ,

Could you share your 'workaround' ?

Gracias!!

**Comment by jbaris** [comment]
@AlbertoLopSie sure:

**index.js:**
```
  const swaggerUi = require('swagger-ui-express')
  const swaggerOptions = require('./utils/swagger-opts')
  const swaggerController = (req, res) => {
    const protocol = req.headers['x-forwarded-proto'] || req.protocol
    const host = req.headers['x-forwarded-host'] || req.get('host')
    const urlBase = protocol + '://' + host
    const setup = swaggerUi.setup(null, swaggerOptions(urlBase))
    setup(req, res)
  }
  app.use('/swagger.json', express.static('./swagger.json'))
  app.use('/api-docs', swaggerUi.serve, swaggerController)
```
**swagger-opts.js:**
```
module.exports = (urlBase) => ({
  swaggerOptions: {
    defaultModelsExpandDepth: -1,
    url: urlBase + '/swagger.json'
  }
})
```
**package.json**:
```
"scripts": {
  "start": "node ./node_modules/swagger-jsdoc/bin/swagger-jsdoc.js -d src/utils/swagger-def.js && node src/index.js",
}
```

Credits go for  @ortizman too.

**Comment by AlbertoLopSie** [comment]
Hi Juan, Thanks for your reply!

Let me understand...

**index.js:**
```
app.use('/swagger.json', express.static('./swagger.json'))
```

Are you serving a static `swagger.json` ?  Mine is built merging a static one with a `swaggerSpec` generated with `swagger-jsdoc` ran on startup, that's why I'm using `swaggerUi.setup(swaggerSpec));`


**package.json:**
```
"scripts": {
  "start": "node ./node_modules/swagger-jsdoc/bin/swagger-jsdoc.js -d src/utils/swagger-def.js && node src/index.js",
}
```

Where do you get `src/utils/swagger-def.js` from ?

My **app.js**:
```
var apidef = yaml.load( './api/my-api-swagger.yaml' );

const options = {
    definition: apidef,

    // Path to the API docs
    apis: ['./routes/*.js', './controllers/jsdoc/*.js', './controllers/V1/*.js' ],
};

// Initialize swagger-jsdoc -> returns validated swagger spec in json format
const swaggerSpec = swaggerJSDoc(options);  


var swOpts = {
  explorer: true
};

app.use( '/docs', swaggerUi.serve, swaggerUi.setup( swaggerSpec, swOpts ) );

```

**Comment by beaclnd92** [comment]
My workaround:
```javascript
const specs = swaggerJsdoc(options);

app.use("/apiDocs", swaggerUI.serve);
app.get("/apiDocs", swaggerUI.setup(null, {
    swaggerOptions: {
        url: "/apiDocs/swagger.json",
    },
}));
app.get("/apiDocs/swagger.json", (req, res) => res.json(specs));
```

**Comment by scottie1984** [comment]
The workaround suggested by @beaclnd92 would be my recommended solution. I will update the docs

**Comment by sacummings91** [comment]
This example does not work. With this code: 

```
const options = {
    swaggerOptions: { url: "/docs/oas3.json" },
  };

  router.use("/docs", swaggerUI.serve);
  router.use("/docs", swaggerUI.setup(undefined, options));
  router.get("/docs/oas3.json", (_, response) => response.json(openAPISpec));
  ```
  
  I get this error:
  
![image](https://user-images.githubusercontent.com/29286028/227279660-c61a6b1e-34de-4f3e-942c-5f1a57a808c9.png)

I'm assuming it's because I'm not actually passing the spec to `setup`.

**Comment by scottie1984** [comment]
The url must be the public url of the spec file. Based on your screenshot I guess it should be /api/docs/oas3.json
