### ISSUE TITLE
customCssUrl is not working in swagger-ui-express

### ISSUE THREAD

**Issue by anandkrishna93** [scottie1984/swagger-ui-express#195]
Hi Team,

I have give correct CSS file URL , but error is coming is coming. and favIcon also not coming.
Please help

const uiOpts = {
    explorer: false,
    customSiteTitle: "Master Data",
    customfavIcon: "./favicon.ico",
    customCssUrl: './custom.css'
};

Error: **Resource interpreted as Stylesheet but transferred with MIME type text/html**: "http://localhost:8181/masterApi/api-docs/custom.css".

**Comment by rahul-sc** [comment]
Seeing the same issue on my side too

**Comment by scottie1984** [comment]
Are you serving the custom.css and favicon.ico out via express? Can you view the files in the browser if you go directly to them?

If not then you will need some code to ensure that you are serving the icon and css - this module does not take care of that for you. I will close this - please open if needed.
