### ISSUE TITLE
Request duration is not showing when API respond with 400 status code

### ISSUE THREAD

**Issue by turivishal** [scottie1984/swagger-ui-express#199]
### Q&A
 - OS: Windows 10 Pro
 - Browser: chrome
 - Version: 83.0.4103.97 (Official Build) (64-bit)
 - Method of installation: npm
 - Swagger-UI Express: ^4.1.4
 - Swagger-UI version: 3.18.3
 - Swagger/OpenAPI version: 3.0.1

### Content & configuration
I have an issue related request duration parameter `displayRequestDuration: true`, its showing request duration perfectly when API respond with 200 status code but if API respond with other status code like 400, 409 its not showing Request duration.

### Status Code 200
![image](https://user-images.githubusercontent.com/10988772/85171853-6ef67580-b28d-11ea-9466-cca76b35095b.png)

### Status Code 400
![image](https://user-images.githubusercontent.com/10988772/85171744-36ef3280-b28d-11ea-9e24-72b71f275ac0.png)

**Comment by scottie1984** [comment]
This issue is specific to swagger-ui (https://github.com/swagger-api/swagger-ui). Please raise them with swagger-ui directly.

This module is a wrapper for swagger-ui for express
