### ISSUE TITLE
Default URL is http://petstore.swagger.io

### ISSUE THREAD

**Issue by abnoba12** [scottie1984/swagger-ui-express#2]
When I run this module it works great with the swagger UI coming up, but the default location it tries to test against is http://petstore.swagger.io. By digging into your module I see you can add a ?url= parameter to the path to make it use whatever path you would like. This has proven to be a big pain for me to do with express. 

I have tried to make a redirect rule that will redirect back to the same page it if is missing the ?url parameter and then appending ?url=http%3A%2F%2Flocalhost%3A9090%2F. This is breaking things for swagger when i do that. 

Could you change it to default to something like "window.location.origin" and use the ?url= parameter if you want it something custom?

**Comment by scottie1984** [comment]
What are you trying to achieve? You should pass your swagger document into the setup function:

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));

This will tie the swaggerUi to your swagger document. The Explore option I can remove as its not intended to be used.

The intention of the module is to tie your swagger doc to the UI in the setup function. I am happy to make changes and serve other purposes if you have another use case.

**Comment by abnoba12** [comment]
Short Answer: Removing the explorer would be perfect for what I need.

Long Answer: I originally wasn't aware of the "host" and "basePath" parameters. In the example configurations for the swagger-jsdoc module there is no reference to them. When the "host" and "basePath" parameters are left blank the swagger UI defaults to using  http://petstore.swagger.io for the host.

So can you please remove the explorer from your module and add mention the "host" and "basePath" parameters in your documentation.

**Comment by scottie1984** [comment]
Ah, that makes sense now as to why you wanted the url to default to "window.location.origin". I wasn't aware that if you left host and basePath parameters blank it caused this.

I will fix it over the weekend to default to "window.location.origin". I will also remove the explorer.

**Comment by scottie1984** [comment]
I set the default url to window.location.origin and removed the explorer by default.

Can you test and let me know if this fixes it for you?

**Comment by abnoba12** [comment]
This worked perfect for me
