### ISSUE TITLE
Randomly I get blank page

### ISSUE THREAD

**Issue by edoardomistretta** [scottie1984/swagger-ui-express#201]
I randomly get a blank page. The `<div id="swagger-ui">` not always is filled in.
![Screenshot 2020-07-11 at 11 44 40](https://user-images.githubusercontent.com/38187989/87221465-7da3ea00-c36c-11ea-8a12-cf6982fc6362.png)

![Screenshot 2020-07-11 at 11 45 37](https://user-images.githubusercontent.com/38187989/87221466-7ed51700-c36c-11ea-84b1-f05dae64e37e.png)

You can try here refreshing the page and clearing the cache:
- that's my repo: [https://github.com/edoardomistretta/art-rest-api](https://github.com/edoardomistretta/art-rest-api)
- deployed with serverless
I use latest version of `"swagger-ui-express": "^4.1.4"`

**Comment by sjinks** [comment]
Same here. As far as I can tell, the issue is that `swagger-ui-init.js` for some reason has 0 bytes.

For the URL above:

```
content-type: application/javascript; charset=utf-8
content-length: 0
date: Sat, 11 Jul 2020 19:30:43 GMT
x-amzn-requestid: 4821c315-0233-4f52-a2b4-98ad37d7ad0c
x-dns-prefetch-control: off
x-xss-protection: 1; mode=block
strict-transport-security: max-age=15552000; includeSubDomains
x-frame-options: SAMEORIGIN
x-amzn-remapped-content-length: 0
x-download-options: noopen
x-amz-apigw-id: Phf3fHvzoAMFScA=
x-content-type-options: nosniff
etag: W/"0-2jmj7l5rSw0yVb/vlWAYkK/YBwk"
x-amzn-trace-id: Root=1-5f0a1363-66bc63147cc3505097b1c04c;Sampled=0
x-cache: Miss from cloudfront
via: 1.1 7c17b3af9cda4d5f0ff45961b7be9fdc.cloudfront.net (CloudFront)
x-amz-cf-pop: VIE50-C1
x-amz-cf-id: lGluQJBGZ-TOFIY4_hUCKlpoFHhb0IT_20WYyPoazpmTyKU_jsI9Ug==
X-Firefox-Spdy: h2
```

**Comment by sjinks** [comment]
Could be a duplicate of #178

**Comment by scottie1984** [comment]
Please review this #228 and let me know if it fixes.

**Comment by edoardomistretta** [comment]
Hi @scottie1984! First of all, sorry for the delay.
I think it's fixed, thank you
