### ISSUE TITLE
Serves example on /index.html

### ISSUE THREAD

**Issue by infodusha** [scottie1984/swagger-ui-express#202]
When i go to `/docs/` i see my swagger & when i go to `/docs/index.html` i see example swagger (petstore). Can you remove this?

**Comment by uncleramsay** [comment]
This is also a problem for me - extremely confusing when a random API shows up in our application that we have nothing to do with!

Please could the example be removed from the distributables?

**Comment by scottie1984** [comment]
Unfortunately I can't remove the demo index.html as it comes from another library without forking that project to remove it - which seems like an excessive solution at the moment. 

I suggest placing a redirect before creating the swagger routes:

```js
app.use('/api-docs/index.html', (req, res) => res.redirect(301, '/api-docs'))
```

**Comment by infodusha** [comment]
Maybe we should open issue at the repo where is the problem?

**Comment by scottie1984** [comment]
I don't think they will do anything as their side as the use case their side is different from this module.

 The swagger-ui-dist module has the Swagger distribution which we serve out as static content (including the index.html). We then send out custom html on the route.

Other than forking swagger-ui-dist to remove the index.html I am not sure what other options would work.

@shockey any thoughts?
