### ISSUE TITLE
Spinning Wheel icon when clicking on route

### ISSUE THREAD

**Issue by jwhitehead77** [scottie1984/swagger-ui-express#203]
Please help...

I have tried a number of different options based on what I have read in regards to swagger-jsdoc and swagger-ui and swagger-ui-express and cannot get this to work. I have done everything exactly the way the swagger-jsdoc and swager-ui-express documentation says and when I go to the /api-docs and click on a route I just get a spinning wheel and nothing renders in the color boxes. The name of my schema object appears but when I expand it there are no properties even though I have clearly defined them in the jsdoc comments. My openapi 3 spec is valid and renders to the browser or in Postman just fine (generated by swagger-jsdoc using jsdoc comments on routes).

I have attached my very small sample project and a screenshot of what is happening.
[package.zip](https://github.com/scottie1984/swagger-ui-express/files/4968369/package.zip)
![openapi-issue](https://user-images.githubusercontent.com/66504934/88331187-2d287700-ccf2-11ea-9932-37a7d75c311a.PNG)

**Comment by jagannathsrs** [comment]
Downgrade to 3.30.0

**Comment by meowlanguages** [comment]
Here is the main issue https://github.com/swagger-api/swagger-ui/issues/6249#issuecomment-662705110

**Comment by meowlanguages** [comment]
> 3.30.0

I think that the problem exists in swagger-ui-express because of the swagger module bug. And we can downgrade to version 3.30.0, because swagger-ui-express doesnt have this version.

**Comment by meowlanguages** [comment]
1. delete swagger-ui-express
2. npm i swagger-ui-express 
3. profit
