### ISSUE TITLE
Text overflow in Model description 

### ISSUE THREAD

**Issue by jagannathsrs** [scottie1984/swagger-ui-express#204]
When a description for an API property is long, it overflows out of the div. 

```
@IsNotEmpty()
  @ApiProperty({ example: integrations.MySQL, description: `Accepted values: ${integrationValues}`})
  @IsString()
  @IsEnum(integrations, {message: `Can be of type`+ integrationValues})
  dbType: integrations;
```

![image](https://user-images.githubusercontent.com/26180818/88568621-42a9e380-d007-11ea-86c4-1d44c8211f28.png)

Fix:

Add the follwing in custom css:

`.swagger-ui .renderedMarkdown p {
  word-break: break-all;
}`

**Comment by scottie1984** [comment]
This issue is specific to swagger-ui (https://github.com/swagger-api/swagger-ui). Please raise them with swagger-ui directly.

This module is a wrapper for swagger-ui for express
