### ISSUE TITLE
Swagger UI css looks broken

### ISSUE THREAD

**Issue by egonz077** [scottie1984/swagger-ui-express#209]
I have the Swagger UI loading and it seems like the CSS files are loading but the UI looks broken or missing CSS. Any help is appreciated.

<img width="2194" alt="Screen Shot 2020-08-06 at 1 12 36 PM" src="https://user-images.githubusercontent.com/14057962/89561563-ab9f1180-d7e6-11ea-8dc9-35f4cceb9764.png">

**Comment by scottie1984** [comment]
Did you manage to solve this? Most likely the CSS is not valid - perhaps try out the example CSS first?

I will close this for not - please reopen if needed
