### ISSUE TITLE
Update swagger-ui dependencie to 3.0.19 

### ISSUE THREAD

**Issue by PhilippeChab** [scottie1984/swagger-ui-express#21]
Hi! 

The tagsSorter option just came back in swagger-ui 3.0.19 (it was previously apisSorter and was not working). It would be awesome to have access to it as quickly as possible. 

Thank you.

**Comment by scottie1984** [comment]
Just updated, can you check it out?

**Comment by PhilippeChab** [comment]
It's working perfectly!

Thank you very much for the quick feedback!
