### ISSUE TITLE
Support Reverse Proxy

### ISSUE THREAD

**Issue by cawoodm** [scottie1984/swagger-ui-express#210]
We're using `swagger-ui-express` and `swagger-jsdoc` to serve a swagger UI for our API so I'm [double posting](https://github.com/Surnet/swagger-jsdoc/issues/207) this because I'm not sure where the problem lies.

---

Many applications run behind a reverse proxy. So while an application runs on `localhost:8080` and swagger uses `/api/` this may be completely different when someone opens the app externally e,g, `https://somedomain.com/foo/bar/api`.

In such situations the swagger UI loads but all attempt to run methods fail because they send the request to the app's root `/` instead of the external root `/foo/bar`.

There is no way to solve this currently since the app does not and should not know how it will be called externally: 

```
// There is no way to know when the app starts, which external URLs will call it
app.use('/', swaggerUi.serve);
app.get('/', swaggerUi.setup(swaggerJsDoc));
```

Changing basePath is not an option because, even if it were known when the app starts, this would mean swagger-ui would only work externally on that basePath and not when called via localhost:8080/api/.

Using  `./method/` in the jsdoc comments doesn't help either. It generates totally incorrect links:

```
/** @swagger
 *  './method/{id}':
```
Generates `http://localhost:8080./method/123` => invalid URL.

Using  `method/` in the jsdoc comments doesn't help either. It generates totally incorrect links:

```
/** @swagger
 *  'method/{id}':
```
Generates `http://localhost:8080method/123` => invalid URL.

**Comment by yinzara** [comment]
You need to set basePath based on some environment variable you make available in your deployed application.

Locally you would not set basePath (or set it to some http://localhost:8080).

**Comment by scottie1984** [comment]
The only possible option would be to use some custom JS on the client to use the hostname as a way to set up swagger correctly.

https://www.npmjs.com/package/swagger-ui-express#custom-js

Other than that you would have to set the basePath correctly.

**Comment by scottie1984** [comment]
Closing for now - happy to add to the docs if someone wants to create a PR
