### ISSUE TITLE
Swagger trying to get content via https on non ssl express server

### ISSUE THREAD

**Issue by n0n3br** [scottie1984/swagger-ui-express#212]
I've configured a no ssl server on my machine and swagger works fine.

When I deploy the application to the productions server (debian 9), everytime I try to access the documentation route it tries to fetch resoursce files (swagger-ui.css for example) via https. Since there's no https server configured, it never loads the page.

Is there someway to force using only http ?

**Comment by nartc** [comment]
@n0n3br How did you resolve this?

**Comment by n0n3br** [comment]
Unfortunately no.

**Comment by taipoxin** [comment]
@n0n3br 
In my case I just needed to remove `helmet` express extension from my setup and everything goes normally. I think for swagger it should be configured manually or be removed.

**Comment by thomasgauvin** [comment]
Removing helmet did not work for me

**Comment by meSmashsta** [comment]
Guys no need to remove `helmet`, just move the swagger above the `helmet` registration like so:

```javascript
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('../swagger.json');
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

app.use(helmet());
```

**Comment by haidaqn** [comment]
> Removing helmet did not work for me

Me too, have you fixed it yet?

**Comment by samuliasmala** [comment]
> Guys no need to remove `helmet`, just move the swagger above the `helmet` registration like so:


The issue is likely caused by the [Upgrade-Insecure-Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade-Insecure-Requests) CSP header, so other option is to disable that from `helmet`:

```ts
app.use(
  helmet({
    contentSecurityPolicy: { directives: { upgradeInsecureRequests: null } },
  }),
);
```

**Comment by minhsu12113** [comment]
> contentSecurityPolicy: { directives: { upgradeInsecureRequests: null } },

Thanks @samuliasmala this work for me

```app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors({ origin: false }));


app.use(helmet({ contentSecurityPolicy: { directives: { upgradeInsecureRequests: null } }, }));
app.use(rateLimiter);


// Request logging
app.use(requestLogger);

// Routes
app.use("/health-check", healthCheckRouter);
app.use("/users", userRouter);


// Swagger UI
app.use(openAPIRouter);

// Error handlers
app.use(errorHandler());

export { app, logger };
