### ISSUE TITLE
Swagger UI doesn't respond for large response data

### ISSUE THREAD

**Issue by bsarchana** [scottie1984/swagger-ui-express#213]
I have an API which sends over 21MB or more as response. But swagger UI doesn't respond. The browser hangs.  Tested the same API through Postman and it doesn't have any issues.
![image](https://user-images.githubusercontent.com/34731146/91041861-63794f00-e62e-11ea-9572-374f1d5688ed.png)

![image](https://user-images.githubusercontent.com/34731146/91041558-e6e67080-e62d-11ea-836d-f7709ac0299c.png)

**Comment by scottie1984** [comment]
This issue are specific to swagger-ui (https://github.com/swagger-api/swagger-ui). Please raise them with swagger-ui directly.

This module is a wrapper for swagger-ui for express
