### ISSUE TITLE
Change Swagger UI logo to custom logo

### ISSUE THREAD

**Issue by leemerlas** [scottie1984/swagger-ui-express#216]
So I want to change the Swagger UI logo in the navbar to a custom one

![image](https://user-images.githubusercontent.com/31193012/91535271-79945180-e945-11ea-8434-8987eeea192b.png)

Is this possible to do? I tried directly manipulating the HTML by using custom.js and getElementsByClassName and appending a simple paragraph but it just throws an error

![image](https://user-images.githubusercontent.com/31193012/91535574-f0314f00-e945-11ea-9633-b94000ad2710.png)

Is this possible?

**Comment by tmtron** [comment]
see #184

**Comment by scottie1984** [comment]
Add the moment the only way to change the logo would be customJs and customCss as posted above
