### ISSUE TITLE
 "Cannot read property 'getScrollToKey' of undefined" when displaying the model of a request

### ISSUE THREAD

**Issue by Kenan13** [scottie1984/swagger-ui-express#217]
Hi. 
This issue was also in swagger-ui, but has been solved 2 weeks ago. 

https://github.com/swagger-api/swagger-ui/issues/6305

the same issue exists in swagger-ui-express.
Is there a possible fix for that?

Thanks in advance!

**Comment by scottie1984** [comment]
If you remove swagger-ui-express and swagger-ui-dist and reinstall you should get the latest version that is fixed.
