### ISSUE TITLE
Swagger ui loads inconsistently 

### ISSUE THREAD

**Issue by israkhan** [scottie1984/swagger-ui-express#218]
```
const swaggerJsDoc = require("swagger-jsdoc");
const swaggerUI = require("swagger-ui-express");
const swaggerOptions = require("./swagger.json");

const swaggerDocs = swaggerJsDoc(swaggerOptions);
app.use("/api-docs", swaggerUI.serve, swaggerUI.setup(swaggerDocs));
```

When I start my server and go to appropriate route, it loads inconsistently. Most times i'm getting a 304 but sometimes the page will load successfully with a 200.

```
>  GET /app/api-docs/ 304 0.686 ms - -
i  functions: Finished "app" in ~1s
i  functions: Beginning execution of "app"
i  functions: Beginning execution of "app"
i  functions: Beginning execution of "app"
i  functions: Beginning execution of "app"
>  GET /app/api-docs/swagger-ui.css 304 0.769 ms - -
i  functions: Finished "app" in ~1s
>  GET /app/api-docs/swagger-ui-standalone-preset.js 304 0.933 ms - -
i  functions: Finished "app" in ~1s
>  GET /app/api-docs/swagger-ui-init.js 304 0.523 ms - -
i  functions: Finished "app" in ~1s
>  GET /app/api-docs/swagger-ui-bundle.js 304 1.134 ms - -
i  functions: Finished "app" in ~1s
i  functions: Beginning execution of "app"
i  functions: Finished "app" in ~1s
>  GET /app/api-docs/favicon-32x32.png 200 0.724 ms - 628
i  functions: Beginning execution of "app"
>  GET /app/api-docs/ 304 0.657 ms - -
i  functions: Finished "app" in ~1s
i  functions: Beginning execution of "app"
i  functions: Beginning execution of "app"
i  functions: Beginning execution of "app"
>  GET /app/api-docs/swagger-ui.css 304 0.759 ms - -
i  functions: Finished "app" in ~1s
>  GET /app/api-docs/swagger-ui-standalone-preset.js 304 0.998 ms - -
>  GET /app/api-docs/swagger-ui-bundle.js 304 0.889 ms - -
i  functions: Finished "app" in ~1s
i  functions: Finished "app" in ~1s
i  functions: Beginning execution of "app"
>  GET /app/api-docs/swagger-ui-init.js 200 0.529 ms - 1794
i  functions: Finished "app" in ~1s
i  functions: Beginning execution of "app"
>  GET /app/api-docs/favicon-32x32.png 200 0.590 ms - 628
```

I've removed my actual api route which is tied to a Firebase Cloud Function for security concerns and replaced with app.

**Comment by mthomas-io** [comment]
I have the same issue, exact same setup.

**Comment by charlescapps** [comment]
We're seeing this same issue. I can't figure out the pattern, but it's possibly worse right after a deploy. It's annoying, because when we give someone a link to our Swagger UI, they often think it's broken and requires several page reloads before it works! We're initializing Swagger UI exactly as in the README.

**Comment by HugoGresse** [comment]
I've spens two hours debugging this until I've found the issue. Can confirm the 4.1.3 works well. 
In my case, I think the issue was from `swagger-ui-init.js` loading with a content-length = 0 (and no data), but still the server responded with a 200 ok. But when calling the url directly, the .js file was loading...

**Comment by markusahlstrand** [comment]
Think I found the issue for this. Looks like a race condition between the root path and the swagger-ui-init path. If the root path isn't executed before the swagger-ui-path the setup function 

I'm running swagger-ui-express on lamda and the generateHTML function isn't called and the swaggerInitFile (https://github.com/scottie1984/swagger-ui-express/blob/master/index.js#210) is never initialised. 

I'm running an expressed wrapped in serverless-offline, which locally spawns a new process on every call, so in this case it happens every time. 

A very ugly workaround for this is to force initialise the init file by faking a call to the root path:
```
// HACK: workaround to ensure that the ui-init file is initialized.
let initialized;
app.use((req, res, next) => {
  if (!initialized) {
    swaggerUi.setup(null, options)(req, { send: () => {} });
    initialized = true;
  }

  next();
});

app.use(swaggerUi.serve, swaggerUi.setup(null, options));
```

Not sure how easy this will be to fix without a breaking change as serve currently doesn't have access to the options object. I could make a PR with an suggestion if there's interest.

**Comment by scottie1984** [comment]
Please review this https://github.com/scottie1984/swagger-ui-express/pull/228 and let me know if it fixes.

**Comment by markusahlstrand** [comment]
It looks like it should work just fine. Thanks!

**Comment by jimlindeman** [comment]
Yes, when one runs >1 kubernetes pod of an application using this library, its possible for one pod to get the call to setup, while another pod gets the call to fetch /swagger-ui-init.js, causing it to return the 0 length empty string.  While waiting for this fix in this PR, the workaround for the blank swaggerInit I'm using is to directly invoke the generateHTML(apiDoc) right after registering the setup method with the express.

**Comment by scottie1984** [comment]
I reverted the code that was causing this issue. Hopefully this is no longer an issue on the latest version.

Will close for now - please reopen if needed

**Comment by nacholorema** [comment]
@scottie1984 I've been having the same issue as @markusahlstrand and suspect the issue is the same as described in his comment. 
I am using the latest version at the moment (5.0.1), using serverless and serverless-offline also.

When using the code of [#228]( https://github.com/scottie1984/swagger-ui-express/pull/228) the issue is solved.
