### ISSUE TITLE
Vesioning set with request header

### ISSUE THREAD

**Issue by daveKoala** [scottie1984/swagger-ui-express#221]
I have APIs with version used defined in the request header. E.g:
```{accept-version: v1}```

There is no obvious solution to this. Current set up works but does not make sense. Is there a better way? Or a way to change the doc header text to "Select a version" from "Select a definition"?

The code example below. Requires every new API version have a url that returns a complete swagger doc.

```
apiDocsRouter.use('/', swaggerUI.serve, (req: Request, res: Response, next: NextFunction) => {
  try {
    const options: swaggerUI.SwaggerOptions = {
      explorer: true,
      customSiteTitle: "cohort-api",
      swaggerOptions: {
        urls: [
          {
            url: `${baseURL}/api-docs/apple`,
            name: 'Apple',
          },
          {
            url: `${baseURL}/api-docs/banana`
            name: 'Banana',
          },
        ],
      },
    };
    // @ts-ignore
    return swaggerUI.setup(null, options)(req, res, next);
  } catch (error) {
    next(error);
  }
});
```

I've also tried using ```oneOf``` for params and responses but thats even more obscure

**Comment by scottie1984** [comment]
This issue would probably sit more with swagger-ui (https://github.com/swagger-api/swagger-ui). The issue would be best placed solved there.

With this module being a wrapper around swagger-ui the only current option would be multiple urls as you detailed.

I will close for now. Please reopen if needed
