### ISSUE TITLE
Response with multiple examples does not change example values

### ISSUE THREAD

**Issue by elielr01** [scottie1984/swagger-ui-express#232]
Hello guys, thanks for this great library. Really enjoying it so far!

I have found that for responses that have multiple examples, the select with all the examples appear correctly, but when selecting another option it does not changes the example shown.

Example 1: Bad Request
![image](https://user-images.githubusercontent.com/9769936/102499118-c303da80-40b5-11eb-8bf0-66d48a8d6596.png)

Change to example 2: Invalid Payload
![image](https://user-images.githubusercontent.com/9769936/102499168-d31bba00-40b5-11eb-8e8d-5890335d9ac4.png)

This is the extract of the OpenAPI definition of my response in JSON format:

```json
{
  "400": {
    "description": "Bad request. Also sent when payload is invalid.",
    "content": {
      "application/json": {
        "schema": {
          "$ref": "#/components/schemas/HTTPError"
        },
        "examples": {
          "BadRequest": {
            "errorType": "BadRequest",
            "code": 400,
            "message": "Bad request"
          },
          "InvalidPayload": {
            "errorType": "InvalidPayload",
            "code": 400,
            "message": "Invalid payload"
          }
        }
      }
    }
  }
}
```

I checked using the redux inspector and it is correctly dispatching the action `oas3_set_active_examples_member`, so Idk if that could be a hint?

![image](https://user-images.githubusercontent.com/9769936/102499724-7e2c7380-40b6-11eb-84b5-d209f9cbc211.png)

If I'm doing something wrong, I would appreciate it if someone could point out to me what's my error 😅

**Comment by scottie1984** [comment]
I would open this issue with swagger-ui project directly.

**Comment by elielr01** [comment]
Oh okok. Then I'll close this and check with swagger-ui. Thanks for the info!

**Comment by petey9891** [comment]
You need to add a value to your response example:
Success: {
   value: {
       /* example code */
   }
}
