### ISSUE TITLE
Error handling middleware not working

### ISSUE THREAD

**Issue by jinnatul** [scottie1984/swagger-ui-express#233]
Swagger config
```js
import swaggerJsDoc from 'swagger-jsdoc';

const swaggerOptions = {
  swaggerDefinition: {
    info: {
      version: '1.0.0',
      title: 'eCommerce',
      description: 'Application Programming Interface for eCommerce application.',
      contact: {
        name: '@TeamTigers',
      },
      servers: ['http://localhost:4000', 'https://bideshi.herokuapp.com/'],
    },
    securityDefinitions: {
      jwt: {
        type: 'apiKey',
        name: 'Authorization',
        in: 'header',
      },
    },
    security: [
      {
        jwt: [],
      },
    ],
  },
  apis: [
    './src/router/router.js',
  ],
};

const swaggerDocs = swaggerJsDoc(swaggerOptions);

export default swaggerDocs;

```

app.js
```js
app.use('/', swaggerUI.serve, swaggerUI.setup(swaggerDocs));

app.all('*', (req, res, next) => {
  next(new AppError(`Can't find ${req.originalUrl} on this server!`, 404));
});
```
When I visit this route `http://localhost:4000/` then I show swagger UI like this.
![Screenshot](https://user-images.githubusercontent.com/31995155/102715675-46653c00-4301-11eb-887a-4c7b560fc799.png)

But, when I visit an anonymous route like `http://localhost:4000/api/data` then I got this error.
![a1](https://user-images.githubusercontent.com/31995155/102715757-bd9ad000-4301-11eb-839d-49f3ad3c9f07.png)

when i hide this line `// app.use('/', swaggerUI.serve, swaggerUI.setup(swaggerDocs));`
then i got my custom error message
![a2](https://user-images.githubusercontent.com/31995155/102715814-02266b80-4302-11eb-9a02-6dfcb0c73376.png)

So, how to way I can solve this problem?

**Comment by scottie1984** [comment]
Recommendation is to place the swagger routes under /docs or something else as to not interfere with your application routes

**Comment by jinnatul** [comment]
Now it's working but when I visit `/docs/somthing` then still i got this error.
https://user-images.githubusercontent.com/31995155/102715757-bd9ad000-4301-11eb-839d-49f3ad3c9f07.png

**Comment by scottie1984** [comment]
Instead of 

```
app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(swaggerDocs));
```

you could use 

```
app.use('/api-docs', swaggerUI.serve)
app.get('/api-docs', swaggerUI.setup(swaggerDocs));
```
