### ISSUE TITLE
Stringified example numbers interpreted as numbers.

### ISSUE THREAD

**Issue by sserperior** [scottie1984/swagger-ui-express#238]
I have a small testcase which exhibits the above behavior with swagger-ui-express 4.1.6 and swagger-jsdoc 6.0.1:

const express = require('express');
const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

const swaggerSpecification = swaggerJsdoc({
    swaggerDefinition: {
        openapi: '3.0.0',
        info: {
            title: 'Hello World',
            version: '1.0.0'
        }
    },
    apis: ['./index.js']
});

const app = express();

/**
 * @swagger
 *
 * components:
 *  schemas:
 *      TestInput:
 *          properties:
 *              inputText:
 *                  type: string
 *                  example: '6000'
 *
 * paths:
 *  /api/test:
 *      post:
 *          requestBody:
 *              description: test input
 *              required: true
 *              content:
 *                  application/json:
 *                      schema:
 *                          $ref: '#/components/schemas/TestInput'
 */
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpecification));
app.post('/api/test', (req, res) => {
    res.send({
        result: true
    });
});

app.listen(3000, () => console.log('Express listening on port 3000'));

when I go to the /api-docs URL to load the Swagger-UI page, I see the following in the Request body:

{
  "inputText": 6000
}

and the same when I click on "Try it out". The 6000 should be in quotes and was with an earlier version of this stack. How do I get the 6000 quoted again in both the request body display and the try it out control?

**Comment by scottie1984** [comment]
Apologies for the delay - I hope you have fixed the issue - if not it would be better to raise with [swagger-ui ](https://github.com/swagger-api/swagger-ui).

Will close for now
