### ISSUE TITLE
Swagger theme

### ISSUE THREAD

**Issue by mat-twg** [scottie1984/swagger-ui-express#239]
Hello! I find template https://github.com/jensoleg/swagger-ui and whant to use it... but how to? Can you give me some advice?

**Comment by scottie1984** [comment]
Module doesn't support themes at the moment - just custom css https://github.com/scottie1984/swagger-ui-express#custom-css-styles

Happy to take a PR to support this.

**Comment by cocuba** [comment]
when is gonna be supported?
