### ISSUE TITLE
Swagger UI with CSP blocking 'unsafe-inline'

### ISSUE THREAD

**Issue by blackcathacker** [scottie1984/swagger-ui-express#24]
I am attempting to use Swagger-UI-Express within an SPA that uses CSP and blocks 'unsafe-inline' to protect against potential XSS vulnerabilities. This breaks the swagger UI due the inline <script> tag. My proposed solution for this is to move this js into a static file. Maybe 'swagger-ui-init.js'. Moving all template options into a separate hidden div that contains a stringified json object with all pertinent options. The swagger-ui-init would then load these options via document.getElementById.innerText and JSON.parse.

Thoughts or concerns? Happy to submit a PR if this all seems reasonable.

**Comment by scottie1984** [comment]
Might be easier to template out 'swagger-ui-init.js' in the setup function and then in the returned setup middleware have an if statement to either return the 'swagger-ui-init.js' or the index.html based on the url. 

What do you think?

**Comment by blackcathacker** [comment]
Sounds alright to me. I'll give it a try.
