### ISSUE TITLE
insecure question

### ISSUE THREAD

**Issue by nicetomeetnode** [scottie1984/swagger-ui-express#240]
hello,when i use swagger-ui-express in nestjs,i couldn't  find how to set username and passwd to protect apis info,and everyone  can read my apis info with swagger,it is insecure ,how to set username and passwd in my project to avoid it ,please find me a solution ,thanks very much

**Comment by scottie1984** [comment]
This would be outside the scope of this module. You should be able to protect the endpoints using some express middleware setup
