### ISSUE TITLE
swagger-ui-express is not working on the live environment (works locally)

### ISSUE THREAD

**Issue by DelandPo** [scottie1984/swagger-ui-express#243]
![image](https://user-images.githubusercontent.com/22736790/112387439-c499fb80-8cbf-11eb-8c41-72e4cddee08b.png)

Getting ```swagger-ui-init.js:6956 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (swagger-ui-init.js:6956)```

**Comment by scottie1984** [comment]
Related to https://github.com/scottie1984/swagger-ui-express/issues/237 perhaps?

**Comment by scottie1984** [comment]
Also previous issues with webpack https://github.com/scottie1984/swagger-ui-express/issues/176

**Comment by manel00** [comment]
It literally happens to me the same, and still its not working, there is no workaround? How can it be possible?
