### ISSUE TITLE
Increase RequestTimeout for the api's

### ISSUE THREAD

**Issue by sarikonda1** [scottie1984/swagger-ui-express#244]
I am using node-js swagger ui-express..

I am doing bulk insert and update operable in the databases..So the APi's is taking almost 5-10 mins to execute.
But Swagger is showing "failed to fetch response" after 1 min(60 sec)..
Do we have any option to change the request timeout (Swagger need to wait untill response come i.e 10 mins)..
I need it badly ...It quite helpfull...
Thanks in Advance

**Comment by sarikonda1** [comment]
I am using node-js swagger ui-express..

I am doing bulk insert and update operable in the databases..So the APi's is taking almost 5-10 mins to execute.
But Swagger is showing "failed to fetch response" after 1 min(60 sec)..
Do we have any option to change the request timeout (Swagger need to wait untill response come i.e 10 mins)..
I need it badly ...It quite helpfull...
Thanks in Advance

**Comment by scottie1984** [comment]
Looks like this is not yet implemented in swagger-ui https://github.com/swagger-api/swagger-ui/issues/3659
