### ISSUE TITLE
Loading this package in Node takes ~1 minute every time.

### ISSUE THREAD

**Issue by imkane** [scottie1984/swagger-ui-express#245]
My hardware is at the top end, too. 

The ~1 minute count is from the time I make a GET on the API docs UI page to the time the page loads. However the same behavior happens if I include the package in app.js and run `npm start`.

Does anyone else experience this? It's specific to this package.

**Comment by scottie1984** [comment]
Hopefully you managed to resolve this - closing for now.

**Comment by imkane** [comment]
@scottie1984 yep! Sorry forgot to update it. 

Rather than loading Swagger in app.js, we changed it to load for a specific route.
