### ISSUE TITLE
The swagger-ui is stuck / very slow in a post request with a huge object response

### ISSUE THREAD

**Issue by shrsbg** [scottie1984/swagger-ui-express#247]
Hi,
I'm using `"swagger-ui-express": "4.1.4"` and when I send as a response a big object, the UI is stuck or very very slow.
When I use postman, for example, I get the response very fast.

Can someone help please?

**Comment by ah-kevin** [comment]
the same

**Comment by rix-nohup** [comment]
the same problem

**Comment by rix-nohup** [comment]
**this work for me**

into file
node_modules/swagger-ui-express/index.js

at
row: 104

change swaggerOptions


  var swaggerOptions = {
    syntaxHighlight: {
      activated: false,
      theme: "agate"
    },

**Comment by ah-kevin** [comment]
i build swagger ui dist , length>20000 syntaxHighlight activated is false.

**Comment by shrsbg** [comment]
> **this works for me**
> 
> into file
> node_modules/swagger-ui-express/index.js
> 
> at
> row: 104
> 
> change swaggerOptions
> 
> var swaggerOptions = {
> syntaxHighlight: {
> activated: false,
> theme: "agate"
> },

Thanks but I can't run the service after that unfortanly

**Comment by shrsbg** [comment]
> i build swagger ui dist , length>20000 syntaxHighlight activated is false.

@ah-kevin I didn't get you, sorry

**Comment by jmroon** [comment]
Same issue here. An 888kB response with 602 rows (mongodb) returns in around 200ms but takes 1-2 minutes to render.

**Comment by scottie1984** [comment]
Suggest raising with swagger ui https://github.com/swagger-api/swagger-ui directly
