### ISSUE TITLE
Showing requestBody as fillable form when executing request on UI

### ISSUE THREAD

**Issue by veyselyenilmez** [scottie1984/swagger-ui-express#251]
Hey,
When I use `"application/x-www-form-urlencoded"` content-type under the `"requestBody: content:"` and click the Try It Out button, the result I get is a fillable form in User Interface. But when I use `"application/json"` content-type and click the Try It Out button, the result is raw JSON editing in the UI.

The problem is my API only accepts `application/json` request body. 

So is there way to get fillable form in the UI while using the `application/json` content-type?

Thanks in advance.
___
```
post:
  summary: Create user
  description: Creates user according the input data
  requestBody:
    content:
      application/x-www-form-urlencoded:
        schema:
          type: object
          required:
          - active
          - username
          - email
          - password
          properties:
            active:
              type: boolean
              description: ""
            firstname:
              type: string
              description: İsim
              example: John
            lastname:
              type: string
              example: Doe
            username:
              type: string
              description: User Name
              example: johndoe
            password:
              type: string
              description: PassWord
            email:
              type: string
              description: Email Address
              example: johndoe@johndoe.com_

```

**Comment by scottie1984** [comment]
I suggest raising this directly with https://github.com/swagger-api/swagger-ui

**Comment by veyselyenilmez** [comment]
> I suggest raising this directly with https://github.com/swagger-api/swagger-ui

Thank you. My bad.
