### ISSUE TITLE
Can I put Swagger UI endpoint behind express authentication middleware?

### ISSUE THREAD

**Issue by ghettosamson** [scottie1984/swagger-ui-express#252]
I have a single page web application using Express and NodeJS on the back-end and I'm using this swagger-ui-express npm module. Our project wants to put the api-docs endpoint behind custom written authentication middleware, so you can only access the api-docs route if you are logged in. Currently this is how we add the swagger endpoint 
`router.use('/api-docs', swaggerUi.serve, swaggerUi.setup(null, options));`
Is it possible to protect this route and make it use the same authentication middleware that the rest of our routes are using, or is this not possible?

**Comment by schealex** [comment]
would also like to know this!

**Comment by scottie1984** [comment]
I am not sure how you would get this to work with an SPA. Most likely you would want a separate URL to host the Docs directly from the API.

You should be able to add middleware though for custom authentication but it would have to respect the page coming from the server.

**Comment by Coinhexa** [comment]
Would it work with a regular express route?
```

app.use(
  '/swagger',
  swaggerUi.serveFiles(swaggerDocument),
  swaggerUi.setup(swaggerDocument),
);
```
How would I make this route accessible only behind a login if I was using passportjs? In my specific case I am using passport-local
