### ISSUE TITLE
Is it possible to pass variables to request interceptors ?

### ISSUE THREAD

**Issue by ypicard** [scottie1984/swagger-ui-express#258]
Hi,

I am trying to pass a custom request interceptor to the swagger configuration. Unfortunately, I cannot manage to pass a custom variable to this function. I get an `undefined` variable error.

```
const audience ='...' // I would like to use this
app.use(
    prefix + '/docs',
    swaggerUi.serve,
    swaggerUi.setup(openapiSpecification, {
        swaggerOptions: {
            requestInterceptor: (request: Request) => {
                if (request.url.includes('oauth/token')) {
                    const body = `${request.body}&audience=${encodeURIComponent('http://localhost:3000')}`; <---- Here, if I replace this with the audience variable above.

                    return {
                        ...request,
                        body,
                    };
                }

                return request;
            },
            oauth: {
                clientId: process.env.AUTH0_CLIENT_ID,
                clientSecret: process.env.AUTH0_CLIENT_SECRET,
            },
        },
    })
);
```

Is this even possible? Thank you!

**Comment by danielfev** [comment]
same problem.. any solution?

**Comment by scottie1984** [comment]
This function is run on the client - so you will not have access to anything from the server. You could try using the using some custom js to define some variables that you could then use https://github.com/scottie1984/swagger-ui-express#custom-js. However you might run into scoping problems depending on how the requestInterceptor function it called.
