### ISSUE TITLE
Swagger UI is slow/unresponsive most of the time.

### ISSUE THREAD

**Issue by dir** [scottie1984/swagger-ui-express#263]
I am able to serve the UI perfectly fine, but when I try and click on various things, i.e. opening an endpoint, it doesn't open on 95% of my clicks, same goes for the rest of the features. Overall just super slow and buggy on my end for some reason.

Here is my code:

```js
const express = require('express');
const app = express();
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./_build/swagger.json');

const port = 3000

app.use('/', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

app.listen(port, () => {
    console.log(`Swagger UI listening at http://localhost:${port}`)
})
```

I also seem to be getting these errors in console a bit:
![Screen Shot 2021-07-15 at 1 18 22 PM](https://user-images.githubusercontent.com/6627316/125837699-30adb43f-4120-41ff-b6de-3237a929d65c.png)

**Comment by dir** [comment]
So far I have tried, uninstalling and reinstalling `swagger-ui-dist` and `swagger-ui-express`, I have also tried changing my endpoint on `app.use()` from `/` to `/docs` to no avail.

**Comment by dir** [comment]
Just enabled "explore", also incredibly slow/buggy as well. I have one endpoint in this entire application and it just infinite loads.

**Comment by scottie1984** [comment]
Is your swagger document correct? It seems to be complaining about an Invalid base URL. 

I will close for now - please reopen if needed
