### ISSUE TITLE
Can't find any html element in Custom javascript

### ISSUE THREAD

**Issue by talatkuyuk** [scottie1984/swagger-ui-express#271]
In the `htmlTplString `, there is a place for ` <% customJs %>`. The custom javascript is placed in the html header, so I am not able to find any html element with **querySelector**, **getElementById** or **getElementByClassName** in the swagger ui with custom js.

I needed the ` <% customJs %>` placed just after the `<script src="./swagger-ui-init.js"> </script>` and before the `<% customCssUrl %>` in the template. In that case I am able to find the html element whatever I want in the swagger ui. (I tested it.)

**Comment by scottie1984** [comment]
Should be fixed now as part of https://github.com/scottie1984/swagger-ui-express/releases/tag/4.2.0
