### ISSUE TITLE
swagger UI stops working (white screen of death)

### ISSUE THREAD

**Issue by tamis-laan** [scottie1984/swagger-ui-express#273]
After a while my swagger ui stops working showing a blank screen and the following client console errors:
```
*/:8 GET https://*/docs/swagger-ui.css net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
*/:71 GET https://*/docs/swagger-ui-standalone-preset.js net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
*/:70 GET https://*/docs/swagger-ui-bundle.js net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
swagger-ui-init.js:1045 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (swagger-ui-init.js:1045)
window.onload @ swagger-ui-init.js:1045
load (async)
(anonymous) @ swagger-ui-init.js:2
/docs/favicon-16x16.png:1 GET https://*/docs/favicon-16x16.png net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
/docs/favicon-32x32.png:1 GET https://*/docs/favicon-32x32.png net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
```
I'm using swagger-jsdoc to generate the schema from comments in the source code. I can fix the problem by commenting out apis, generating an empty schema, refreshing the swaager ui and then again uncommenting apis and generating the full schema again:
``` javascript
apis: [
  // './src/**/*.js'
]
```
``` javascript
apis: [
  './src/**/*.js'
]
```
After a while swagger stops working again and I have to repeat the trick from above to get things working again.

Versions:
```
"swagger-jsdoc": "^6.1.0",
"swagger-ui-express": "^4.1.6",
```
and node 16

In my staging environment where the code is first bundled and deployed I can't get the UI to work at all. I'm always getting a blank screen even though the OpenApi spec is loaded correctly from a json file generated using swagger-jsdoc during the build. 

This is a problem for front end developers who need the docs as a reference.

**Comment by tamis-laan** [comment]
In order to make things more clear, here is what's happening illustrated visually:
![step0](https://user-images.githubusercontent.com/3178666/143918028-97192f40-aaae-4b09-8552-15087a844754.png)
![step1](https://user-images.githubusercontent.com/3178666/143918011-10d50797-42d8-48cc-a58f-d972d4c420d3.png)
![step3](https://user-images.githubusercontent.com/3178666/143918057-7587ef77-a2bf-4db9-bfb1-c5c8190aab93.png)
![step4](https://user-images.githubusercontent.com/3178666/143918066-ed5c462a-e6e1-4194-bb5a-f194655d49a5.png)
![step5](https://user-images.githubusercontent.com/3178666/143918075-aa962164-0ae0-4939-9e60-80a7aed5bd7e.png)
![step6](https://user-images.githubusercontent.com/3178666/143918084-7f810ba5-555e-4804-8656-1b9f067fd37c.png)

**Comment by daniloab** [comment]
Is there an error in your console `SwaggerUIBundle is not defined`

**Comment by tamis-laan** [comment]
Yes there is:
![screenshot](https://user-images.githubusercontent.com/3178666/144041643-eee2a498-8dcb-481b-a9bb-13d0edb60b25.png)

**Comment by daniloab** [comment]
> Yes there is: ![screenshot](https://user-images.githubusercontent.com/3178666/144041643-eee2a498-8dcb-481b-a9bb-13d0edb60b25.png)
> 
> BTW, looking at the source the schema definition is there, generated and loaded properly.

You need to understand why is this happening

**Comment by tamis-laan** [comment]
Error originates from here:
![screenshot](https://user-images.githubusercontent.com/3178666/144044249-e8a5e014-97fa-41dd-8a62-2578c3da8f8a.png)

For some reason swaggerUIBundle is not defined. I don't know why. Server side things look like they are working:
![screenshot](https://user-images.githubusercontent.com/3178666/144044508-58ad1aac-08ed-4cf2-ab72-a3564312cc82.png)
Maybe `swagger-ui-init.js` is wrongly cached??

**Comment by tamis-laan** [comment]
Stuff is failing when looking at network requests:
![screenshot](https://user-images.githubusercontent.com/3178666/144044977-36e248fb-2663-4fc0-8ada-7b644eff4fe4.png)

**Comment by tamis-laan** [comment]
Curl also fails:
![screenshot](https://user-images.githubusercontent.com/3178666/144045603-c7257de9-7ca5-43e0-92c8-41c5bb9f9583.png)

**Comment by tamis-laan** [comment]
Curl verbose, looks like a timeout:
![screenshot](https://user-images.githubusercontent.com/3178666/144045903-cea0a0f4-1714-496b-8f1a-930516dfd8fe.png)
Something is taking to long swagger-ui end

**Comment by tamis-laan** [comment]
Can I turn on console logging for swagger-ui-express? Make it verbose?

**Comment by scottie1984** [comment]
There is no verbose logging mode for swagger-ui-express as it essentially relying of express middleware setup.

swagger-ui-bundle.js is served via express.static so the fact this isn't being served suggests you have something wrong with your node/express server set-up. So when you do app.use(swaggerUiExpress.serve) - you are essentially calling express.static pointing to the swagger-ui assets. It is important that you don't have any race conditions or any other routes that might interfere with these calls.

My suggestion would be to go back to a basic set up using the examples in the swagger-ui-express documentation, ensure that works and then work from there to gradually put in your set up until you identify the problem.

**Comment by tamis-laan** [comment]
@scottie1984 
Thnx for the pointer, moving the swagger ui express route up fixes the problem:
``` javascript
app.use('/docs', swaggerUi.serve, swaggerUi.setup(schema))
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use(cookieParser())
```
One of these other middlewares is for some reason messing things up...
