### ISSUE TITLE
Empty required field doesn't prevent request

### ISSUE THREAD

**Issue by michaelsitte** [scottie1984/swagger-ui-express#275]
Even if a field is configured as required and also showing up as required in the UI, leaving it empty doesn't prevent the request to be fired. The request seems to run endless and the browser console returns the following:
![image](https://user-images.githubusercontent.com/31673786/145023226-26d0eea7-7128-4221-b716-68f5f2b1258c.png)

**Comment by scottie1984** [comment]
Issue would be best raised directly with swagger-ui. Seems like a known issue https://github.com/swagger-api/swagger-ui/issues/5181

**Comment by michaelsitte** [comment]
Sorry for not replying earlier. Thanks for the info.
