### ISSUE TITLE
vulnerabilities error with swagger-ui-express

### ISSUE THREAD

**Issue by mstephanysilva** [scottie1984/swagger-ui-express#276]
Hello! Even though I'm updating swagger-ui-express to version 4.2.0 I'm getting the vulnerability error in the npm audit fix command. Apparently there is a problem using versions below 4.13.0 of swagger-ui-dist. Vulnerability details was reported on this link https://github.com/advisories/GHSA-qrmm-w75w-3wpx. Is there a possibility this is causing the error?
![error](https://user-images.githubusercontent.com/73243081/145486772-ee804064-27cd-4b0e-913c-58a5cc6ed60f.png)

**Comment by rudemex** [comment]
the swagger-ui-dist dependency has already uploaded an improvement patch, it is a matter of waiting for an update.

https://github.com/swagger-api/swagger-ui/releases/tag/v4.1.3

**Comment by andreainnocenti** [comment]
@scottie1984 can you take a look at this issue please? our integration pipelines are failing due to this security issues

**Comment by scottie1984** [comment]
Fixed in https://github.com/scottie1984/swagger-ui-express/releases/tag/4.3.0

**Comment by andreainnocenti** [comment]
thank you so much! will you publish a new version? I still see the old version in https://www.npmjs.com/package/swagger-ui-dist
