### ISSUE TITLE
configure swagger-ui to root - "/"

### ISSUE THREAD

**Issue by jasminas** [scottie1984/swagger-ui-express#28]
I am trying to serve the swagger-ui content from the root of the server. My configuration looks like that:

`app.use('/', swaggerUi.serve, swaggerUi.setup(swaggerDocument));`

However, when I'm trying to access some other route defined, such as let's say "/movies", I'm still seeing the swagger-ui instead of the API response.
Is there any other way of having the swagger-ui docs in the root of the API without affecting all the other routes?

**Comment by scottie1984** [comment]
Please see issue [17](https://github.com/scottie1984/swagger-ui-express/issues/17).

Make sure you define your routes before the swagger-ui route.
