### ISSUE TITLE
Request body doesn't work

### ISSUE THREAD

**Issue by Dharanikanna** [scottie1984/swagger-ui-express#283]
I'm trying to send email and password data's using request body instead of params method, but I'm not able to see request body in the swagger-ui `"swagger-ui-express": "^4.3.0"`. 

I have the same issue. But in my case `openapi: '3.0.0'`

**Screenshot for reference**

![image](https://user-images.githubusercontent.com/55808143/150107112-42a1d7ef-32bb-48f1-bcdb-0513c0d83250.png)

**Swagger-jsdoc output**

`
{
  openapi: '3.0.0',
  info: { title: 'Node API', version: '1.0.0' },
  paths: {
    '/user/register': { post: [Object] },
    '/healthcare/heroku': { get: [Object] },
    '/healthcare/getall': { get: [Object] },
    '/healthcare/id': { get: [Object] }
  },
  components: { schema: { users: [Object] } },
  tags: []
}
`

**Code for reference**

```nodejs
//user login routes
router.post('/login',user.login)


/**
 * @swagger
 *  components:
 *      schema:
 *          users:
 *              type: object
 *              properties:
 *                  email:
 *                      type: string
 *                  password:
 *                      type: string 
 */


/**
 * @swagger
 * /user/login:
 *   post:
 *     summary: Login
 *     description: Login User
 *     requestBody:
 *       required:true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#components/schema/users'
 *     responses:
 *       201:
 *         description: User Logged in successfuly
 *         schema:
 *           type: "string"
 *       "400":
 *         description: "Invalid username/password supplied"
 */

**Comment by scottie1984** [comment]
You can test your swagger document here https://editor.swagger.io/ to make sure it is valid.

If you are still having problems I suggest raising it directly with https://github.com/swagger-api/swagger-ui
