### ISSUE TITLE
Swagger UI not loading in environment different from localhost

### ISSUE THREAD

**Issue by angelhodar** [scottie1984/swagger-ui-express#285]
Hey I have a strange bug where Swagger UI loads perfectly in localhost but it doesnt load in any other environment. The files are downloaded without error but the HTML is empty, somehow it seems like the js files arent executed or something like that

![imagen](https://user-images.githubusercontent.com/26228709/152947002-3df3a38a-df45-4f77-9f4d-2a343f04763a.png)

![imagen](https://user-images.githubusercontent.com/26228709/152946909-d4950411-379a-4ded-b161-027472a7ce7b.png)

**Comment by BlowinInWind** [comment]
So do I

**Comment by scottie1984** [comment]
Did you manage to resolve?
