### ISSUE TITLE
customfavIcon does not work

### ISSUE THREAD

**Issue by DinoscapeProgramming** [scottie1984/swagger-ui-express#287]
**Describe the bug**
I‘ve declared a variable (uiOpts) and have customCss, customSiteTitle and customfavIcon in it, the first both things are working, but not customfavIcon. The file I specified is published on my site (https://url.dinoscape.tk/favicon.webp).

**To Reproduce**
1. Declare a variable
2. Add „customfavIcon“ in it and add this variable after the configuration
3. Restart your program
4. Open the site and the favicon didn‘t changed

**Expected behavior**
I can‘t change the favicon of my site.

**Screenshots**
![DB846D68-23EA-4805-B72F-1030F0FF3DD8](https://user-images.githubusercontent.com/95239392/155140891-13734fc4-812d-4f8a-a005-382a5edd86f1.jpeg)
![D5741FA2-645D-47E9-92A1-C8EEBFB93799](https://user-images.githubusercontent.com/95239392/155142321-1973deee-a078-4af3-9eee-a3de928a14f3.jpeg)

**Tablet (yeah, i‘m using a tablet):**
 - OS: iOS
 - Browser: Safari
 - Version 14.6

**Additional context**
I tried to change the images in https://url.dinoscape.tk/docs/favicon-16x16.png and https://url.dinoscape.tk/docs/favicon-32x32.png, so the images changed, but it still doesn‘t work. Oh, and I’m using the version 3.0.

**Comment by DinoscapeProgramming** [comment]
I hope you can help me :)

**Comment by scottie1984** [comment]
Seems to be showing the correct icon on my phone

**Comment by DinoscapeProgramming** [comment]
> 
Can I make a screenshot, please?

**Comment by DinoscapeProgramming** [comment]
> 



> Seems to be showing the correct icon on my phone
Can you make a screenshot, please?

**Comment by scottie1984** [comment]
![Screenshot 2022-02-22 at 22 01 04](https://user-images.githubusercontent.com/3470971/155226898-dad032ae-f66e-4ab6-aa6c-4c9946f1828a.png)

**Comment by DinoscapeProgramming** [comment]
> ![Screenshot 2022-02-22 at 22 01 04](https://user-images.githubusercontent.com/3470971/155226898-dad032ae-f66e-4ab6-aa6c-4c9946f1828a.png)

So, this is the screenshot of https://url.dinoscape.tk/docs and not the main page?

**Comment by DinoscapeProgramming** [comment]
I really don‘t know what I should do, because in my other website the customfavIcon works.

**Comment by DinoscapeProgramming** [comment]
> I really don‘t know what I should do, because in my other website the customfavIcon works.

That makes no sense

**Comment by scottie1984** [comment]
> https://url.dinoscape.tk/docs

Yes

> > ![Screenshot 2022-02-22 at 22 01 04](https://user-images.githubusercontent.com/3470971/155226898-dad032ae-f66e-4ab6-aa6c-4c9946f1828a.png)
> 
> So, this is the screenshot of https://url.dinoscape.tk/docs and not the main page?

Yes - screenshot is from the Docs. Perhaps a browser caching issue - maybe do a hard reload, clear cache for your site, try another device or incognito browser

**Comment by DinoscapeProgramming** [comment]
I think my browser already saved the old favicon and I can‘t delete the data of my browser.

**Comment by DinoscapeProgramming** [comment]
> > https://url.dinoscape.tk/docs
> 
> Yes
> 
> > > ![Screenshot 2022-02-22 at 22 01 04](https://user-images.githubusercontent.com/3470971/155226898-dad032ae-f66e-4ab6-aa6c-4c9946f1828a.png)
> > 
> > 
> > So, this is the screenshot of https://url.dinoscape.tk/docs and not the main page?
> 
> Yes - screenshot is from the Docs. Perhaps a browser caching issue - maybe do a hard reload, clear cache for your site, try another device or incognito browser

I found a solution in stackoverflow. So but I deleted the catch data of Safari, but it doesn‘t work…

**Comment by DinoscapeProgramming** [comment]
When I can‘t found a solution I will reopen it.

**Comment by DinoscapeProgramming** [comment]
> When I can‘t found a solution I will reopen it.
