### ISSUE TITLE
Dynamic swagger docs with load balancing and/or concurrent users

### ISSUE THREAD

**Issue by tzuge** [scottie1984/swagger-ui-express#290]
Love getting express with swagger going fast with this library.

I think there is a defect or at least documentation gap around dynamic docs in production scenarios.

If I understand correctly, `swagger-ui-init.js` is generated on the first browser request in the handler returned by `setup()`, then returned on a follow-up request due to the script src, and the state is maintained in the closure over `swaggerInit`. 

```javascript
app.use('/api-docs', function(req, res, next){
    const { world } = req.query;
    swaggerDocument.info.description = `Hello ${world}!`;
    req.swaggerDoc = swaggerDocument;
    next();
}, swaggerUi.serve, swaggerUi.setup());
```

1. In a multi-user scenario, user A requests `/api-docs?world=Mars` then user B requests `/api-docs?world=Venus`, user B request would override `swaggerInit` and user A browser might get `swagger-ui-init.js` associated with user B request.

2. In a load balanced scenario, user A requests `/api-docs?world=Mars`, but the subsequent request for `swagger-ui-init.js` could go to an instance where `swaggerInit` has not been updated.

Can the initialization script just be inline with the html returned, or alternatively the swagger ui options could be included in the script src URL for `swagger-ui-init.js`?

**Comment by scottie1984** [comment]
Yep -makes sense. There is another function serveFiles which doesn’t use swaggerInit however it doesn’t use the swaggerDoc from the request. I will look to make a change and update the docs and let you know.

**Comment by scottie1984** [comment]
Released: https://github.com/scottie1984/swagger-ui-express/releases/tag/4.4.0

Close for now, please let me know.
