### ISSUE TITLE
Vercel: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by Hazelwu2** [scottie1984/swagger-ui-express#293]
Hi, I'm using vercel to deploy swagger api document

This is my full code.
```javascript
/* eslint-disable import/order */
const express = require('express')
const app = express()
const path = require('path')

// Router
const swaggerUi = require('swagger-ui-express')
const YAML = require('yamljs')

// Swagger
const swaggerPath = path.resolve(__dirname, './swagger.yml')
const swaggerDocument = YAML.load(swaggerPath)
// const cssOptions = require('./utils/swagger.js')

var options = {
  explorer: true
};

// API Document
app.use(
  '/apidoc',
  swaggerUi.serve,
  swaggerUi.setup(swaggerDocument, options),
)

app.use(express.json())

module.exports = app
```

- nodejs 14
- swagger-ui-express 4.3.0

## Problem
When I run local environment is work. It has correctly loaded css style.
![CleanShot 2022-05-02 at 16 05 11](https://user-images.githubusercontent.com/24752360/166203597-d6decb75-60ff-4871-a85e-22139bbc1fe2.png)

But running at `Vercel Production`, It's doesn't work.
Dev Tools show error
```
DevTools failed to load source map: Could not parse content for https://metawall-backend-git-feature-express-ayugioh2003.vercel.app/apidoc/swagger-ui-bundle.js.map: Unexpected token < in JSON at position 1

DevTools failed to load source map: Could not parse content for https://metawall-backend-git-feature-express-ayugioh2003.vercel.app/apidoc/swagger-ui-standalone-preset.js.map: Unexpected token < in JSON at position 1
```

![CleanShot 2022-05-02 at 16 01 42](https://user-images.githubusercontent.com/24752360/166203272-622adee5-5fa1-4520-8cf6-27adcf35833f.png)

![CleanShot 2022-05-02 at 16 07 05](https://user-images.githubusercontent.com/24752360/166203841-bd740524-3522-465a-807b-12cc333e8a80.png)

I don't understand why this error occurs, cannot load css style, I'm not sure how to fix this. 
I think it is vercel problem, same code deploy to Heroku, it's work!
Is there any idea?

**Comment by scottie1984** [comment]
Not sure - I guess this would need raised with Vercel - perhaps something to do with expected file types for your application?
