### ISSUE TITLE
Path redirect

### ISSUE THREAD

**Issue by vorticalbox** [scottie1984/swagger-ui-express#296]
```
const express = require('express');
const app = express();
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./swagger.json');

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
```
when put behind a reverse proxy under `/demo` E.g `http://localhost:8080/demo/api-docs` redirects to `http://localhost:8080/api-docs`

**Comment by scottie1984** [comment]
I can point you to a few similar issues:

https://github.com/scottie1984/swagger-ui-express/issues/237
https://github.com/scottie1984/swagger-ui-express/issues/210
https://github.com/scottie1984/swagger-ui-express/issues/111

**Comment by scottie1984** [comment]
N
