### ISSUE TITLE
The contents of the array in the form-data are converted to a single string

### ISSUE THREAD

**Issue by tomyoll** [scottie1984/swagger-ui-express#297]
I'm trying to send a form-data request that describes an array of objects. The problem is that when sending such a request, my server receives an array, the entire content of which is turned into one string.

```
"requestBody": {
     "content": {
         "multipart/form-data": {
            "schema": {
               "type": "object",
               "properties": {
                   "video[]": {
                    "type": "array",
                    "items": {
                       "type": "object",
                       "properties": {
                          "_id": {
                             "type": "string"
                          }
                       }
                    }
                 }
               }
            },
            "encoding": {
               "video[]": {
                 "contentType": "application/json",
                 "explode": true
               }
            }
         }
     }
 },
```
What I expect on server: `{ video: [{ _id: "string" }] }`

What I get: `{ video: [ '{"_id": "string"}' ] }`

I use swagger-ui-express 4.4.0

**Comment by scottie1984** [comment]
suggest raising this directly with https://github.com/swagger-api/swagger-ui

**Comment by josip-volarevic** [comment]
@tomyoll  Any secret knowledge you've obtained in the last few months that you might share with me?

Kinda have the same issue but haven't managed to dig out a solution
