### ISSUE TITLE
Use swagger-ui-dist ?

### ISSUE THREAD

**Issue by kyv** [scottie1984/swagger-ui-express#30]
Any reason you guys don't use [swagger-ui-dist](https://www.npmjs.com/package/swagger-ui-dist). Looks like its basically the same as your `static` folder.

**Comment by scottie1984** [comment]
It is the swagger-ui-dist but with a custom index.html. I don't want to use swagger-ui-dist directly as updates may break this package

**Comment by WillBartee** [comment]
Couldn't you just lock down the dependency to a single version?
