### ISSUE TITLE
my swagger not showing button authorize

### ISSUE THREAD

**Issue by farasjibran** [scottie1984/swagger-ui-express#304]
i have the problem with this library, i cant show my button authorize

this my options, i using swaggerJsdoc as swagger options, please help

```
const swaggerSpec = swaggerJsdoc({
  swaggerDefinition: {
    openapi: '3.0.0',
    info: {
      title: 'Relay API IMP STUDIO',
      version: '1.0.0',
    },
    apis: ['./routes/routes.js'],
  },
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT'
      }
     }
   },
  security: [{
    bearerAuth: []
  }],
  explorer: true,
  apis: ['./routes/routes.js'],
});
```

**Comment by Andrey-Yur** [comment]
I think you should remove {} at you pass `swaggerDefinition `object, so `const swaggerSpec = swaggerJsdoc(swaggerDefinition: {...`

**Comment by scottie1984** [comment]
Does it work when you create a JSON swagger document?

**Comment by farasjibran** [comment]
my issue is completely done. i close this issue. thank you for your answer guys
