### ISSUE TITLE
swagger authorization does not display schemas in AND scenario

### ISSUE THREAD

**Issue by asarver** [scottie1984/swagger-ui-express#309]
using 4.5.0

when there is a route that requires more than one security schema (using AND), the schema does not appear as an option (OR works though)

```
{
  openapi: '3.0.0',
  info: {
    title: 'Example'
    version: '1.0.0'
  },
  components: {
    schemas: {
      Version: {
        type: 'object',
        properties: {
          version: {
            type: 'string',
            description: 'Semantic version number for the application',
            example: '0.1.0'
          }
        }
      }
    },
    securitySchemes: {
      BearerSchema: {
        type: 'http',
        scheme: 'bearer'
      },
      HeaderSchema: {
        type: 'apikey',
        name: 'apikey',
        in: 'header'
      }
    }
  },
  paths: {
    '/': {
      get: {
        operationId: 'getVersion',
        tags: ['version'],
        summary: 'Check the running version of the API',
        security: [{ BearerSchema: [], HeaderSchema: [] }],
        responses: {
          200: {
            description: 'success',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Version'
                }
              }
            }
          }
        }
      }
    }
  }
}
```

<img width="667" alt="Screen Shot 2022-09-01 at 3 23 37 PM" src="https://user-images.githubusercontent.com/895038/187995959-c357be4c-6c9f-49d8-8ba6-1b9ca161c0e1.png">

**Comment by asarver** [comment]
it looks like the reason the second security schema isn't showing up is because swagger is case sensitive on `apikey`

```js
      HeaderSchema: {
        type: 'apikey',
        name: 'apikey',
        in: 'header'
      }
```

it really should be `apiKey`

**Comment by mriedem** [comment]
It's funny that the schema didn't catch that given it's defined here:

https://swagger.io/specification/?sbsearch=security-schemes#security-scheme-object

![image](https://user-images.githubusercontent.com/3237936/194648357-4f670db1-8ecf-4b84-8cd2-e9788f193806.png)

So should this issue be re-opened about _that_?
