### ISSUE TITLE
preauthorizeApiKey?

### ISSUE THREAD

**Issue by giggioz** [scottie1984/swagger-ui-express#311]
Is it possibile to use preauthorizeApiKey of [Swagger-UI](https://github.com/swagger-api/swagger-ui/blob/9891d97201092877059a8fc55a1c922a635b5611/docs/usage/configuration.md#instance-methods)?

I could not find anything in the repo.
Thanks!

**Comment by scottie1984** [comment]
Nothing at the moment- happy to take a PR for it.
