### ISSUE TITLE
css file dosent load on production

### ISSUE THREAD

**Issue by m0x31h0x64i** [scottie1984/swagger-ui-express#312]
index.js :
```bash
const swaggerUi = require('swagger-ui-express')
const swagger = require('./swagger')
app.use('/api-docs', swaggerUi.serve, swagger)
```
swagger file :
```bash
const swaggerJsDoc = require('swagger-jsdoc')
const swaggerUi = require('swagger-ui-express')

swaggerOptions = {
    swaggerDefinition: {
        openapi: '3.0.1',
        info: {
            title: 'APIs',
            version: '2.0.0'
        },
        servers:
        [
            {
                url: 'http://localhost:3000'
            }
        ],
        components: {
            securitySchemes:
            {
                    JWT: 
                {
                    name: 'User Authorization',
                    description: 'Value: Bearer {token}',
                    type: 'apiKey',
                    scheme: 'bearer',
                    in: 'header',
                    bearerFormat: 'JWT'
                }
            }
        }
    },
    apis: ['./routes/*.js']
}

const swaggerDocs = swaggerJsDoc(swaggerOptions)

const options = {
    customCss: '.swagger-ui .topbar { display: none }'
}

module.exports = swaggerUi.setup(swaggerDocs)
```

**Comment by scottie1984** [comment]
Your url is set to localhost. You will need to chang ethe URL based on the environment

**Comment by m0x31h0x64i** [comment]
> Your url is set to localhost. You will need to change the URL based on the environment

i removed the production server. you can consider that the above code has an production url like this :

```
servers:
        [
            {
                url: 'https://@example.com'
            }
        ]
```

it dosent work.

**Comment by m0x31h0x64i** [comment]
> Your url is set to localhost. You will need to change the URL based on the environment

could you please test the above code ? it dosent work im 100% sure

**Comment by gabrielpra1** [comment]
I'm also facing a similar issue.

I can see that the network request for `swagger-ui.css` is actually returning the HTML code instead of CSS.

**Comment by tnwanna** [comment]
Running into the same issue as well

**Comment by anjitpariyar** [comment]
@m0x31h0x64i did you solve it ? im also facing the similar issue

**Comment by m0x31h0x64i** [comment]
Hello @anjitpariyar, no bro i still have this problem.

**Comment by anjitpariyar** [comment]
@m0x31h0x64i I moved to swagger json and used cdn for CSS, its working for me at least
like this
`
const swaggerDocument = require("./swagger.json");
const swaggeroptions = {
  customCssUrl:
    "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.18.3/swagger-ui.css",
};

// connecting to swagger
app.use(
  "/api-docs",
  swaggerUi.serve,
  swaggerUi.setup(swaggerDocument, swaggeroptions)
);
`
