### ISSUE TITLE
Defaulting to https://petstore.swagger.io/v2/swagger.json and CORS error

### ISSUE THREAD

**Issue by flyfishMT** [scottie1984/swagger-ui-express#314]
I am loading my OpenAPI spec through [openapi-comment-parser](https://github.com/bee-travels/openapi-comment-parser), based upon the suggestion in this [issue](https://github.com/scottie1984/swagger-ui-express/issues/194#issuecomment-701318903).  Here is my abbreviated code;

```javascript
const express = require('express');
const cors = require('cors');
const swaggerUi = require('swagger-ui-express');
const openapi = require('openapi-comment-parser');

const specs = openapi();

const app = express();

app.use(cors());
app.use(express.json());
app.use('/swagger', swaggerUi.serve);
app.get(
  '/swagger',
  swaggerUi.setup(null, {
    swaggerOptions: {
      url: '/swagger/swagger.json',
    },
  })
);

app.get('/swagger/swagger.json', (req, res) => res.json(specs));

```
I have recently updated all my libs and not sure what changed but now the explorer bar is showing up and defaulting to https://petstore.swagger.io/v2/swagger.json, which tries to load this  and causes a CORS error (even though I am using the express-cors module). 

![image](https://user-images.githubusercontent.com/5473678/195136201-2dc47654-1acc-4d2e-baad-ab0b8a0d47af.png)

I would like it just to load my api definition and not have an explorer bar. I've tried many options - `explorer:false,` setting `url`, `swaggerUrl`, url in base yml file, etc. with no success.  

Any suggestions would be appreciated!

**Comment by scottie1984** [comment]
The get for '/swagger/swagger.json' needs to be before the app.use(‘/swagger’

**Comment by flyfishMT** [comment]
Thanks, that fixed. Strange because when it was "/api-docs" rather than "/swagger" it worked without moving.
