### ISSUE TITLE
How to serve SwaggerUI without using middleware (app.use)

### ISSUE THREAD

**Issue by Hasankanso** [scottie1984/swagger-ui-express#315]
I'm implementing a controller where I'm only responsible of the get route/function and don't have access to app.

```
const swaggerUI = require('swagger-ui');

function getSwagger(req, res) {

//swaggerUI.serve?
//swaggerUI.serveFile?

var page = swaggerUI.generateHTML(doc);

return res.send(page);
}
```

This isn't working with error 404. how do I call serve correctly in the function?

P.S.: this is a pseudo code, because I don't have access to my pc at the moment, but the idea is I don't have access to app.use and app.get, I only can implement inside of the get function.

**Comment by scottie1984** [comment]
I don’t think you will be able to do this as the serve is used to serve the assets therefore needs the app.use
