### ISSUE TITLE
[DOCS] Incorrect example in docs for modify swagger file on the fly before load

### ISSUE THREAD

**Issue by Avm07** [scottie1984/swagger-ui-express#318]
Incorrect example in readme for modifying swagger file on the fly before load:

```
const express = require('express');
const app = express();
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./swagger.json');

var options = {}

app.use('/api-docs', function(req, res, next){
    swaggerDocument.servers[0].url = req.get('host');
    req.swaggerDoc = swaggerDocument;
    next();
}, swaggerUi.serveFiles(swaggerDocument, options), swaggerUi.setup());
```

^^^ This does not work for me then I try to change 
```
swaggerDocument.servers[0].url = req.get('host')
```

Correct example, which works:

```
const express = require('express');
const app = express();
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./swagger.json');

app.use('/api-docs', function(req, res, next){
    swaggerDocument.servers[0].url = req.get('host');
    req.swaggerDoc = swaggerDocument;
    next();
}, swaggerUi.serve, swaggerUi.setup());
```

**Comment by scottie1984** [comment]
I haven't been able to replicate any issue with the docs. I don't see anything in particular as to why it might not have worked.

**Comment by Avm07** [comment]
> I haven't been able to replicate any issue with the docs. I don't see anything in particular as to why it might not have worked.

Try to see updates in the browser after the doc is loaded and updated on the fly. It will render the old version without updates, while logging will show that the document updated correctly.

**Comment by chgeo** [comment]
See https://github.com/scottie1984/swagger-ui-express/pull/336, which should fix this issue.
It's not a documentation issue, though.
