### ISSUE TITLE
swaggerUI.serve response unminified

### ISSUE THREAD

**Issue by arthurchumak** [scottie1984/swagger-ui-express#324]
![image](https://user-images.githubusercontent.com/8324045/207493408-06596306-d2f5-41b3-b3e6-cde6d00d6de2.png)
it takes to much to load it, could minified versions of swagger js scripts and styles be used?

**Comment by scottie1984** [comment]
These files are loaded in from swagger-ui-dist as we want to automatically take in the latest version. This issue would need to be addressed within Swagger UI and therefore raised directly against that project.
