### ISSUE TITLE
Required query field freezes loading

### ISSUE THREAD

**Issue by ChoppinBlockParty** [scottie1984/swagger-ui-express#328]
I am using swagger on express node.js app. I am not sure if this issues is relevant to this project, just want to check in case it is or someone can give a workaround or something.
Copied my post from [here](https://github.com/swagger-api/swagger-ui/issues/8007#issuecomment-1366645975.
):

```yaml
- name: accessToken
  description: Access Token
  in: query
  required: true
  type: string
````

If I have the above parameter the loading hangs and gives the below error in console

```
system.js:490 Error: Required parameter accessToken is not provided
    at index.js:233:13
    at Array.forEach (<anonymous>)
    at Object.Lr [as buildRequest] (index.js:200:22)
    at actions.js:452:24
    at utils.js:177:16
    at redux.js:546:12
    at wrap-actions.js:33:10
    at Object.n (system.js:175:26)
    at Object.executeRequest (system.js:487:17)
    at actions.js:499:22
(anonymous) @ system.js:490
```

No way to cancel loading, have to reload the whole page and lose all the input.

If `required: false` is set, then it works fine. But obviously required parameter is missing.

**Comment by scottie1984** [comment]
I think this would be best raised with Swagger UI directly.
