### ISSUE TITLE
Unable to get JSON file for swagger specification. 

### ISSUE THREAD

**Issue by Ishankhan21** [scottie1984/swagger-ui-express#329]
- while integrating Swagger on other frameworks and languages we have seen that we get a link to JSON file on swagger UI, but while integrating swagger with express using swagger-ui-express and swagger-jsdoc libraries we don't get link to JSON file for the API documentation. 
- Some URL like {BASE_PAHT}:{PORT}/api-doc/swagger.json

**Comment by scottie1984** [comment]
If you want to serve the json file you can follow this example:

https://github.com/scottie1984/swagger-ui-express#link-to-swagger-document

It was the deliberate intention not to serve the JSON file.
