### ISSUE TITLE
Is there a way to swap input fields on select of enum drop down

### ISSUE THREAD

**Issue by mnjdev** [scottie1984/swagger-ui-express#331]
I am using swagger with Nest JS application and I have a requirement where I need to use the same endpoint to patch different columns of the same table, with this requirement I provide the enum drop down with the column value the user wants to edit but the input field which should take in the value to be edited needs to change based on the selected value from the drop down. Thanks in advance.

**Config / setup:**
swagger-ui-express - 4.1.6
@nestjs/swagger - 5.0.9

**Comment by scottie1984** [comment]
I think you would need to refer to the Swagger UI documentation to see if anything like that exists: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
