### ISSUE TITLE
Schema properties have to be expanded to see description, datatype, & example data

### ISSUE THREAD

**Issue by jwhitehead77** [scottie1984/swagger-ui-express#334]
All Schema properties have to be expanded to see description, datatype, & example data. Not sure this was a great decision or not. Image if you had a schema that had 30 or 40 properties and you had to expand each and everyone of them. Not Ideal!

It used to be like this by default...
![image](https://user-images.githubusercontent.com/66504934/218885391-359bdac7-9090-4110-a047-30ce2d14de9d.png)

Now it is like this by default...
![image](https://user-images.githubusercontent.com/66504934/218885455-23fe3fc2-4c63-4d83-9b2d-e86204f95f0a.png)

Would really like to see it go back the other way or at the least expand them all by default.

**Comment by scottie1984** [comment]
This behaviour is from Swagger UI itself so you will need to refer to the Swagger UI configuration to see if there is any options for this: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

Swagger UI config can be passed into this module using https://github.com/scottie1984/swagger-ui-express#custom-swagger-options
