### ISSUE TITLE
I don't understand where swagger.json gets generated...

### ISSUE THREAD

**Issue by pguardiario** [scottie1984/swagger-ui-express#355]
Am I supposed to make that manually? Any links are appreciated.

**Comment by paras-verma** [comment]
If you already have YAML file you can follow [these steps](https://github.com/scottie1984/swagger-ui-express#load-swagger-from-yaml-file) to get a JSON and then pass it to the middleware

**Comment by pguardiario** [comment]
> If you already have YAML file you can follow [these steps](https://github.com/scottie1984/swagger-ui-express#load-swagger-from-yaml-file) to get a JSON and then pass it to the middleware

What if I don't already have YAML? Where would I get that YAML from?

**Comment by scottie1984** [comment]
You have to create the swagger.json file yourself - there are tools to help like https://editor.swagger.io/
