### ISSUE TITLE
links in descriptions are not getting converted to href

### ISSUE THREAD

**Issue by firefoxNX** [scottie1984/swagger-ui-express#37]
If description has markdown with link for ex `[Login](../login)`, it is not getting rendered with hyperlink in the swagger-ui.

**Comment by scottie1984** [comment]
I just upgraded the module to swagger-ui 3.4.4 and this seems to have resolved this issues. Can you download the latest version of this module and try again?

**Comment by firefoxNX** [comment]
Thanks @scottie1984 🙏🏽
