### ISSUE TITLE
font file loading fail in Secure Internet Environment 

### ISSUE THREAD

**Issue by kazikai** [scottie1984/swagger-ui-express#39]
Hi. I use swagger-ui-express very well.
 
recently. my swagger app not loaded font file ('https://fonts.googleapis.com/css)

because 'indexTemplate.html' file includes 'https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700'

`<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700" rel="stylesheet">` 

but it is not loaded in secure internet environment.

Can you include this file in npm?

**Comment by shockey** [comment]
@scottie1984 this can be closed, we resolved it in https://github.com/swagger-api/swagger-ui/pull/4598.
