### ISSUE TITLE
Pass options to SwaggerUi

### ISSUE THREAD

**Issue by abnoba12** [scottie1984/swagger-ui-express#4]
I am running my instance of swagger on an internal network. Swagger UI goes out to http://online.swagger.io/ to validate my specification. Seeing online.swagger.io can't reach my instance I get an error at the bottom of the page. This issue can be seen here http://stackoverflow.com/questions/27808804/swagger-ui-shows-error-validation-when-deployed

I need to pass "validatorUrl : null" as a parameter into SwaggerUI so it doesn't try to validate my specification against online.swagger.io

**Comment by scottie1984** [comment]
I will fix this over the weekend.

**Comment by abnoba12** [comment]
Youre awesome. Thank you for being so responsive.

**Comment by scottie1984** [comment]
Just updated to allow you to pass options into the setup function - let me know if this fixes for you. I updated the readme on how to use.

**Comment by abnoba12** [comment]
That worked perfect. Thank you.
