### ISSUE TITLE
Source map missing

### ISSUE THREAD

**Issue by noygal** [scottie1984/swagger-ui-express#40]
I'm getting this error when the chrome dev tools are opened:
 `DevTools failed to parse SourceMap`

For those files: 
`swagger-ui-bundle.js.map`
`swagger-ui-standalone-preset.js.map`
`swagger-ui.css.map`

Can you add the missing static files? Or use other solution like removing the references to those missing file from the code or bundle without the source map option?

**Comment by scottie1984** [comment]
I have just published this with these files included

**Comment by noygal** [comment]
Thanks, much appreciated.
