### ISSUE TITLE
Does the new release support OAS 3?

### ISSUE THREAD

**Issue by melkarm** [scottie1984/swagger-ui-express#43]
I see that the library has been updated to Swagger 3.4.4, but for some reason I cannot configure my JSON config except with OAS 2 format.

Am I missing something?

Thanks!

**Comment by scottie1984** [comment]
I just tried this example - https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/examples/v3.0/petstore.yaml (I converted it to json)

and it loaded correctly. Perhaps your spec json file is invalid?

**Comment by melkarm** [comment]
The silliest of mistakes, 
I was specifying the version of the specification with swagger, instead of openapi.

Many thanks!
