### ISSUE TITLE
How to use JWT authorization header in swagger-ui-express.

### ISSUE THREAD

**Issue by pavelrudenya** [scottie1984/swagger-ui-express#44]
I have the same question as [here](https://github.com/swagger-api/swagger-ui/issues/2915).
What I need is a way to add a JWT authorization header to each request. How can I process it with swagger-ui-express?

**Comment by scottie1984** [comment]
I would have to make a change to allow this to work. Looking at the link you provided:

ui.authActions.authorize({JWT: {name: "JWT", schema: {type: "apiKey", in: "header", name: "Authorization", description: ""}, value: "Bearer <JWT>"}})

I will add a authAction to the custom options and if it is defined I will pass it into the ui.authActions.authorize function. What do you think?

**Comment by pavelrudenya** [comment]
Yes, it'll be fine for my goals:) Will it a button 'Authorize' like [here](http://petstore.swagger.io/) or as  a input field in explorer? Thanks!

**Comment by scottie1984** [comment]
I have added this, let me know if it works:

```javascript
const express = require('express');
const app = express();
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./swagger.json');

var options = {
  swaggerOptions: {
    authAction :{ JWT: {name: "JWT", schema: {type: "apiKey", in: "header", name: "Authorization", description: ""}, value: "Bearer <JWT>"} }
  }
};

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, options));
```

**Comment by pavelrudenya** [comment]
@scottie1984 Sure! Thank you.

**Comment by arpit2438735** [comment]
@scottie1984 The above code is not working.

```var options = JSON.parse(document.getElementById('swagger-options').innerText)``` this line remove `JWT` from `value: "Bearer <JWT>"`

It's coming like ```"{"jwt":{"name":"jwt","schema":{"type":"apiKey","in":"header","name":"Authorization"},"value":"Bearer "}}"```

**Comment by scottie1984** [comment]
@arpit2438735 I believe you have to replace <JWT> with your auth token

**Comment by arpit2438735** [comment]
@scottie1984 you meant to say hardcoded token? I didn't get what you trying to say, can you explain in more details.Thanks

**Comment by scottie1984** [comment]
@arpit2438735 apologies, yes - replace < JWT > with a hardcoded token. Please follow [this](https://github.com/swagger-api/swagger-ui/issues/2915) issue for where the solution can from (and other possible solutions.

**Comment by SpiresAwake** [comment]
I just tried to implement this with Basic authentication. This is my code:
`basicAuth: {name: "basicAuth", schema: {type: "basic", in: "header", name: "Basic Auth", description: ""}, value: "Basic <base64 encoded user:password combination>"}`

It's not working though. The token in the sent request also evaluates to "undefined:undefined". I also tried:
`basicAuth: {name: "basicAuth", schema: {type: "basic", in: "header", name: "Basic Auth", description: ""}, value: "Basic <user:password>"}`

The generated request looks right, except for the "value" part:

> curl -X GET "<URL>" -H "accept: application/json" -H "authorization: Basic dW5kZWZpbmVkOnVuZGVmaW5lZA=="

which gives me the same result. What am I doing wrong?

**Comment by scottie1984** [comment]
I haven't been able to find a way to do with with Swagger UI. I suggest trying to raise an issue with Swagger UI directly as they will be in a much better position to help. From that if you manage to find something that needs added to this module then I am happy to do so.

**Comment by stefanrockon** [comment]
@scottie1984 Apart from adding the "authAction" property in the "swaggerOptions" object (exactly like above, with my own jwt token), do I need to specify a security schema like the one below? When I use this, the "Try it out" --> "Execute" buttons throw the error below and do not execute any request.
```yaml
# swagger.yaml
/users: # token protected api
    x-swagger-router-controller: userController
    get:
      summary: Get list of users
      description: ""
      operationId: getUsers
      # some code here ..
      security:
        - authentication: []

securityDefinitions:
  authentication:
    type: apiKey
    name: Authorization
    in: header
```
Error:
```js
TypeError: o is undefined
Stack trace:
t.default<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:52:83216
p/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:62:130652
c/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:62:130385
t.default/</</<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:92:99717
t.default/</<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:92:99671
pe.prototype.withMutations@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:1:34201
t.default/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:92:99643
p@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:52:210751
v/</</<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:1:60393
r/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:92:102197
t.validateParams/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:52:92856
r@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:62:133500
p/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:62:130652
t/r.onClick@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:62:44606
r@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:38:59584
a@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:38:55670
s@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:38:55887
h@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:49327
m@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:49455
r@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:52:186344
processEventQueue@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:50517
r@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:91:95984
handleTopLevel@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:91:96057
o@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:91:96508
perform@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:72177
batchedUpdates@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:91:94764
o@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:12315
dispatchEvent@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:91:97363
swagger-ui-bundle.js:62:130704
TypeError: p.forEach is not a function
Stack trace:
i@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:53:18787
e.exports</t.default@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:53:19564
o@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:53:15848
t.executeRequest/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:90735
v/</</<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:1:60386
r/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:92:102197
t.executeRequest/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:52:92770
r@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:62:133500
p/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:62:130652
Y</<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:91554
v/</</<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:1:60386
r/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:92:102197
t.execute/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:52:39623
r@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:62:133500
p/<@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:62:130652
t/r.onClick@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:62:44702
r@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:38:59584
a@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:38:55670
s@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:38:55887
h@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:49327
m@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:49455
r@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:52:186344
processEventQueue@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:50517
r@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:91:95984
handleTopLevel@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:91:96057
o@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:91:96508
perform@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:72177
batchedUpdates@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:91:94764
o@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:12:12315
dispatchEvent@http://localhost:8080/api/api-docs/swagger-ui-bundle.js:91:97363

```

**Comment by scottie1984** [comment]
What version of swagger spec are you using? 

Can you post your swagger-ui-express options?

```JAVASCRIPT
const options = {
  swaggerOptions: {
    authAction :{ JWT: {name: "JWT", schema: {type: "apiKey", in: "header", name: "Authorization", description: ""}, value: "Bearer <JWT>"} }
  }
};
```

The name of the key in the object and name property need to match the security definition, so for the example you posted your swagger options would need to be: 

```JAVASCRIPT
const options = {
  swaggerOptions: {
    authAction :{ authentication: {name: "authentication", schema: {type: "apiKey", in: "header", name: "Authorization", description: ""}, value: "Bearer <JWT>"} }
  }
};
```

**Comment by stefanrockon** [comment]
I am using swagger spec 3.0
My swagger-ui-express options are:

```JS
var customSwaggerOptions = {
  swaggerOptions: {
    explorer: true,
    authAction: {
      JWT: {
        name: 'JWT',
        schema: {
          type: 'apiKey',
          in: 'header',
          name: 'Authorization',
          description: ''
        },
        value: 'Bearer <my own JWT token>'
      }
    }
  }
}
```
The 'options' work, because the search bar is hidden using the 'explorer : true' property. However, after making sure the name are the same, the errors are the same (in developer console): no request is being made. If I use the 'Authorize' button to log out, I can see the request being made (without authorization header) and I get 401. 

The security definition in swagger.json
``` JSON
    "securitySchemes": {
      "JWT": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    }
```

**Comment by scottie1984** [comment]
Are the security definitions in a components section? 

```
"components": {
     "securitySchemes": {
         "JWT": {
            "description": "",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
         }
     }
   }
```

**Comment by DanielNetzeriAm** [comment]
anyway to achieve this using the Token attached to the swagger Authorize button?

**Comment by troymolsberry** [comment]
I was able to get this working by having my client put the token in the path as a parameter. This seems to load fine in an iframe using the token for authentication
`
                self.app.use('/api-docs/:token', function (req, res, next) {
                    req.headers['x-api-token'] = req.params.token;
                    securityHandlers.ApiHeaderTokenSecurity(req, ["Admin"]).then(function (succeeded) {
                        if (succeeded) {
                            next();
                        } else {
                            res.status(401).send("Authentication failed");
                        }
                    }).catch(function (err) {
                        self.logger.info(err);
                        res.status(401).send("Authentication failed");
                    });
                }, swaggerui.serve, swaggerui.setup(self.openapi.apiDoc));
`

**Comment by kozikkam** [comment]
Hi, I don't think this feature works right now. I specify JWT validation as follows:
swagger.json
```
  "components": {
    "securitySchemes": {
      "JWT": {
        "description": "",
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    }
  },
  "security": {
    "bearerAuth": []
  },
```

My swagger options
```
      explorer: true,
      swaggerOptions: {
        authAction: {
          JWT: {
            name: 'JWT',
            schema: {
              type: 'apiKey',
              in: 'header',
              name: 'Authorization',
              description: ''
            },
            value: 'Bearer <my own JWT token>'
          }
        }
      }
```

An authorization button appears in swagger after adding this code. If it remains untouched, a request is being made as expected. If anything is being filled in to authorization (in a field that pops up after pressing the auth button in top right corner), requests are not being made at all.

Am I doing something wrong?

**Comment by scottie1984** [comment]
Would a workaround of adding some css to hide the authorization button work in your case? If the request works without touching it?

**Comment by kozikkam** [comment]
I mean, I want to send authorization header, but if I try as much as adding anything as my token through that button, the request never stops sending.

**Comment by scottie1984** [comment]
Is this related? https://github.com/scottie1984/swagger-ui-express/issues/118.

My guess is that this issue is with swagger-ui itself, so would be best placed raised with that project

**Comment by kozikkam** [comment]
Thank you! I also had an issue with my requestBody.

**Comment by waynebloss** [comment]
Here's a plan to save your authorization token automatically after you login. If I implement this code, I'll try to remember to come back here and update this comment.

```js
  app.use(
    API_DOCS_PATH,
    swaggerUI.serve,
    swaggerUI.setup(apiSpec, {
      swaggerOptions: {
        docExpansion: "none",
        plugins: [
          {
            afterLoad: function(ui) {
              // NOTE: Code inside this afterLoad function will run in the browser!
              // See: https://github.com/scottie1984/swagger-ui-express/blob/master/index.js#L239

              // Other Notes:
              // See https://github.com/swagger-api/swagger-ui/blob/master/src/core/system.js#L344
              // See https://github.com/swagger-api/swagger-ui/issues/2915#issuecomment-297405865

              // var swaggerOptions = this;

              // TODO: Get auth token from localStorage.

              // TODO: Put auth token into Swagger:
              // ui.authActions.authorize({ SCHEMA_NAME: { name: "SCHEMA_NAME", schema: {type:"apiKey", in: "header", name: "Authorization", description: ""}, value: "<THE TOKEN>"}});

              // TODO: On interval, Call ui.getState(); and get auth token from:
              // "auth.authorized[SCHEMA_NAME].value", by finding strings in _root.entries[]...
              // _root.entries[4][1]._root.entries[0][1]._root.entries[0][1]._root.entries[2][1]
              // TEST: console.log("STATE: ", ui.getState());

              // TODO: In same interval, save fresh auth token into localStorage.

              // TEST: With hard-coded JWT...

              setTimeout(function() {
                ui.authActions.authorize({
                  AuthJWT: {
                    name: "AuthJWT",
                    schema: {
                      type: "apiKey",
                      in: "header",
                      name: "Authorization",
                      description: "",
                    },
                    value:
                      "<JWT TOKEN WITHOUT THE WORD Bearer>",
                  },
                });
              }, 1000);
            },
          },
        ],
      },
    }),
  );
```

**Comment by him7797** [comment]
@scottie1984 i'm not able to authorize token with above codes!!..i'm using swagger-ui-express.

**Comment by emretufekci** [comment]
seems issue still persist.
```

const swaggerOptions = {
  swaggerDefinition: {
    info: {
      version: "1.0.0",
      title: "REST API",
      description: "REST API Information",
      contact: {
        name: "AUTH TEST"
      },
      servers: ["http://localhost:99097"]
    },
    components: {
      securitySchemes: {
        bearerAuth: {
          description: "JWT Authorization",
          type: "https",
          scheme: "bearer",
          in: "header",
          bearerFormat: "JWT",
        }
      }
    },
    security: {
      bearerAuth: [],
    },
  },
  apis: ["routes/user.routes.js"]
};

```

I've above configs but i can see only blank page when i click auth button.

**Comment by jeremyfry** [comment]
Just adding a note here for anyone landing here from the preserve auth token issue above. If you're trying to get your authorization token to persist between refreshes you can use swaggerOptions to pass in a ```persistAuthorization``` value like this:
```
  app.use(
    '/api-docs',
    swaggerUi.serve,
    swaggerUi.setup(swaggerDoc, {
       swaggerOptions: {
          docExpansions: "none",
          persistAuthorization: true
       }
    })
  );
```

**Comment by yashwanthrk** [comment]
> @scottie1984 i'm not able to authorize token with above codes!!..i'm using swagger-ui-express.

To dynamically add token after login
`
export function renderSwaggerUi(token) {
  const swaggerUiOptions = {
    swaggerOptions: {
      authAction: {
        bearerAuth: {
          name: "JWT",
          schema: {
            type: "http",
            in: "header",
            name: "Authorization",
          },
          value: `${token}`,
        },
      },
    },
    persistAuthorization: true,
  };
  swaggerUi.setup(swaggerDocument, swaggerUiOptions);
}
`

**Comment by torressam333** [comment]
@jeremyfry thank you for showing how to persist the bearer token!

**Comment by JhonFather** [comment]
O que funcionou comigo foi o seguinte código no arquivo swagger.json.

Código abaixo logo após a configuração de info:

"swaggerOptions": {
        "docExpansions": "none",
        "persistAuthorization": true
    },
    "securityDefinitions": {
        "bearerAuth": {
            "type": "apiKey",
            "name": "x-auth-token",
            "scheme": "bearer",
            "in": "header"
        }
    },

Codigo abaixo no final do arquivo:

"components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "name": "x-auth-token",
                "scheme": "bearer",
                "in": "header"
            }
        }
    },

    "security": [{ "bearerAuth": [] }]

Espero ter ajudado
