### ISSUE TITLE
Non position dependent custom swagger options

### ISSUE THREAD

**Issue by beanilsson** [scottie1984/swagger-ui-express#45]
Maybe this is more of a feature request, but it would be neat to not have to account for the position of the options when declaring them. Also, it's a bit weird to have to set a lot of `null` parameters if I only want to utilize the custom url option for example; `app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(null, null, null, null, null, 'http://petstore.swagger.io/v2/swagger.json'));`

My proposal is to send an object where custom options can be defined in whatever order, or left out if not needed. So in regard to the above example, it would be something like this instead:
`app.use('/api-docs', swaggerUi.serve, swaggerUi.setup({'loadUrl': 'http://petstore.swagger.io/v2/swagger.json'}));`

**Comment by scottie1984** [comment]
Agreed - I will fix it over the next week

**Comment by scottie1984** [comment]
Hopefully fixed. Let me know if you have any problems

**Comment by beanilsson** [comment]
Awesome, thanks! Closing the issue then 👍
