### ISSUE TITLE
If you're going to make backwards-compatible breaking changes to your API, you need to increment more than the patch version

### ISSUE THREAD

**Issue by EdwardDrapkin** [scottie1984/swagger-ui-express#46]
My builds broke because you do not follow semver.

Please follow semver.

Another breakage and I will drop your package and use something else.  It's not a hard standard to follow and wasting a bunch of others' time because you're too lazy is really rude.

**Comment by scottie1984** [comment]
Can you explain the issue? It was not meant to be a breaking change, apologies for the time wasted.

**Comment by EdwardDrapkin** [comment]
The only thing I did was try to create a new yarn.lock file and wound up with this stack trace:

```
 stack:
   [ 'TypeError: Cannot read property \'explorer\' of null',
     '    at Object.setup (/Users/edwarddrapkin/projects/kraken-event-scheduler/node_modules/swagger-ui-express/index.js:13:23)',```

Downgrading to the release from yesterday(?) fixed it.

**Comment by scottie1984** [comment]
Apologies, i will fix this now!

**Comment by EdwardDrapkin** [comment]
Thanks, sorry for venting, it was extremely frustrating to have a build break at deployment and have no idea why and it took a while to figure it out.

**Comment by scottie1984** [comment]
No problem - I have fixed the issue now. Any problems let me know.
