### ISSUE TITLE
Serving swagger-ui-express from route subdir

### ISSUE THREAD

**Issue by pedgarcia** [scottie1984/swagger-ui-express#48]
My node/express application has the following directory structure:

/app.js
/routes.1/apidoc.js

where apidocs.js basically contains:

```
const router = require('express').Router(),
  swaggerUi = require('swagger-ui-express'),
  YAML = require('yamljs'),
  path = require("path"),
  swaggerDocument = YAML.load(path.join(__dirname + '/../api.1/swagger2.yaml'));

router.get('/', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
```

When I access `localhost/1/apidocs` I get an "almost good" response, which means the swagger-ui index.html is loaded, but its references to all CSS and JS files are wrong, therefore failing to load the page.

I can see the index.html file uses a relative path 

```
<script src="./swagger-ui-express/static/swagger-ui-bundle.js"> </script>
```

which is apparently points to an invalid path when calling the route via the browser, for example

```
Request URL:http://localhost:30300/1/apidoc/swagger-ui.css
Request Method:GET
Status Code:404 Not Found
```
So what I see from this reponse, the base URL is of my route and that's why swagger-ui.css cannot be found, since is located under the `node_modules/etc/etc`.

So my questions are 

Does swagger-ui-express support what I am trying to do here?

If it does, what am I doing wrong?

Thanks

Paulo

**Comment by scottie1984** [comment]
Change your router code in apidocs.js as follows:

```javascript
router.use('/', swaggerUi.serve);
router.get('/', swaggerUi.setup(swaggerDocument));
```

Hope that helps.

**Comment by select** [comment]
@scottie1984 this should be in the README.md thanks

**Comment by scottie1984** [comment]
@select can you suggest where? All the examples in the readme use app.use

**Comment by select** [comment]
I'd put it just below 

> Express setup app.js

```
const express = require('express');
const app = express();
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./swagger.json');

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
```
or if you are using Express router 
```
const router = require('express').Router();
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./swagger.json');

router.use('/', swaggerUi.serve);
router.get('/', swaggerUi.setup(swaggerDocument));
```

something along the lines

**Comment by select** [comment]
maybe even drop the swagger imports, since it's obvious from the first example

**Comment by minh-hd** [comment]
> Change your router code in apidocs.js as follows:
> 
> ```js
> router.use('/', swaggerUi.serve);
> router.get('/', swaggerUi.setup(swaggerDocument));
> ```
> 
> Hope that helps.

Thank you for your solution! 🙏🙏🙏
