### ISSUE TITLE
How to set the client_id for OAuth 2

### ISSUE THREAD

**Issue by otusweb** [scottie1984/swagger-ui-express#5]
I'm trying to integrate with AuthO so basically, I need to configure swagger to use OAuth 2.0

My problem right now is I can't find a way to override 
`clientId: "your-client-id"` 
from IndexTemplate on line 60

Any tips?

**Comment by scottie1984** [comment]
This should be possible by passing a custom onComplete function into swagger-ui-express:

```javascript
const options: {
      onComplete: function(swaggerApi, swaggerUi){
	   if(typeof initOAuth == "function") {
	       initOAuth({
	           clientId: "your-client-id",
	           clientSecret: "your-client-secret-if-required",
	           realm: "your-realms",
	           appName: "your-app-name",
	           scopeSeparator: ",",
	           additionalQueryStringParams: {}
	       });
	  }
          if(window.SwaggerTranslator) {
	       window.SwaggerTranslator.translate();
	  }
     }
}
	
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, false, options));
```

Let me know and if it doesn't work I can create a new version to allow you to pass oAuth options through.

**Comment by otusweb** [comment]
Looking at index.js, JSON.stringify is called on options, so the method is lost at that point.

**Comment by scottie1984** [comment]
Apologies - my bad! 

{
	 clientId: "your-client-id",
	 clientSecret: "your-client-secret-if-required",
	 realm: "your-realms",
	 appName: "your-app-name",
	 scopeSeparator: ",",
	 additionalQueryStringParams: {}      
}

Would you accept being able to pass in this object to the module?

**Comment by otusweb** [comment]
Yes, that would work for me

**Comment by scottie1984** [comment]
Just added so you should be able to define custom ouath settings like so:

```javascript
var options = {
	validatorUrl : null,
	oauth: {
	 clientId: "your-client-id1",
	 clientSecret: "your-client-secret-if-required1",
	 realm: "your-realms1",
	 appName: "your-app-name1",
	 scopeSeparator: ",",
	 additionalQueryStringParams: {}
       }
};

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, false, options));
```

Let me know if that works and I will update the documentation. You will need to make sure to define all the oauth settings as it simply replaces the current object with the one you define.

**Comment by grayyang** [comment]
@scottie1984 , any updates on this issue? I also need this to provides additional query parameters.
The solution you are going to provide as above is OK for us.

I made a local test by adding following code into the indexTemplate:
```javascript
...
  var ui = SwaggerUIBundle(swaggerOptions)

  if (customOptions.oauth) {
    ui.initOAuth(customOptions.oauth)
  }

  window.ui = ui
...
```

**Comment by scottie1984** [comment]
I have merge that in - let me know if everything works ok.

**Comment by grayyang** [comment]
I have tested using the v2.0.3 npm package, it works well.

**Comment by lgibso34** [comment]
> Just added so you should be able to define custom ouath settings like so:
> 
> ```js
> var options = {
> 	validatorUrl : null,
> 	oauth: {
> 	 clientId: "your-client-id1",
> 	 clientSecret: "your-client-secret-if-required1",
> 	 realm: "your-realms1",
> 	 appName: "your-app-name1",
> 	 scopeSeparator: ",",
> 	 additionalQueryStringParams: {}
>        }
> };
> 
> app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, false, options));
> ```
> 
> Let me know if that works and I will update the documentation. You will need to make sure to define all the oauth settings as it simply replaces the current object with the one you define.

Is the "oauth" param documented anywhere? Had quite the trouble finding out how to do this and would like to help anyone in the future find this easier. You have a line in the README "For all the available options, refer to Swagger UI Configuration" but the key "oauth" does not exist there.

Thanks.

**Comment by scottie1984** [comment]
> 

Any help documenting this would be great.
