### ISSUE TITLE
Swagger ui displays paths vendor extensions as a path

### ISSUE THREAD

**Issue by kidnme** [scottie1984/swagger-ui-express#50]
If I have:

`...`
`paths:`
&nbsp;&nbsp;&nbsp;`x-vendor-extension:`
&nbsp;&nbsp;&nbsp;`/pets:`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`...`

Shouldn't I only get /pets as a path in the UI? Currently, it displays both x-vendor-extension and /pets.
 
OAS 2 specifies paths must begin with a slash and 'x-' signals a vendor extension (that I assume would be ignored in the displayed UI).

**Comment by scottie1984** [comment]
This is an issue with swagger-ui. There is an open issue which seems related [https://github.com/swagger-api/swagger-ui/issues/3757](3757)
