### ISSUE TITLE
UI Does not change when the schema has changed

### ISSUE THREAD

**Issue by rusith** [scottie1984/swagger-ui-express#51]
I use this package to merge some docs and show the UI in one endpoint. when one of the docs changed , i  call the setup function with the new merged JSON. but the UI does not change.

When something changed , I do this.
```TS
 this._setupFunc = swaggerUi.setup(this._schema);
 this._app.use('/', swaggerUi.serve, this.serve.bind(this));
```
The `this.serve` function calls `this._setupFunc` function.

**Comment by scottie1984** [comment]
For this I would serve the Swagger document as a url - that way you can change the Swagger document as you need without having to keep serving this module.

[https://github.com/scottie1984/swagger-ui-express#load-swagger-from-url](https://github.com/scottie1984/swagger-ui-express#load-swagger-from-url)

**Comment by rusith** [comment]
Will try that, thank you very much

**Comment by rusith** [comment]
Serving as URL worked.
Closing this because the solution is already there.
