### ISSUE TITLE
Input value not passed on url when testing end point.

### ISSUE THREAD

**Issue by dcvice1967** [scottie1984/swagger-ui-express#55]
I am using the following:
"swagger-express-jsdoc": "^1.0.3",
    "swagger-jsdoc": "^1.9.7",
    "swagger-ui-express": "^2.0.15"

path: /chemicals/:id
action: get
I have an end point that takes an integer as an input parameter.
  *     parameters:
  *       - name: id
  *         in: path
  *         description: id for a specific chemical
  *         required: true
  *         schema:
  *           type: integer

I am able to type a number in the ui and hit execute but the parameter value is always ':id' instead of the value I passed in. The end point works fine testing it from Insomnia.

**Comment by scottie1984** [comment]
the path in swagger should be path: /chemicals/{id}
