### ISSUE TITLE
Relative path issue.

### ISSUE THREAD

**Issue by ananth03** [scottie1984/swagger-ui-express#56]
when I split swagger spec to different json files, it display resolver error.

Errors

Resolver error at paths./students.$ref
Could not resolve reference because of: Tried to resolve a relative URL, without having a basePath. path: './tt.json' basePath: 'undefined'

**Comment by scottie1984** [comment]
How are you splitting the file? I think you will need to join the files together before passing to this module.

The bottom section 'Tools' of this article might help: [http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html](http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html)
