### ISSUE TITLE
formData send String instead Array

### ISSUE THREAD

**Issue by DaBoogie** [scottie1984/swagger-ui-express#57]
I have the next configuration of data, and it is rendered properly as array input in UI (with different fields for each value).
- name: test
     in: formData
     type: array
       items:
       type: integer

But when I trying to send this data, it causes next curl string:
curl -X POST "http: // localhost: 3000 / test" -H "accept: application / json" -H "Content-Type: application / x-www-form-urlencoded" -d **"test = 1,2,3,4 "**
and node receiving this data as **string** type.
I think when I POST'ing formData with an array type, it should looks like the request below, which leads to the correct sending of the **array** data type:
curl -X POST "http: // localhost: 3000 / test" -H "accept: application / json" -H "Content-Type: application / x-www-form-urlencoded" -d **'test=1&test=2&test=3&test=4'**

How can I achieve this?

**Comment by scottie1984** [comment]
The swagger definition for the property should include the collection: multi option i.e.:

{
           "name": "test",
           "in": "formData",
           "type": "array",
           "collectionFormat": "multi",
           "items": {
             "type": "integer"
            }
 }

**Comment by DaBoogie** [comment]
Thanks. It works for me!

**Comment by munezerobagira** [comment]
I am having the same issue, on openAPI 3.0 and  I tried that solution and It didn't work for me
