### ISSUE TITLE
formData parameter with file upload

### ISSUE THREAD

**Issue by seanmcilvenna** [scottie1984/swagger-ui-express#58]
I have the following parameters on a request:

` 
       "parameters": [{
          "name": "profileId",
          "in": "formData",
          "required": true,
          "type": "string"
        }, {
          "name": "file",
          "in": "formData",
          "type": "file",
          "required": "true"
        }],
`

When the request is submitted with the data, the "file" parameter in the form-data is not being sent.
Can you tell me why?

**Comment by scottie1984** [comment]
How are you processing the form in Express - does it handle files i.e. [multer](https://www.npmjs.com/package/multer)? Also ensure the request is a POST

**Comment by seanmcilvenna** [comment]
I am using the "multiparty" module to parse the request's body into form data.
Here's the basic logic:

`
            var form = new multiparty.Form();

            var parsedBody = { };
            form.on('error', function (err) {
                console.log(err);
            });

            form.on('part', function (part) {
                if (part.filename) {
                    streamToArray(part, function (err, bytes) {
                        parsedBody[part.name] = {
                            filename: part.filename,
                            content: Buffer.concat(bytes)
                        };
                        part.resume();
                    });
                }
            });

            form.on('field', function (name, value) {
                parsedBody[name] = value;
            });

            form.on('close', function () {
              // do stuff with parsedBody
            });

            form.parse(req);
`

This logic works fine with my browser-based <form>...

**Comment by seanmcilvenna** [comment]
Wow... Not sure what happened. But, it magically started working. Oddest thing, I didn't touch any real logic. Just added some tracing logs! Weird. Thanks for your willingness to help, at least :)
