### ISSUE TITLE
Resource/Path Not in Order

### ISSUE THREAD

**Issue by dlbrown06** [scottie1984/swagger-ui-express#59]
The Swagger HTML does not maintain the order that the swagger.json file has in the paths.

For example if I list '/first-path' '/second-path', the swagger HTML randomly orders the two paths in the HTML.

Is there an option or something I'm missing that enforces the order to be maintained?

**Comment by scottie1984** [comment]
That would be a swagger-ui issue. Swagger-ui does allow you to define an operationsSorter [https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md)

You should be able to pass operationsSorter as an option to this module and it will add it to the swagger-ui options. I think there is an issue at the minute with submitting functions as options with this module that I will have to look into separately if you require this.

**Comment by dlbrown06** [comment]
It looks like this function never is called when debugging. It isn't very clear what parameters this should be defined in though... :/
```
app.use('/', swaggerUi.serve, swaggerUi.setup(null, {
  swaggerUrl: '/__docs',
  operationsSorter: (a => {
    return a;
  })
}));
```

**Comment by scottie1984** [comment]
Ok - I have a fix for the reason the function is not being passed in correctly. I will package it up tomorrow and include on here an example of how to define the sort.

**Comment by scottie1984** [comment]
I just updated the module to allow functions to correctly get passed in. 

An examples sorter function is:

```javascript
operationsSorter: function (a, b) {
	 var score = {
		 '/test': 2,
		 '/bar': 1
	 }
	 return score[a.get("path")] < score[b.get("path")]
 }
```
where score is the order you want the paths to appear
