### ISSUE TITLE
what is the customization story

### ISSUE THREAD

**Issue by bschmitlin** [scottie1984/swagger-ui-express#6]
what is the preferred way to use the latest version of swagger-ui (ex: 2.2.8 at the time of this writing instead of 2.1.5 built in swagger-ui-express)? 
How do I provide my own UI customisations? 

Thank you.

**Comment by scottie1984** [comment]
The version of Swagger-UI is bundled with the module (as I have some code
templated in to support various features). To update to the latest version
I would need to update the module and make sure there is no breaking
changes. This is something I was only going to do on an ad-hoc basis.

As for UI customisations this is not something I intended with the module -
though I am open to suggestions or PRs on what would be required to allow
this to work.

**Comment by JigSawFr** [comment]
will be great to have customization possibility 😋

**Comment by scottie1984** [comment]
would just allowing you to supply a custom CSS file suffice?

**Comment by metaodi** [comment]
With #9 merged, it's now possible to add arbitrary CSS to the swagger-ui page.

**Comment by douglasrlee** [comment]
It would be nice to add custom js to the page too for when custom css just isn't enough.

**Comment by BruceHem** [comment]
<img width="144" alt="screen shot 2017-12-17 at 8 44 36 am" src="https://user-images.githubusercontent.com/15667259/34075864-9968e43c-e306-11e7-87ab-ce911fbf1036.png">

Is possible to change the title as well?

**Comment by scottie1984** [comment]
@BruceHem pass customSiteTitle into the options - example:

```javascript
var swaggerUiOpts = {
	customSiteTitle: 'Test 123'
}

app.use('/api-docs-using-object', swaggerUi.serve)
app.get('/api-docs-using-object', swaggerUi.setup(swaggerDocument, swaggerUiOpts));
```

**Comment by scottie1984** [comment]
JS and CSS can now be pass in. See docs
