### ISSUE TITLE
Cannot load YAML file (Version 3.0.0)

### ISSUE THREAD

**Issue by raksit31667** [scottie1984/swagger-ui-express#61]
I attempted to load YAML to use as following code below:
```
const swaggerUI = require('swagger-ui-express')
const YAML = require('yamljs')
const path = require('path')
const swaggerDocument = YAML.load(path.join(__dirname, '/swagger.yaml'))
app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(swaggerDocument))
```

When I tried to `npm start` it displayed the error like this:

`
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),
`

`
Error: ENOENT: no such file or directory, open '<directory>/node_modules/swagger-ui-express/swagger-ui-init.js'
`

However, I reverted back to version 2.0.15 and it worked.

**Comment by scottie1984** [comment]
Sorry about that - can you try 3.0.1? I have revert the broken commit and will look into it further later.

**Comment by raksit31667** [comment]
I've recently changed to version 3.0.1 and it's working, looking forward to receiving updates.

Thank you very much.
