### ISSUE TITLE
Redirect loop when serving static

### ISSUE THREAD

**Issue by Can-Sahin** [scottie1984/swagger-ui-express#62]
Using  version `3.0.1`

Library creates a middleware for serving static with redirect option set to true (default is true)

```javascript
var serve = express.static(__dirname + '/static');  // Means express.static(__dirname + '/static', { redirect: true }); 
```
This causes infinite redirect when I try to load `.../api-docs` endpoint. Constantly redirecting to `api-docs` endpoint and throws `too many redirects` error

I solved it with a workaround replacing the 'serve' with my own implementation disabling the redirect on static middleware

```javascript
const staticPathForSwagger = () => {
    // tslint:disable-next-line:no-eval
    const dir = eval('require.resolve("swagger-ui-express")');
    return express.static(Path.dirname(dir) + '/static', { redirect: false });
};
this.express.use('/api-docs/', staticPathForSwagger(), swaggerUI.setup(swaggerDocument));
```

What could be the reason of it ? Can't figure it out
Using `webpack 4.1.1` with `serverless-webpack 5.0`. Can this be a post-transpile issue? I have basic knowledge about transpilers.

**Comment by scottie1984** [comment]
Do you have code anywhere redirecting pages with a trailing slash to a page without a trailing slash?

**Comment by Can-Sahin** [comment]
I'm not sure what you mean. 

Some info.
This is a rest api. Swagger is the only html response I am returning. Other endpoints are json return type. I'm not using static files anywhere else. There is no explicit redirect in the code. There is only one express route so far and it starts with `../api/user/...`

**Comment by scottie1984** [comment]
I am unable to recreate this using a local express server. What I was trying to get at is there somewhere in your stack that is removing trailing slashes from routes therefore causing the redirect loop?

I can add to this module the ability to pass static options in? That will at least allow you to workaround the issue more elegantly?

**Comment by Can-Sahin** [comment]
Yes thanks. You can simply modify `serve` to accept `serveStatic.ServeStaticOptions` to use instead default ones. Cause I am not removing trailing slashes deliberately anywhere. I dont exactly know how express works in details though. So it could be simply my bad doing something wrong somehere. Its now a very small api and cant yet figure it out.

**Comment by scottie1984** [comment]
I added the serveWithOptions which will accept the express.static options e.g. 

```javascript
app.use('/api-docs/', swaggerUi.serveWithOptions({ redirect: false }))
```
