### ISSUE TITLE
When swagger-ui-express will support Open API 3.0 (swagger-ui v3.13.0)

### ISSUE THREAD

**Issue by GillianPerard** [scottie1984/swagger-ui-express#64]
Hi,

I love Swagger and I tried the new Open API 3.0 but currently it only supported by the swagger-ui 3.13.0 and I would like to know when swagger-ui-express will be updated for this version.

FYI I tested it with my swagger.yaml file (OAS 3.0) that I have converted with yamljs as it says in the documentation and everything seems to work but I got an error from swagger-ui-bundle.js:62:130704 (o is undefined) when I try to execute a route.
I suppose it's due to my swagger.yaml version.

So if you have some informations about a new release, it would be great!

Thank you in advance!

**Comment by scottie1984** [comment]
I can update the swagger-ui version tomorrow to 3.13.0. However the version of swagger ui (3.9.2) that is bundled with swagger-ui-express should already support Open API 3.0.

Perhaps you have another issue somewhere? If you copy your yaml file into the swagger editor you can verify if you want valid swagger:

https://editor.swagger.io/

**Comment by GillianPerard** [comment]
Thanks for your answer.

I tested my swagger file with the swagger editor and I've no issue but I still got the same error.

<img width="1035" alt="capture d ecran 2018-03-25 a 09 51 53" src="https://user-images.githubusercontent.com/8409476/37872947-4bd002a6-3012-11e8-8a62-5cf9c513dd2c.png">

**Comment by scottie1984** [comment]
I have updated this module to 3.13.0

**Comment by GillianPerard** [comment]
Well now I get no error.

Thanks a lot !
