### ISSUE TITLE
Only last document is shown

### ISSUE THREAD

**Issue by DanielNetzer** [scottie1984/swagger-ui-express#65]
https://stackoverflow.com/questions/49607146/swagger-ui-express-module-instantiates-only-the-last-defined-document

**Comment by scottie1984** [comment]
This is because the of the require caching the returned function. I could provide a generateHTML function that you could call and provide some documentation on how to use?

**Comment by scottie1984** [comment]
And I have spotted a variable that gets reset and would cause only the last settings to be used. I will provide some new functions to fix this.

**Comment by DanielNetzer** [comment]
sounds good, waiting for  your PR

**Comment by DanielNetzer** [comment]
if you can direct me in to the problematic area, I can work out a fix and submit a pr.

**Comment by scottie1984** [comment]
I have created a branch feature/generate-html that lets you generate the HTML and does not sure any variables:

```javascript
var swaggerHtml = swaggerUi.generateHTML(swaggerDocument, swaggerUiOpts)

app.use('/api-docs-html1', swaggerUi.serveFiles(swaggerDocument, swaggerUiOpts))
app.get('/api-docs-html1', (req, res) => { res.send(swaggerHtml) });
```

Can you check it out before I publish?

**Comment by DanielNetzer** [comment]
works great, appreciate it

**Comment by hermanzamula** [comment]
> I have created a branch feature/generate-html that lets you generate the HTML and does not sure any variables:
> 
> ```js
> var swaggerHtml = swaggerUi.generateHTML(swaggerDocument, swaggerUiOpts)
> 
> app.use('/api-docs-html1', swaggerUi.serveFiles(swaggerDocument, swaggerUiOpts))
> app.get('/api-docs-html1', (req, res) => { res.send(swaggerHtml) });
> ```
> 
> Can you check it out before I publish?

In that case custom swagger ui options don't work

**Comment by scottie1984** [comment]
@hermanzamula  I am unable to replicate - can you provide more details in a separate issue?
