### ISSUE TITLE
Dynamic Base URL and Scheme

### ISSUE THREAD

**Issue by LuukDeVille** [scottie1984/swagger-ui-express#66]
We are hosting our API on multiple stages. Due to this, the base URL and Scheme are changing. As the Swagger file (version 2) has only one static value for Base URL, we needed to adapt it manually so far.

I am not sure whether handling different stages is in the scope of Swagger UI, however support for it would be great.

In the meantime, we have come up with the following workaround, in order to improve the situation:
```
router.use(
  swaggerUi.serve,
  function(req, res) {
    swaggerDocument.host = req.get('host'); // Replace hardcoded host information in Swagger file
    swaggerDocument.schemes = [req.protocol]; // Replace hardcoded protocol information in Swagger file
    swaggerUi.setup(swaggerDocument)(req, res);
  }
);
```

**Comment by scottie1984** [comment]
Thanks - I could accept the host and schemes as parameters to this module and then set them as your example? Would that work?

**Comment by shockey** [comment]
FYI: if you omit `host` or `schemes` in your Swagger document, Swagger UI will use the host and scheme that your document was retrieved from.
