### ISSUE TITLE
CustomCSS example doesn't work

### ISSUE THREAD

**Issue by jennaprice** [scottie1984/swagger-ui-express#67]
Hello, 

Thank you for putting this module together it has really saved me a lot of time. I have copied the code from your exact example:

`const swaggerUi = require('swagger-ui-express');
const  swaggerDocument = require('./swagger.json');

var options = {
    customCss: '#header {display: none }'
  };

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, options));
`
But I wasn't seeing any change in the CSS. I realized there is no element called header in the HTML, and instead I used the class .topbar and it worked.

It took me a while to figure out why the customCSS wasn't working. As a side note it may be nice to allow the definition of a different CSS file.

**Comment by scottie1984** [comment]
Thanks - apologies for the incorrect instructions. I have updated the README.

I will consider how to allow the CSS as a file for a future version :)

**Comment by vabhishek-me** [comment]
any updates on allowing file?

**Comment by scottie1984** [comment]
Just added this - let me know how you get on: https://github.com/scottie1984/swagger-ui-express#custom-css-styles-from-url

**Comment by vabhishek-me** [comment]
not working. I'm trying to use one of the themes from: https://github.com/ostranme/swagger-ui-themes

Doing view-source shows
```
<style>
undefined
</style>
```

**Comment by scottie1984** [comment]
Can you post your setup?

**Comment by vabhishek-me** [comment]
```
import { Router } from 'express';
import swaggerUI from 'swagger-ui-express';
import appRootPath from 'app-root-path';
import yamljs from 'yamljs';

const swaggerDoc = yamljs.load(`${appRootPath}/docs/swagger.yml`);

const options = {
  explorer: true,
  swaggerOptions: {
    docExpansion: 'none'
  },
  customCssUrl: 'https://raw.githubusercontent.com/ostranme/swagger-ui-themes/develop/themes/3.x/theme-newspaper.css',
};

const swaggerRouter = Router();
swaggerRouter.use('/', swaggerUI.serve, swaggerUI.setup(swaggerDoc, options));
```

**Comment by scottie1984** [comment]
Thanks - 2 issues:

* I had the CCS file url in the wrong place in the template - I have fixed that now in version 4.0.4
* You won't be able to use github to get the css file as it is not a file server. You will have to host the file  yourself or use something like - https://cdn.jsdelivr.net/npm/swagger-ui-themes@3.0.0/themes/3.x/theme-newspaper.css

**Comment by vabhishek-me** [comment]
Thanks! Works perfectly!

**Comment by methodbox** [comment]
I am using this package along with swagger-jsdoc. I can't seem to make this work as expected. It just doesn't change the theme at all.

I was originally doing docs in JSDoc but it was too cumbersome to have the JSDoc comment **and** yaml-in-JSDoc, so I moved them into yaml for the Swagger docs.

Here's my config:

```js
const swaggerOptions = {
  swaggerDefinition: {
    info: {
      title: "my-api",
      description: "API",
      contact: {
        name: "****",
      },
    },
    servers: [`http://localhost:5000`],
  },
  apis: ["src/index_docs.yaml", "src/internal_docs.yaml"],
  customCssUrl: "docs.css",
};

const swaggerDocs = swaggerJsdoc(swaggerOptions);
app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDocs));
```

**Comment by cgd1** [comment]
> I am using this package along with swagger-jsdoc. I can't seem to make this work as expected. It just doesn't change the theme at all.
> 
> I was originally doing docs in JSDoc but it was too cumbersome to have the JSDoc comment **and** yaml-in-JSDoc, so I moved them into yaml for the Swagger docs.
> 
> Here's my config:
> 
> ```js
> const swaggerOptions = {
>   swaggerDefinition: {
>     info: {
>       title: "my-api",
>       description: "API",
>       contact: {
>         name: "****",
>       },
>     },
>     servers: [`http://localhost:5000`],
>   },
>   apis: ["src/index_docs.yaml", "src/internal_docs.yaml"],
>   customCssUrl: "docs.css",
> };
> 
> const swaggerDocs = swaggerJsdoc(swaggerOptions);
> app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDocs));
> ```

Also stuck with this issue :(
