### ISSUE TITLE
Several swagger files

### ISSUE THREAD

**Issue by tofik-mamishov** [scottie1984/swagger-ui-express#69]
I try to split my swagger.yml into separate files according to [swagger's docs](https://swagger.io/docs/specification/using-ref/), but I get an error: 
`Tried to resolve a relative URL, without having a basePath. path: 'docs/definitions/locales.yml#Locales' basePath: 'undefined'`
I've been changing path to './docs/definitions/locales.yml#Locales' and '../docs/definitions/locales.yml#Locales', but I've got still the same error. The only way to get it works: set url like 'localhost:3000/docs/definitions/locales.yml#Locales' and setup express to work with static.

**Comment by scottie1984** [comment]
I think you will need to join the files together before passing to this module.

The bottom section 'Tools' of this article might help: http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html

**Comment by yakovenkoroman1993** [comment]
My solution:
```js
const app = express();
...
specs.forEach(spec => (
  app.route(`${spec.basePath}/spec.json`).get((req, res) => res.json(spec));
));
...
app.use('/docs-api', swaggerUi.serve, swaggerUi.setup(undefined, {
        explorer: true,
        swaggerUrl: `${specs[0].basePath}/spec.json`,
        swaggerOptions: {
            'urls.primaryName': specs[0].basePath,
            urls: specs.map(({spec}) => ({
                name: spec.basePath,
                url: `${spec.basePath}/spec.json`
            })),
        },
 }));
```
Go to http://localhost:3000/docs-api/ and you can see follow:
![image](https://user-images.githubusercontent.com/13461433/41274763-cd64530c-6e48-11e8-9273-3c81af149caf.png)

**Comment by MuhammadAkif** [comment]
Guys there is a heck i found. I changed my json files to js file and every js file return json object now can easily spilt my json into multiple files. You can also import multiple file in js file an plugin u want.
