### ISSUE TITLE
Split swagger.json to smaller json files

### ISSUE THREAD

**Issue by eldimious** [scottie1984/swagger-ui-express#70]
Hey, i am trying to split swagger.json to smaller JSON files, for example, I tried to create another definitions.json file, where I put the definitions and then using $ref I am trying to add them in swagger.json, but get an error message:

`Tried to resolve a relative URL, without having a basePath. path: '...' basePath: 'undefined'`

**Comment by scottie1984** [comment]
I think you will need to join the files together before passing to this module (this module will only deal with one full swagger document).

The bottom section 'Tools' of this article might help: http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html

**Comment by maxbook** [comment]
```javascript
const JsonRefs = require('json-refs');
const YAML = require('js-yaml');
const fs = require('fs');

function yamlContentProcessor (res, callback) {
    callback(undefined, YAML.safeLoad(res.text));
}

async getSwaggerDocWithRefs(rootFilePath){
    let rootOpenApiJSON = YAML.load(fs.readFileSync(rootFilePath).toString());
    let swaggerDoc = await JsonRefs.resolveRefs(rootOpenApiJSON, {
        location : rootFilePath,
        loaderOptions: {
            processContent: yamlContentProcessor
        },
    });
    return swaggerDoc.resolved;
}

let swaggerDoc = await getSwaggerDocWithRefs('./openapi.yaml');
```
