### ISSUE TITLE
The las version in npm is 3.0.9

### ISSUE THREAD

**Issue by dancespiele** [scottie1984/swagger-ui-express#72]
Hello I try to download the last version by npm but the last version published is 3.0.9 instead of 3.14.1
and this version I saw that doesn't support swagger 3.0 (OPEN-API 3.0)

**Comment by ClintEsteMadera** [comment]
I'm just migrating to Open API 3 and I can tell that `swagger-ui-express@3.0.9` seems to support a v3 spec, though swagger-ui is not allowing me to enter the bearer token (as a header) so all requests are failing due to lack of authentication. Any clue, anyone? Thanks!

**Comment by scottie1984** [comment]
The version of this module is 3.0.9, it contains swagger-ui 3.14.1. So this module should support swagger 3.0

**Comment by ClintEsteMadera** [comment]
yeah, it works. The problem I mentioned regarding HTTP Bearer (using with JWT) pertains more to swagger-ui rather than this library (see https://github.com/swagger-api/swagger-ui/issues/4481) thanks @scottie1984  for the quick feedback.

**Comment by dancespiele** [comment]
Could you provide me a example that works with Swagger,
I put this in the beginning of the file

```yaml
swagger: "3.0"
info:
  version: "1.0.0"
  title: THINGS-API

host: localhost:8000

basePath: /

schemes:
  - http

consumes:
  - application/json

produces:
  - application/json
```

Maybe I miss something

**Comment by dancespiele** [comment]
I think the problem was that I had to put this `openapi: "3.0.0"` instead of `swagger: "3.0"`

**Comment by dancespiele** [comment]
@ClintEsteMadera @scottie1984 the problem was mine
