### ISSUE TITLE
Swagger UI Express Support for OAS 3.0? 

### ISSUE THREAD

**Issue by pdushkin** [scottie1984/swagger-ui-express#74]
Hi. 

I am using swagger-ui-express and having a hard time moving from OAS2 to OAS3.

I am getting a ton of errors which imply that I my YAML file is still being evaluated as OAS2.0:
```
Project Errors
--------------
#/: Missing required property: swagger
#/: Additional properties not allowed: components,servers,openapi
#/paths/~1auth~1info~1firebase/get/responses/200: Not a valid response definition
#/paths/~1posts~1{id}~1comments/get/responses/200: Not a valid response definition
#/paths/~1posts~1{id}~1comments/get/parameters/2: Not a valid parameter definition
#/paths/~1posts~1{id}~1comments/get/parameters/1: Not a valid parameter definition
#/paths/~1posts~1{id}~1comments/get/parameters/0: Not a valid parameter definition
#/paths/~1users~1{id}~1profile/get/responses/200: Not a valid response definition
```

I have updated swagger-ui-express to the latest version. 

As that didn't make a difference, I tried the below: 

docker pull swaggerapi/swagger-ui
docker run -p 80:8080 swaggerapi/swagger-ui
You can now open swagger-ui on your machine via 80:

But I am still getting the above errors. 

What am I doing wrong?

**Comment by scottie1984** [comment]
swagger-ui-express will not return these errors. My only suggestion is to try placing your swagger document here: [https://editor.swagger.io/](https://editor.swagger.io/) and ensuring it is valid
