### ISSUE TITLE
How to auto generate swagger schema ?

### ISSUE THREAD

**Issue by thapliyalmanoj** [scottie1984/swagger-ui-express#75]
Hi i'm fresher in express, node, 
           Frameworks like spring boot the schema auto generated for UI . Here i create file after error "file not found" swagger.json but how to generate auto schema on this file . 
Should i need hard code schema in swagger.json or something else?

**Comment by scottie1984** [comment]
Not sure I understand your issue, is the swagger document auto generated from the framework you are using? And you want to serve it to swagger-ui-express?

Is the swagger document generated as an API endpoint via the framework?

**Comment by thapliyalmanoj** [comment]
Yes in Java framework Spring documentation is auto generated. 
So i want exactly same with node and express because "swagger-ui-express" is top listed package i thought maybe i'm missing something. 

also i found another solution for this->
I'm handy with postman export JSON from there and convert it to swagger format by using https://apimatic.io/transformer.

**Comment by scottie1984** [comment]
Ok - I recommend you use [swagger-jsdoc](https://www.npmjs.com/package/swagger-jsdoc) to auto generate the swagger document from your code. Or [swagger-tools](https://www.npmjs.com/package/swagger-tools) if you want to use the swagger document to drive your API

**Comment by thapliyalmanoj** [comment]
Ok -  Thanks a lot  Stephen .
