### ISSUE TITLE
end of the stream or a document separator is expected

### ISSUE THREAD

**Issue by jdnichollsc** [scottie1984/swagger-ui-express#76]
Hi guys,

I'm getting the following issue:

```
Errors
Hide
Parser error on line 14
end of the stream or a document separator is expected
```

And my JSON is:
```
{"swagger":"2.0","info":{"title":"REST API","version":"1.0.0","description":"This is a REST API for the Enturnate app","contact":{"email":"edwin.bustos@linkarga.com"}},"basePath":"/","paths":{"/swagger.json":{"get":{"tags":[],"description":"","responses":{"200":{"description":"Returns the swagger.json document"}},"parameters":[]}},"/auth/login":{"post":{"tags":[],"summary":"Authenticate the user","description":"Validate if exist an user with that email and password","responses":{"200":{"description":"Returns the token and the info of the user"}},"parameters":[{"name":"body","in":"body","schema":{"type":"object","properties":{"email":{"type":"string"},"password":{"type":"string"}}},"required":false}],"consumes":["application/json"],"produces":["application/json"],"addedParameters":{"body":{"body":true}}}},"/auth/signup":{"post":{"tags":[],"description":"","responses":{"200":{"description":"Returns example 1"}},"parameters":[]}}}}
```

Let me know what you think, Nicholls

**Comment by jdnichollsc** [comment]
Thanks @scottie1984 
This issue was fixed using the following configuration:
```
app.use('/', swaggerUi.serve, swaggerUi.setup(null, {
  swaggerUrl: '/swagger.json',
  swaggerOptions: {
    validatorUrl : null
  }
}));
```

**Comment by vpaflah** [comment]
I have a same kind of error, when searching using explore section in swagger docs.

The error can be produced by pasting the below code into [swagger editor](https://editor.swagger.io/).

`/**
 * @swagger
 *   /api/v1/therapies/{TherapyID}:
 *     put:
 *       summary: Therapy Updation
 *       security:
 *        - bearerAuth: []
 *       tags:
 *         - Therapies
 *       parameters:
 *         - in: path
 *           name: TherapyID
 *           required: true
 *           schema:
 *             type: integer
 *       requestBody:
 *           required: true
 *           content:
 *             application/json:
 *               schema:
 *                 type: object
 *                 properties:
 *                   TherapyName:
 *                     type: string
 *                     required: true
 *                   AgeGroup:
 *                     type: string
 *                     required: true
 *                   Status:
 *                     required: true
 *                     type: boolean
 *       responses:
 *         "200":
 *           description: Request was successful
 *           content:
 *             application/json:
 *               schema:
 *                 type: object
 *                 properties:
 *                   success:
 *                     type: boolean
 *                     description: If the request is falied or not
 *                   results:
 *                     type: object
 *                     properties:
 *                       message:
 *                         type: string
 *                         example: Therapy updated successfully
 *         "404":
 *           description: Not Found
 *           content:
 *             application/json:
 *               schema:
 *                 type: object
 *                 properties:
 *                   success:
 *                     type: boolean
 *                     description: If the request is falied or not
 *                     example: false
 *                   errors:
 *                     type: object
 *                     properties:
 *                       message:
 *                         type: string
 *                         example: Not found
 *         "500":
 *           description: Internal server error
 */`
