### ISSUE TITLE
swagger-ui version 3.17.0 - Fix for multipart/form-data

### ISSUE THREAD

**Issue by Francula** [scottie1984/swagger-ui-express#77]
Hi, 
I have an issue with the current swagger-ui version. It contains a bug that makes it impossible to work with multipart/form-data. This bug is fixed with 3.16 (https://github.com/swagger-api/swagger-ui/issues/3781). Could you please update?
Thanks francula

**Comment by scottie1984** [comment]
Hi, 

I have updated to swagger 3.17.1, hopefully this fixes your issue.

Thanks
Stephen
