### ISSUE TITLE
Set-Cookie response header not appearing in 'response headers' box

### ISSUE THREAD

**Issue by JeremyColton** [scottie1984/swagger-ui-express#80]
Hi, I have 2 servers: UI and API. To accommodate CORS:
a) The client login request sets:
credentials: 'include'
b) The login response has a "Set-Cookie" HTTP header. This works when run via my UI in Chrome.

But when I run the login API using your project (v2.0.11 and swagger-jsdoc v.1.9.7) I see the Set-Cookie response header in the console but not in the UI's 'response headers' box:
![capture](https://user-images.githubusercontent.com/2919478/42509789-b85869ee-8455-11e8-9ee3-95ae1d1e0836.PNG)

Because of this ALL my other APIs are failing since they need the cookie to be sent with each API request.

I read that "Cookie authentication is supported in OpenAPI 3.0 but not in OpenAPI/Swagger 2.0" from https://stackoverflow.com/questions/36924317/how-to-use-cookies-in-swagger-editor but this comment didnt' receive any points so i'm not sure if it's correct.

https://swagger.io/docs/specification/2-0/authentication/ also doesn't have a cookie example but doesn't say that are not supported!

Set-cookie is supported by this project? This is a limitation of OpenAPI 2.0?

**Comment by scottie1984** [comment]
This project is simply a wrapper around swagger-ui for express. After reviewing the documentation for swagger is does look like cookie based authentication is only available in OpenAPI 3.0:

[Cookie Auth](https://swagger.io/docs/specification/authentication/cookie-authentication/)

This doesn't seem to be available in OpenAPI 2.0: [Authentication in OAS 2](https://swagger.io/docs/specification/2-0/authentication/)

**Comment by yurenchen000** [comment]
I guess the low-level reason is that,
  browser js can't access all ajax response headers, as security restrictions.

https://stackoverflow.com/questions/12840410/how-to-get-a-cookie-from-an-ajax-response
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
