### ISSUE TITLE
Support for different swagger files

### ISSUE THREAD

**Issue by danielrentz** [scottie1984/swagger-ui-express#81]
Is it possible to let this module serve different (complete) swagger files? Say, for example,

swagger/admin.yml under localhost:3000/api-docs/admin-api.html

and

swagger/public.yml under localhost:3000/api-docs/public-api.html

**Comment by scottie1984** [comment]
I believe the following issue should be able to help with this:

https://github.com/scottie1984/swagger-ui-express/issues/65

Any problems, please let me know.

**Comment by danielrentz** [comment]
Thanks! Would be great if this can be added in the readme ...

**Comment by scottie1984** [comment]
Good point. Yeh I will add it in :)

**Comment by danielrentz** [comment]
Thanks again. The solution works like a charm.
