### ISSUE TITLE
customeSiteTitle option not working 

### ISSUE THREAD

**Issue by mohit125** [scottie1984/swagger-ui-express#82]
hi i am new to github so don't know how to raise a question here correctly or whether to change and raise a pull request , i found a issue at generateHTML function variable customeSiteTitle field in opts object , there  spelling mistake in the current release which is causing issue in using  customeSiteTitle option
in index.js file 
`var generateHTML = function (swaggerDoc, opts, options, customCss, customfavIcon, swaggerUrl, customeSiteTitle) {
  var isExplorer
  var customJs
  if (opts && typeof opts === 'object') {
    isExplorer = opts.explorer
    options = opts.swaggerOptions
    customCss = opts.customCss
    customJs = opts.customJs
    customfavIcon = opts.customfavIcon
    swaggerUrl = opts.swaggerUrl
    customeSiteTitle = opts. customSiteTitle
  }`

**Comment by scottie1984** [comment]
I can see that it is spelt incorrectly but not sure what issue this is causing you directly? If you are using the opts object assign the title to the 'customSiteTitle' property.

**Comment by mohit125** [comment]
@scottie1984 
not causing a issue i am using it as you mentioned and it is working for me , i just pointed out as i found that mostly everyone will try using the fieldName as `customeSiteTitle` as other naming are matching correctly for ex- customCss or customfavIcon

**Comment by scottie1984** [comment]
cool - glad there is no direct issue. I will include a fix in a future release.
