### ISSUE TITLE
Security release 3.18

### ISSUE THREAD

**Issue by regisbsb** [scottie1984/swagger-ui-express#85]
https://github.com/swagger-api/swagger-ui/releases

^^^^^^^^^^^^^^^^^^^

 This release contains security fixes. If your OpenAPI documents link to untrusted external URLs, you should upgrade.

**Comment by shockey** [comment]
I think this can be closed, as `master`'s `package.json` now relies on a minimum of `swagger-ui-dist@3.18.1`:

https://github.com/scottie1984/swagger-ui-express/blob/76d21d4b6ec888d63fc0cbdd95db59d8c1436f63/package.json#L48
