### ISSUE TITLE
README.md encourages users to install `@latest`

### ISSUE THREAD

**Issue by shockey** [scottie1984/swagger-ui-express#86]
### Currently...

The README encourages users to install `swagger-ui-express` by manually copying `"swagger-ui-dist": "latest"` into their package manifest.

ref: https://github.com/scottie1984/swagger-ui-express/blob/master/README.md#usage

### Thoughts

I think this is an antipattern, because...
1. copy-pasting into a manifest will not trigger regeneration of a lock file, which could lead to weird behavior, up to and including missing dependencies at runtime
2. it encourages users to install `@latest`, which will automatically expose them to breaking changes (major version bumps) within this module in the future

### Desired behavior

I think the README should instead include a command-line install one-liner, i.e. `npm install swagger-ui-express` or `yarn add swagger-ui-express`.

**Comment by scottie1984** [comment]
Agreed, will be included in the next version.

**Comment by lacivert** [comment]
I guess this issue can be closed
