### ISSUE TITLE
How to use swagger v2

### ISSUE THREAD

**Issue by song50119** [scottie1984/swagger-ui-express#87]

**Comment by scottie1984** [comment]
Make sure your swagger file has the attribute "swagger": "2.0".

**Comment by pvsong** [comment]
Thanks, another thing
How can I make the themes like this
http://meostrander.com/swagger-ui-themes/demo/index.html#/

**Comment by pvsong** [comment]
That would be cool, if we have more options so we can switch between themes v2/v3 :)

**Comment by scottie1984** [comment]
You should now be able to use the customCssUrl option to specify the themes via the theme url. https://github.com/scottie1984/swagger-ui-express#custom-css-styles-from-url
