### ISSUE TITLE
Multiple swagger instances

### ISSUE THREAD

**Issue by karpoff** [scottie1984/swagger-ui-express#92]
Hi
I have two swaggers in my project and I want to add them both 
I've tried the following way
```
app.use('/swagger-public, swaggerUi.serve, swaggerUi.setup(swaggerPublicSpec));
app.use('/swagger-internal, swaggerUi.serve, swaggerUi.setup(swaggerInternalSpec));
```
but I see that  /swagger-public shows me internal spec. And If I move swagger-internal before swagger-public I see that both endpoint shows me swagger-public spec

So as I see only latest result of swaggerUi.setup is used
Can I configure multiple swagger instances somehow?

**Comment by karpoff** [comment]
I've found the following workaround:
```
interface ISwaggerConfig {
    key: string;
    spec: any;
}
const addSwaggerEndpoint = (app: express.Express, instances: ISwaggerConfig[]) => {
    const baseUrl = '/swagger/';

    app.use(baseUrl, swaggerUi.serve, (req: express.Request, res: express.Response, next: express.NextFunction) => {
        const item = req.originalUrl.substr(baseUrl.length);
        const instance = instances.find(i => i.key === item);

        if (!instance) {
            next();
            return;
        }

        res.send(swaggerUi.generateHTML(instance.spec));
    });
};

```

so then I can use
```
addSwaggerEndpoint(app, [
                {key: 'public', spec: swaggerPublic},
                {key: 'internal', spec: swaggerInternal},
            ]);
```
and I will have my swaggers available at /swagger/public and /swagger/internal

**Comment by jk89** [comment]
Exactly the same issue here

**Comment by Jammjammjamm** [comment]
The solution above didn't work for me, but this did:

```
const useSchema = schema => (...args) => swaggerUi.setup(schema)(...args);

app.use('/api/schema1', swaggerUi.serve, useSchema(schema1));
app.use('/api/schema2', swaggerUi.serve, useSchema(schema2));
```

**Comment by Snake1980** [comment]
Hi!
Thanks @Jammjammjamm ! Great work!
but...is it possible to generate HTML at runtime and not when I start the app?

**Comment by Jammjammjamm** [comment]
That wasn't functionality I needed, but does my workaround not generate the HTML at runtime? I'm not an express expert, but I would assume that the functions passed to `use` aren't called until a client hits that endpoint.

**Comment by Snake1980** [comment]
I hit an endpoint then I update the related swagger document and hit the same endpoint, the generated HTML is related to the old swagger document version. The new HTML is available when application restarts

**Comment by scottie1984** [comment]
Have you tried using generateHTML?

```javascript
app.get('/api-docs', (req, res) => { res.send(swaggerUi.generateHTML(swaggerDocument, swaggerUiOpts)) });
```

**Comment by Snake1980** [comment]
Tried today, but the result is an empty HTML + css

**Comment by scottie1984** [comment]
Another option is to load the swagger document from a url.

If you check the section of the readme for ‘Load swagger from url’. You can pass the url of your swagger document which you can host on your api via normal express options.

**Comment by scottie1984** [comment]
https://github.com/scottie1984/swagger-ui-express/issues/65#issuecomment-378280126

**Comment by joticajulian** [comment]
Following the response of @Jammjammjamm I did it in this way

```
app.use("/api-docs1", swaggerUi.serve, (...args) => swaggerUi.setup(doc1)(...args));
app.use("/api-docs2", swaggerUi.serve, (...args) => swaggerUi.setup(doc2)(...args));
```
