### ISSUE TITLE
validationUrl apparently not working

### ISSUE THREAD

**Issue by Javirln** [scottie1984/swagger-ui-express#93]
Hello,

I've installed the latest version of **swagger-ui-express (4.0.1)** on **express (4.14.1)**. I've declare the like following:

Importing the necessary files:
```
const swaggerUi = require('swagger-ui-express');
const swaggerDoc = require(pathToFileInJson);
```
Declaring swagger UI:
```
app.use('/documentation', swaggerUi.serve, swaggerUi.setup(swaggerDoc, {
  validatorUrl: null
}));
```

That works totally fine and the `Validation badge` is not shown but, if I go like this instead:
```
app.use('/documentation', swaggerUi.serve, swaggerUi.setup(null, {
  validatorUrl: null,
  swaggerUrl: 'UrlToMyServerWithSwaggerSpecification'
}));
```
The badge is shown and giving back and error since the server is protected through a VPN. I expected badge not be shown since I have the same option set for both cases.

Thanks in advance,
Javi.

**Comment by scottie1984** [comment]
The validatorUrl should be in an object swaggerOptions:

```
app.use('/documentation', swaggerUi.serve, swaggerUi.setup(null, {
  swaggerOptions: { 
     validatorUrl: null
  },
  swaggerUrl: 'UrlToMyServerWithSwaggerSpecification'
}));
```

**Comment by Javirln** [comment]
That was it @scottie1984, thanks so much!
