### ISSUE TITLE
/api-docs/index.html shows default Petstore API

### ISSUE THREAD

**Issue by endoval** [scottie1984/swagger-ui-express#94]
Hi @scottie1984,

when upgrading swagger-ui-express from version 3.0.10 to 4.0.0+ the correct Swagger API is shown on /api-docs but not /api-docs/index.html. We use code similar to this:

```
const express = require('express');
const app = express();
const swaggerUi = require('swagger-ui-express');

var options = {
  swaggerUrl: '/path/to/our/swagger.json'
}

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(null, options));
```

The reason is that if you navigate directly to the index.html the swaggerUi.serve already handles the request and the middleware from swaggerUi.setup is not called.

According to research the following commit seems to cause the issue: https://github.com/scottie1984/swagger-ui-express/commit/cdb6d968b9c0b0a43755bb6eea4a20199b8a4210

Cheers :)

**Comment by Trapholov** [comment]
@scottie1984 works for me, thanks.
