### ISSUE TITLE
openapi: 3.0.0 support

### ISSUE THREAD

**Issue by Frankoloko** [scottie1984/swagger-ui-express#96]
Hi there. Am I right by saying that swagger-ui-express doesn't support `openapi: 3.0.0 support`? A lot of my yaml code is not being created for some reason (like the `servers:` option)

**Comment by scottie1984** [comment]
Hey, swagger-ui-express does support openapi: "3.0.0". My only suggestion is to try placing your swagger document here: [https://editor.swagger.io/](https://editor.swagger.io/) and ensuring it is valid

**Comment by Frankoloko** [comment]
I actually wrote it there first before adding it to swagger-ui-express. I attached the yaml below to have a look at. Still for some reason it is not displaying the servers, or the try out button. Also the css options example is not doing anything at all.

[New Text Document (3).txt](https://github.com/scottie1984/swagger-ui-express/files/2433395/New.Text.Document.3.txt)

**Comment by scottie1984** [comment]
@shockey this seems to be an issue introduced in swagger ui 3.19.1, I tested locally reverting back to swagger-ui-dist 3.19.0 and it seems to work. 

@Frankoloko if you add `"swagger-ui-dist": "3.19.0"` to your dependencies (and reinstall swagger-ui-express) it should work as you expect. The css example will remove the Swagger UI topbar.

**Comment by scottie1984** [comment]
The issue is already filed with swagger ui [https://github.com/swagger-api/swagger-ui/issues/4912](https://github.com/swagger-api/swagger-ui/issues/4912)

**Comment by Frankoloko** [comment]
Where exactly do I add this value `"swagger-ui-dist": "3.19.0"` and how do I reinstall swagger-ui-express? Sorry but I tried everything I understand but I can't seem to get this working haha. It keeps installing 3.19.1

**Comment by scottie1984** [comment]
Add `"swagger-ui-dist": "3.19.0"` to your package.json. Delete swagger-ui-express from your node_modules and `npm install`

**Comment by Frankoloko** [comment]
Thanks @scottie1984 That worked perfectly. Just to add, I had to delete `swagger-ui-dist` from my `node_modules`. Not `swagger-ui-express`

@shockey Add good thanks man! Good luck!
