### ISSUE TITLE
Swagger ui doesn't show api response data when data is falsy.

### ISSUE THREAD

**Issue by jk89** [scottie1984/swagger-ui-express#97]
Hi I wrote a route which returns a boolean, the Response body is hidden when its false, similar issue maybe with the example value, if the example is falsy the example value appears hidden. Great lib otherwise chaps really enjoying it!

**Comment by scottie1984** [comment]
Hey - this sounds like an issue with swagger ui. I suggest filing an issue with them [https://github.com/swagger-api/swagger-ui/issues/new?template=Bug_report.md](https://github.com/swagger-api/swagger-ui/issues/new?template=Bug_report.md)
