### ISSUE TITLE
For one to use YAML, one needs to import yamljs

### ISSUE THREAD

**Issue by mwaz** [scottie1984/swagger-ui-express#98]
I would like to request a direct import of YAML files something like

`import SwaggerDocument from 'docs/swagger.yaml'`

currently one has to first import yamljs then convert it
```
import YAML from 'yamljs';
const swaggerDocument = YAML.load('docs/swagger.yaml');
```

**Comment by nickforddesign** [comment]
Using `import` with yaml would only be possible via webpack and a yaml loader, which would have to be set up in your project, not the `swagger-ui-express` library.

**Comment by shockey** [comment]
Is `swagger-ui-express` using the definition object for anything?

If not, I could make it possible* to pass a YAML string directly into Swagger UI, which would make this flow much simpler (just use `fs.readFileSync` to get the string, no YAML lib required).

_*: I actually think this works now, it just isn't documented_

**Comment by scottie1984** [comment]
@shockey it doesn't use the definition object for anything. Keen to hear the option for this.
