### ISSUE TITLE
description message is not getting displayed with example object

### ISSUE THREAD

**Issue by AyUsH988** [scottie1984/swagger-ui-express#99]
Hi, i wrote a swagger, where in response block i want to display a description and a example object. But i am unable to do that together, either the description message can be displayed or the example object can be displayed.
So this is part of my swagger where i am not getting the description message
*     responses:
*       200:
*         description: OK
*         type: object
*         items:
*          $ref: '#/definitions/RegOrganisation'

so i want both the description and the example object to be displayed.
i have attached the screenshot of my swagger how it is displayed.
so just have a look on this issue.
![swaggerissue](https://user-images.githubusercontent.com/36485529/46808377-d4405680-cd89-11e8-8662-91faca8312bd.png)

**Comment by scottie1984** [comment]
hey - this looks like an issue with swagger-ui. Can you raise directly with them? [https://github.com/swagger-api/swagger-ui/issues/new/choose](https://github.com/swagger-api/swagger-ui/issues/new/choose)
